### ISSUE TITLE
Reduce coupling with System.Web and System.Web.Mvc

### ISSUE THREAD

**Issue by Hihaj** [twilio/twilio-csharp#105]
There are a couple of unnecessary dependencies between convenience types and `System.Web` as well as `System.Web.Mvc` that I feel should be eliminated to improve usability of the library going forward.

For example, the various `*Request` classes in `Twilio.Mvc` classes really don't have any dependency on `System.Web.Mvc`, and since they are handy when using other web frameworks than ASP.NET MVC (for example [Nancy](http://nancyfx.org/)) they could very well be moved to a web framework-neutral package.

The same goes for the `RequestValidator` class in `Twilio.Twiml` - it is super useful regardless of the choice of server host, so why is it written to assume that the application builds atop of `System.Web`? With OWIN-compatible servers like [Katana](http://www.asp.net/aspnet/overview/owin-and-katana/an-overview-of-project-katana) gaining popularity I think it would make sense to factor out the core request validation algorithm into a separate component.

**Comment by jingming** [comment]
For the new version of the library we have to tried to remove as many dependencies as possible. 

Regarding `Twilio.Mvc`, it has been removed from this library and moved its own artifact.
