### ISSUE TITLE
Overload Needed

### ISSUE THREAD

**Issue by interactivelion** [twilio/twilio-csharp#112]
Hi,

 I need overloads for the following in TwiML.

DialClient
DialClients

Currently I can only pass a client or array of clients. 
I need to set some attributes to the wrapping Dial tag such as recordcall and timeout.

Thanks in advance,
Chris

**Comment by jingming** [comment]
@interactivelion We have updated the TwiML generator in the latest release of the library. Please let us know at help@twilio.com if you continue to have trouble.
