### ISSUE TITLE
ListCalls specifies "EndTime", "EndTime<", and "EndTime>" query parameters

### ISSUE THREAD

**Issue by alexcchan** [twilio/twilio-csharp#120]
https://github.com/twilio/twilio-csharp/blob/master/src/Twilio.Api.Silverlight/Calls.Async.cs#L48

"EndTime" is not a valid query parameter for the calls list resource:

https://www.twilio.com/docs/api/rest/call#list-get-filters

The valid time parameters are "StartTime", "StartTime<", and "StartTime>".

**Comment by jpadgeo** [comment]
Will EndTime ever be supported by the API?  It would be nice if we could query for completed calls after a certain EndDateTime, which would allow us to just remember the last time we pulled a record.

Also, I think there is a bug in the StartTime as it is only using the Date, I have a fix to use Date and Time, should I create a new issue and checkin the code against that?

**Comment by jingming** [comment]
We released a new version of the library that should address the `StartTime` issues. Please let us know if you continue to see problems.
