### ISSUE TITLE
ValidateRequestAttribute does not work with WebAPI - please add WebAPI verson

### ISSUE THREAD

**Issue by bubbafat** [twilio/twilio-csharp#122]
ValidateRequestAttribute does not work with WebAPI projects - only MVC.  This requires everyone who wants to use WebAPI to roll their own solution.

See this blog post for a suggested implementation:

http://blogs.endjin.com/2013/01/a-step-by-step-guide-to-building-a-twilio-voice-app-with-web-api/

**Comment by 0xdeafcafe** [comment]
Would this really be worth implementing? As of the next version of of MVC (MVC6), WebAPI has been merged into the MVC code base.

**Comment by jhurdlow** [comment]
Because of the significant changes in ASP.NET 5, most existing projects will not be updated, so they will be around for years. I think it does make sense to do this. In the meantime I just add this inside my WebAPI methods:

```csharp
var validator = new RequestValidator();
var isValidRequest = validator.IsValidRequest(HttpContext.Current, twilioAccount.AuthToken);
```

**Comment by jingming** [comment]
Answered.
