### ISSUE TITLE
latest restsharp breaks this lib

### ISSUE THREAD

**Issue by artfulhacker** [twilio/twilio-csharp#139]
An exception of type 'System.MissingMethodException' occurred in Twilio.Api.dll but was not handled in user code

Additional information: Method not found: 'Void RestSharp.RestClient.set_BaseUrl(System.String)'.

**Comment by shawnlivermore** [comment]
Problem... 

This same issue seems to exist today,... perhaps when you updated this 3 days ago it failed to have necessary info / data ?

Trying to instantiate the rest object with this line of code: 
var twilio = new TwilioRestClient(AccountSid, AuthToken);

>> ERROR: Method not found: 'Void RestSharp.RestClient.set_BaseUrl(System.Uri)'.
