### ISSUE TITLE
Wiki needs to be updated with the latest async API

### ISSUE THREAD

**Issue by naveensrinivasan** [twilio/twilio-csharp#144]
The Wiki does not have any samples or user API documentation for the new async implementation. 
 For example `await twilio.ListMessages(new MessageListRequest() )` the ListMessages has an overload which takes a new class instead of multiple parameters.

**Comment by jhurdlow** [comment]
What is the latest version that supports async anyway? I'm using 3.7.55 alpha and it's getting frustrating trying to work with that version via nuget. Is there a later release with async? When will we see the async stuff in the main release branch?

**Comment by jingming** [comment]
hey! we've added XML comments have been added and HTML docs are published here: https://twilio.github.io/twilio-csharp/
