### ISSUE TITLE
Twilio consumes error not giving any feedback to the user.

### ISSUE THREAD

**Issue by tharris29** [twilio/twilio-csharp#151]
When making a call to the API to obtain messages (Potentially other calls) Twilio doesn't error if you keys or anything else is wrong. This means it is unclear to why the results have not come back.

````
 var messages = _client.ListMessages(options);

````

In the code example above you need to check that "messages.Messages" is not null. Null test suck if I have no messages give me a count of 0. If I have an error give me the error, let me decide what to do with it.

**Comment by devinrader** [comment]
You can test to see if the RestException property is null:

    var messages = client.ListMessages(options)
    if (messages.RestException != null) {
        Console.Writeline(messages.RestException.Message);
    }

Hope that helps.

**Comment by tharris29** [comment]
Oh! thanks.
