### ISSUE TITLE
TURN/STUN Twilio methods missing

### ISSUE THREAD

**Issue by Harinder** [twilio/twilio-csharp#153]
Looks like some methods are missing in latest Twilio Api

I am following steps (C#) as mentioned in following URL.
https://www.twilio.com/docs/stun-turn

However CreateToken() method is not availabe in latest version of TwilioRestClient

**Comment by alexcchan** [comment]
It looks like these were added in 3.6.25 but excluded from 3.6.26 (NuGet package versions).

**Comment by devinrader** [comment]
Not sure why, but looks like a bunch of files got excluded from the project file.  They've been readded and 3.6.27 pushed to nuget.
