### ISSUE TITLE
Twilio SMS is not woking on Windows azure (ASP.net MVC web role)

### ISSUE THREAD

**Issue by Sampath-Lokuge** [twilio/twilio-csharp#156]
var client = new TwilioRestClient(ConstantKeys.AccountSid,ConstantKeys.AuthToken); // instantiate a new Twilio Rest Client

    var messageCallBack = client.SendMessage(ConstantKeys.SmsEnabledTwilioNumber, mobileNumber, smsMessage);

Above code snippet is working fine on localhost but when we publish and try to use the same on live site we are getting a 500 error.We are using windows azure for hosting our website (as a web role).It doesn't reach the first line of the above code on production.Can you tell me why ? Any help would be highly appreciated.

Note 1:I have checked the dlls on published version.It's having below dlls. Twilio.Api.dll and RestSharp.dll

Note 2 : I have installed Twilio dependencies by using Nuget package.

**Comment by devinrader** [comment]
Just pushed a new version to NuGet which should resolve this issue.
