### ISSUE TITLE
Twilio SMS is not woking on Windows azure (ASP.net MVC web role) - Part 2

### ISSUE THREAD

**Issue by Sampath-Lokuge** [twilio/twilio-csharp#157]
According to this issue (https://github.com/twilio/twilio-csharp/issues/156) where I have updated the Twlio.Mvc nuget.But now I have different issue on production.It's working fine on local host.Please check that.Thanks in advance.

    Method not found: 'Void RestSharp.RestClient.set_BaseUrl(System.Uri)'.

**Comment by devinrader** [comment]
That looks like RestSharp (which the Twilio library depends on) is either not getting deployed or the wrong version is getting deployed.
