### ISSUE TITLE
Twilio SMS is not woking on Windows azure (ASP.net MVC web role) - Part 3

### ISSUE THREAD

**Issue by Sampath-Lokuge** [twilio/twilio-csharp#158]
According to this issue (#157) where I have used nuget to update the assemblies.Then how can it be wrong version ? 

Dlls on production as shown below : 

```
Twilio.Api.dll - Ver 3.4.1.0

RestSharp.dll - Ver 105.0.1
```

Please check that and let me know.Thanks in advance.

**Comment by devinrader** [comment]
3.4 is a very old version of the Twilio nuget package.  You should upgrade this.  Current version is 3.6.27

https://www.nuget.org/packages/Twilio

**Comment by devinrader** [comment]
I just realized you were saying this is the DLL version, not the package version.

Are you sure that all of your assemblies are being deployed?

**Comment by Sampath-Lokuge** [comment]
Yes you're right.Please check the Twilio package versions on 'packages.config' file. 

     <package id="RestSharp" version="105.0.1" targetFramework="net45" />
     <package id="Twilio" version="3.6.27" targetFramework="net45" />
     <package id="Twilio.Mvc" version="3.1.14" targetFramework="net45" />
     <package id="Twilio.TwiML" version="3.3.5" targetFramework="net45" />

**Comment by Sampath-Lokuge** [comment]
On production I can see only 2 dlls.Those are as shown below.

**Comment by devinrader** [comment]
Well if you are using the Twilio.Mvc package and the Twilio.TwiML package I would expect to see those assemblies deployed as well, but I'm not an expert in Azure Web Roles so I don't know for sure how it packages a website for publication.

I tried to replicate what you are seeing on my end by creating a new ASP.NET MVC site, adding the Twilio nuget package, adding code to the Home controller that sends me a text message and then deployed it to an Azure Cloud Service as a Web Role.   Unfortunately I was unable to replicate the issue.

**Comment by Sampath-Lokuge** [comment]
Do you have "Twilio.Mvc" on your published version ?

**Comment by Sampath-Lokuge** [comment]
I do have web application.Not a web site.I have added all the above dlls into my web project.But unfortunately the error is the same.It's working fine on local host.Not working on azure web role ?

    Method not found: 'Void RestSharp.RestClient.set_BaseUrl(System.Uri)'.

**Comment by devinrader** [comment]
I added the Twilio.Mvc package to my sample app, changd the HomeController clas to derive from TwilioController and created a method in the controlle that generates and returns TwiML.  Thats a pretty good exercise of the library.  

Unfortuantely I was unable to replicat your issue when I deploy the site as a Web Role into my Azure  Cloud Service.

**Comment by jingming** [comment]
`Twilio.Mvc` has been moved out of this package and to https://www.nuget.org/packages/Twilio.AspNet.Mvc. Please follow up there if you are still having issues.
