### ISSUE TITLE
Phone Number Verification

### ISSUE THREAD

**Issue by vivekjamla** [twilio/twilio-csharp#161]
Hello,

I do not know exactly this is issue or not. i am using trial account and i have verified two phone numbers online at my account. I was keep trying using c# console application to test calling and messaging. but it was giving me error like "number is not verified with your account"

But i tried verifying using below method and it started working completely fine.

var result = client.AddOutgoingCallerId("+1937654****", "Verified Number", null, null);
            if (result.RestException != null)
            {
               Debug.WriteLine(result.RestException.Message);
            }
           Debug.WriteLine(result.ValidationCode); 

Again I might be wrong but i thought it would save other persons time if you include it in documentation

Regards
Vivekkumar Patel.

**Comment by devinrader** [comment]
Hey @vivekjamla .  I'm not entirely clear on the problem you ran into.

Are you saying you verified a couple of phone numbers via your Twilio dashboard then tried to send a message or make a call with them and got the "not verified" error?  After adding them via the API you were able to use them to send a message or make a call?

**Comment by vivekjamla** [comment]
Hey @devinrader  

yes I verified two numbers using dashboard and keep getting that "not verified" error. and once I verified with API I was able to call and send text as well.

**Comment by jingming** [comment]
@vivekjamla Please redirect this question to help@twilio.com if you are still seeing it.
