### ISSUE TITLE
Twilio C# Client should work with .NET Core/ ASP.NET 5

### ISSUE THREAD

**Issue by rustd** [twilio/twilio-csharp#163]
Now that ASP.NET 5 can run on .NET Core. It would be great if Twilio could update their C# client to build on these platforms so users can use Twilio.

**Comment by mplacona** [comment]
Hey, we have the library running on ASP.NET5 as you can see [here](https://www.twilio.com/blog/2015/08/getting-started-with-asp-net-5-and-visual-studio-code-on-a-mac.html), however it is still not stable on CORE CLR.

**Comment by joeaudette** [comment]
fyi, for anyone who needs it, I have working code for sending sms with twilio REST API that works on .NET Core 
https://github.com/joeaudette/cloudscribe/blob/master/src/cloudscribe.Messaging.Sms/TwilioSmsSender.cs

it is very basic but it does the job if all you need is a way to send an message for 2 factor authentication, ie for asp.net identity phone number verification

**Comment by dcworldwide** [comment]
> Hey, we have the library running on ASP.NET5 as you can see here, however it is still not stable on CORE CLR.

@mplacona It has been 6 months since this comment. Is this lib now stable to run on .net core? For those of us who which to run twilio on docker and use .net, this is a really important capability. Thanks.

**Comment by joeaudette** [comment]
@dcworldwide did you see my previous comment? I posted a link to code you can use today using the twilio rest api on .NET Core. I'm using it for 2 factor auth in my app and it works well.
I'm sure twilio will get around to making their library support .NET Core, but after all, .NET Core is not released yet. Nevertheless, I would not let that hold you back, since it is easy to get it working.

**Comment by dcworldwide** [comment]
Thanks Joe, i'll look into your work more. Great job getting it working. I was chasing something more official that's all.

**Comment by mplacona** [comment]
We're working on a brand new version of the library that will support the
latest version of the .Net Core 1.0. I know it's taking a long time, but
we'll have it on GA soon!

On Saturday, 19 March 2016, Danijel Cole <notifications@github.com> wrote:

> Thanks Joe, i'll look into your work more. Great job getting it working. I
> was chasing something more official that's all.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/twilio/twilio-csharp/issues/163#issuecomment-198632311>
>


-- 
Marcos Placona
www.placona.co.uk

**Comment by marchy** [comment]
@mplacona That's great to hear it. Any betas we can get access to in the meanwhile? Azure has officially stopped running RC1 apps and are forcing everyone to update to RC2 - which means requiring .NETStandard. This just because an immediate burning issue!

**Comment by antonellil** [comment]
Looking forward to this! Only thing stopping my project from moving off Mono

**Comment by jackhamburger** [comment]
This would be much appreciated so I can get on dotnetcore, any update on the progress?

**Comment by marchy** [comment]
.NET Core 1.0 [has been launched](https://blogs.msdn.microsoft.com/dotnet/2016/06/27/announcing-net-core-1-0/)!

How're we lookin on that Core CLR version, team Twilio??

**Comment by GuardRex** [comment]
Good progress, but as @marchy said, we need CoreCLR support (i.e., `netstandard1.x` TFM) to include in `netcoreapp1.0` applications (for example headed for Nano Server). REST API is fine, but it would be nice to take existing Twilio lib code and just make a handful of updates. Any status to report @mplacona?

**Comment by SimonTouchtech** [comment]
For @GuardRex and anyone else wondering about the progress, it seems like work is being done in the next-gen branch. On June 30th there was a commit (https://github.com/twilio/twilio-csharp/commit/b99e2eba3ebf355f9d08306379197850143316e8) made to add .NET Standard (1.4) support.

**Comment by senwen** [comment]
Any further updates on this? We are also waiting to use Twilio on CORE.
Cheers.

**Comment by adamreed90** [comment]
Any update on this? Would really like to see a .NET Core Release?

**Comment by ArashMotamedi** [comment]
While we eagerly await the release of an official .NET Core Twilio library, I just published a package as a stop-gap measure for folks looking for a drop-in solution for their projects.

Here's the package: https://www.nuget.org/packages/Twilio.NetCore 
And here's the source code: https://github.com/ArashMotamedi/twilio.netcore

The original library has a dependency on RestSharp, which I replaced with RestSharp.NetCore. A couple lines of code were needed to make it work with RestSharp.NetCore, but otherwise, the source is identical to the original library. I did not port the unit tests, so please do extensive testing before using this package. Also, be a hero and port the original tests over to the repo linked above :)

**Comment by marchy** [comment]
That's awesome @ArashMotamedi thanks for doing that for everyone  :)

**Comment by SD-Abhi** [comment]
I want to use twilio for browser to browser call in .Net core 2.0 .But I have compatibility issues. Any help would be appreciated.
Thanks

**Comment by Rick-Anderson** [comment]
@SD-Abhi  this isn't a support forum. Try SO, but you'll need to be much more specific.

**Comment by ArashMotamedi** [comment]
Just updated and published a .Net Core 2 compatible package.

Source: https://github.com/ArashMotamedi/Twilio.NetCore
Nuget: https://www.nuget.org/packages/Twilio.NetCore/2.0.0
PM: Install-Package Twilio.NetCore -Version 2.0.0

Thanks,
Arash

**Comment by a-patel** [comment]
Thanks @ArashMotamedi
