### ISSUE TITLE
Async library update?

### ISSUE THREAD

**Issue by bunceg** [twilio/twilio-csharp#164]
I notice there have been a number of official releases since this original issue https://github.com/twilio/twilio-csharp/issues/127 was raised 7 months ago. Can you let me know if the branch referred to in this original issue is dead or, if not, the planned date for updating the v4.x version to include async methods?

Thanks

**Comment by devinrader** [comment]
hey @bunceg, you can grab version [3.8.45-beta](http://www.nuget.org/packages/Twilio/3.8.45-beta) which was updated in March.

**Comment by bunceg** [comment]
Thanks - any news on when this will make it into live?

**Comment by devinrader** [comment]
@bunceg nothing to announce right now, but feel free to give it a try and let us know if there is anything thats missing or not working as you expect.
