### ISSUE TITLE
ValidateRequestAttribute and "unsafe" characters

### ISSUE THREAD

**Issue by bslatner** [twilio/twilio-csharp#168]
A frequent issue I have in my SMS-based apps is that sometimes people send "unsafe" characters in their messages. For example, < and >. Usually these are part of some weird signature they put on all their outgoing messages. This causes the MVC framework to throw an HttpRequestValidationException exception.

The regular MVC way to deal with this is to add [ValidateInput(false)] on your action method. However, I also use the ValidateRequestAttribute from Twilio to validate Twilio's signature on the incoming message. ValidateRequestAttribute news up a RequestValidator() object which, in turn, enumerates the incoming POST values. If the incoming message body has a < or a > in it, the call to context.Request.Form[key] triggers the same validation and causes the HttpRequestValidationException.

I think that the invocation of context.Request.Form[key] should be context.Request.Unvalidated.Form[key] instead. There is no particular danger in doing this since the ValidateRequestAttribute isn't persisting the form values in any way that might later trigger an XSS attack or similar, which is what the validator is attempting to prevent.

**Comment by kwhinnery** [comment]
+1

**Comment by devinrader** [comment]
Thanks for the suggestion @bslatner.  I took a look at this today and the problem with using context.Request.Unvalidated is that it appears to only exist in .NET 4.5 and newer.  The MVC helper library is currently built using .NET 3.5 and I'd like to keep it that way if we can.

However, I agree that it would be nice to change the current behavior, so I took a shot at solving the problem via reflection:

https://github.com/twilio/twilio-csharp/tree/NonvalidatedForms

Not the most ideal to have to drop into reflection for this, but I could not find a different way.  Let me know what you think.

**Comment by MSDP** [comment]
I would DEFINITELY like to see the library updated to the latest MVC, or a
fork be created that is updated to the latest.



*Adam Reed*
*(P) 716 478 3509*
*(C) 716 406 7333*
*Chief Technical Officer*
*Spire Recovery Solutions, LLC*
*Tier One Asset Management Group, LLC *


*Market Street Debt Partners, LLC.*

**Comment by dsghi** [comment]
I'm with @MSDP here...

**Comment by devinrader** [comment]
@dsghi, @MSDP I'm happy to discuss if we should be taking dependencies on different framework versions, but lets start a new thread for that and keep this one limited to the original issue.  Thanks!

**Comment by bslatner** [comment]
It does seem excessive to have to use reflection for something so simple. I'm fairly happy with my solution that just duplicates the classes from the SDK and modifies them.

I haven't got the time right this second, but I'm curious if the MVC framework exposes a method that honors the [ValidateInput] attribute that could be leveraged.

**Comment by jingming** [comment]
`Twilio.Mvc` has been removed from this library and moved to https://www.nuget.org/packages/Twilio.AspNet.Mvc. Please email help@twilio.com if you continue to see issues there.
