### ISSUE TITLE
Filter subaccounts by status

### ISSUE THREAD

**Issue by menocomp** [twilio/twilio-csharp#173]
In the Rest implementation there is an option to request list of accounts by a status as following:
https://api.twilio.com/2010-04-01/Accounts?Status=closed
And as per Twilio documentation (in C#) it should be something like this:
var twilio = new TwilioRestClient(AccountSid, AuthToken);
var accounts = twilio.ListSubAccounts(null, "closed", null, null);

While in this SDK there is no way to call this method 'ListSubAccounts' and specify 'status' parameter.
Is there something missing here?

**Comment by skimbrel** [comment]
Yep, looks like we're missing that filter. @devinrader do you have a minute to add that?

**Comment by devinrader** [comment]
@skimbrel, yup, already have a prototype to test

**Comment by jingming** [comment]
This has been added in version `5.0.0`
