### ISSUE TITLE
Monitor.EventList doesn't seem to work when date range option set (C#)

### ISSUE THREAD

**Issue by abhhart** [twilio/twilio-csharp#174]
The sample C# code describing how to use the EventList with a date range filter throws a null reference exception on the "foreach"statment.   Commenting out the two lines that set StartDate and EndDate enable the sample to get past the foreach, but e.Description is still a null.  e.EventDate and e.EventType appear valid.

// Download the twilio-csharp library from twilio.com/docs/csharp/install
using System;
using Twilio.Monitor;
class Example
{
  static void Main(string[] args)
  {
    // Find your Account Sid and Auth Token at twilio.com/user/account
    string AccountSid = "ACd21740e37b3651c4a53434ebc542e869";
    string AuthToken = "{{ auth_token }}";
    var monitor = new MonitorClient(AccountSid, AuthToken);
    var options = new EventListRequest();
    options.StartDate = new DateTime(2015, 3, 1);
    options.EndDate = new DateTime(2015, 4, 1);
    var events = monitor.ListEvents(options);
    foreach (var e in events.Events)
    {
      Console.WriteLine(e.Description);
    }
  }
}

**Comment by mplacona** [comment]
Your code is right, but you get this error because there aren't any Events to be returned, and you're trying to loop through them.

Change your loop to the following and it will stop error'ing when there aren't any events.

```
if (events.Events == null) return;
foreach (var e in events.Events)
{
    Console.WriteLine(e.Description);
}
```

Hope this helps you.
