### ISSUE TITLE
The Twilio Nuget Package needs to be signed

### ISSUE THREAD

**Issue by keiichi-morisato** [twilio/twilio-csharp#176]
The Twilio nuget library assembly must be signed and have a strong-name assembly in order to allow its use in codebase that has signed components.
Our environment has signed assemblies and we cannot import your nuget package since your assembly is not signed.

Before someone suggests that we disable in our systems, we need COM Interop which requires strong named assemblies.

Thank you very much.

https://msdn.microsoft.com/en-us/library/xc31ft41(v=vs.110).aspx

**Comment by devinrader** [comment]
See this issue for why we don't have a signed version:  

https://github.com/twilio/twilio-csharp/issues/79

**Comment by Ultimacho** [comment]
RestSharp goes with signed libraries support since 24 Mar 2015. So why don't you take it and release a strongly-named Twilio assembly?
