### ISSUE TITLE
CSharp Helper "TypeLoadException"

### ISSUE THREAD

**Issue by FLSkyhopper** [twilio/twilio-csharp#183]
Hey guys. 
I cannot get the Twilio CSharp Helper to work. 
I followed the instructions of:
https://github.com/twilio/twilio-csharp 
Even if I try to load the prerelease (which is supposed to get rid of the RestSharp dependencies, right?) I still get the Err (see attached screenshot) when trying to use the TwilioRestClient. 
The packages are installed properly in the project.

I already tried to remove previous versions from my Nuget packages and cleared the the nuget cache.I’m running NuGet  2.8.60318.667 in Visual Studio 2012.

Here’s the log of the installation:
PM> Install-Package Twilio -prerelease -ProjectName FleuropReportsTester -Source nuget.org 
Attempting to resolve dependency 'RestSharp (≥ 105.0.1)'.
Installing 'RestSharp 105.0.1'.
Successfully installed 'RestSharp 105.0.1'.
Installing 'Twilio 4.0.5'.
Successfully installed 'Twilio 4.0.5'.
Adding 'RestSharp 105.0.1' to FleuropReportsTester.
Successfully added 'RestSharp 105.0.1' to FleuropReportsTester.
Adding 'Twilio 4.0.5' to FleuropReportsTester.
Successfully added 'Twilio 4.0.5' to FleuropReportsTester.

Any hints on how to resolve this? 
Best regards
Martin

![exception](https://cloud.githubusercontent.com/assets/14051823/9575290/c9059604-4fce-11e5-90ca-93d4dade1bde.png)

**Comment by mplacona** [comment]
Hey Martyn, I think it would be worth trying to update Restsharp. Try running: Install-Package RestSharp to get version 105.2.3 and it should solve your problem.

Have a look at my anwser [here](http://stackoverflow.com/questions/32067529/twilio-restsharp-dependency) and the update I added to it.

Let me know if this helps you.
