### ISSUE TITLE
UAP compatibility

### ISSUE THREAD

**Issue by paalders** [twilio/twilio-csharp#184]
It would be great if I could use the framework with UAP and also on the different frameworks. Planned implementing a windows IoT application with Twilio.

```
Twilio 4.1.0 is not compatible with UAP,Version=v10.0 (win10-arm).
Twilio 4.1.0 is not compatible with UAP,Version=v10.0 (win10-x86).
Twilio 4.1.0 is not compatible with UAP,Version=v10.0 (win10-x64).
```

**Comment by bbougot** [comment]
Same thing here!

**Comment by dsghi** [comment]
I don't think there's an issue with this not being UAP compatible. Calling Twilio services directly from IoT or mobile apps isn't wise architecture, mainly it's not scalable. You should offload that kind of work to backend services, for example we do it with Azure API apps or Azure WebApps/WebJobs. Queuing a message to be sent is much more reliable and scalable and decouples the app from the actual delivery of messages.

**Comment by jingming** [comment]
We have released an updated version of the library. Please give that try and let us know if you continue to see issues.
