### ISSUE TITLE
Twilio Security Certificate

### ISSUE THREAD

**Issue by AmitaKhatri** [twilio/twilio-csharp#189]
Hi,
Twilio is going to update its security certificate and has provided a test domain at https://api.twilio.com:8443. I am using your library for communicating with Twilio so I am not providing the API URL from my application. How can I make sure my application behaves as expected after the certificate change? How can I override the base URL of your dll to test it in our staging environment?

**Comment by carlosdp** [comment]
Hey Amita, you should be able to specify the baseUrl when initializing a TwilioRestClient:

```csharp
TwilioRestClient client = new TwilioRestClient(accountSid, authToken, accountSid, "2010-04-01", "https://api.twilio.com:8443");
```

Sorry that isn't easier! We'll improve that in the near future. Let me know if that works.

**Comment by AmitaKhatri** [comment]
Thanks @carlosdp !!

But I can find only 2 overloads of TwilioRestClient. 
1. TwilioRestClient(accountSid, authToken) and
2. TwilioRestClient(accountSid, authToken, accountSid)

There is no method with version or url as parameters.

**Comment by TimothyG** [comment]
Having the same issue. Not seeing a constructor that accepts 5 parameters.

**Comment by cmsanders3** [comment]
me too

**Comment by carlosdp** [comment]
Yea you're right, I read it wrong, it's the base class that has the overload. I'll add the overload in and close this issue once that's done.
