### ISSUE TITLE
Feature Request: Data as property on TwiMLResult

### ISSUE THREAD

**Issue by acamino** [twilio/twilio-csharp#194]
Hi folks,

First, let me provide some **context**, let's say I wrote an _action method_ that generates a `TwiMLResult` this this one:

```xml
<Response>
    <Message>Hello TwiML</Message>
</Response>
```

Then I write a test that makes sure the response is generated as expected.

```csharp
[Test]
public void MessageShouldRenderAValidResponse()
{
    var controller = new BrokerController();
    var result = (TwiMLResult) controller.Send();
    // Back magic here to get access to `result.data`
    data = GetInstanceField(typeof (TwiMLResult), result, "data") as XDocument;
    Assert.That(data.XPathSelectElement("Response/Message").Value, Is.EqualTo("Hello Twilio"));
}
```

As you can see _black magic_ in this example is pretty much using reflection to get access to the private instance field `result.data`.

```csharp
private static object GetInstanceField(IReflect type, object instance, string fieldName)
{
    const BindingFlags bindFlags = BindingFlags.Instance | BindingFlags.NonPublic;
    var field = type.GetField(fieldName, bindFlags);
    return field.GetValue(instance);
}
```

This is just something to bear in mind, whenever I use something like [`JsonResult`](https://aspnetwebstack.codeplex.com/SourceControl/latest#src/System.Web.Mvc/JsonResult.cs) I can use `Data` property for free (_Mostly used for testing purposes_).

### Feature Request
I'd like to have `data` or `Data` as a public property on [`TwiMLResult`](https://github.com/twilio/twilio-csharp/blob/bd3319d83eb7187cf6c372a3805213d2ec20add2/src/Twilio.Mvc/TwiMLResult.cs#L14), it will help me riding of some of the complexity related to testing a Twilio application.

What do you think guys, does this _feature request_ make sense for you? If so, I'd love to contribute.

**Comment by carlosdp** [comment]
It should probably be easier to access `data`. However, it does seem weird to test against the TwimlResult object. I would think you would actually want to test against the rendered view. Otherwise, you aren't really testing that the correct Twiml is being rendered.

**Comment by acamino** [comment]
@carlosdp thanks for the quick response, really appreciate it.

TL;TR;

I'm not sure why I should test the rendered view _which leads us to a more complex test_, I'll write an example about this reasoning in a the next paragraph.

As a continuation of the previous example, let's say this is the controller.

```csharp
public class Broker : TwilioController
{
    public ActionResult Message()
    {
        var result = new TwilioResponse();
        result.Message("Hello TwiML");
        return TwiML(result);
    }
}
```

According to [this](https://github.com/twilio/twilio-csharp/blob/bd3319d83eb7187cf6c372a3805213d2ec20add2/src/Twilio.Mvc/TwiMLResult.cs#L39) the data added to the response is the _content type_, but `data` itself remains immutable, which is good.

The closest thing that I can do to test the rendered view is play with `controller.ExecuteResult`:

```csharp
// The dependency in this test is Moq

[Test]
public void MessageShouldRenderAValidResponse()
{
    // Setup to read the response.
    var rawData = new StringBuilder();
    var mockResponse = new Mock<HttpResponseBase>();
    mockResponse.Setup(s => s.Write(It.IsAny<string>())).Callback<string>(c => Result.Append(c));
    mockResponse.Setup(s => s.Output).Returns(new StringWriter(rawData));

    var mockControllerContext = new Mock<ControllerContext>();
    var mockControllerContext.Setup(x => x.HttpContext.Response).Returns(mockResponse.Object);

    var controller = new BrokerController();
    var result = controller.Send(); // This creates an ActionResult, right?
    
    result.ExecuteResult(MockControllerContext.Object);

    // Ufff... finally getting the actual data.
    var data = rawData as XDocument;

    Assert.That(data.XPathSelectElement("Response/Message").Value, Is.EqualTo("Hello Twilio"));
}
```

As you can see, this test (_probably is not the best possible approach_) is more complex than the one shown in the previous example.

**Additional points to support testing using `data` or the theoretical `Data` directly:**

* In [`TwiMLResult`](https://github.com/twilio/twilio-csharp/blob/bd3319d83eb7187cf6c372a3805213d2ec20add2/src/Twilio.Mvc/TwiMLResult.cs) definition the constructors set the value of `data` as a `XDocument`.
* [`TwiML`](https://github.com/twilio/twilio-csharp/blob/bd3319d83eb7187cf6c372a3805213d2ec20add2/src/Twilio.Mvc/TwilioController.cs#L19) is just a thin wrapper around the instantiation of a `TwiMLResult`.

_I'm not sure how to write a test which renders the view content, if you can provide me any clue about how to do it that would be awesome._

I'd love to hear you opinions on this, thanks!

**Comment by acamino** [comment]
This one is cool 864adcf. 😉
