### ISSUE TITLE
Wrap optional params in a value exists test before adding params

### ISSUE THREAD

**Issue by devinrader** [twilio/twilio-csharp#198]
Probably want to check that [these](https://github.com/twilio/twilio-csharp/blob/edge-release/src/Twilio.IpMessaging/Services.cs#L104-L108) (and other optional values) actually have a value before adding them as parameters to the request, otherwise we might be unknowingly setting values to "empty" on Twilios side

**Comment by jingming** [comment]
All params should be checked in the updated library.
