### ISSUE TITLE
Async library update?

### ISSUE THREAD

**Issue by dprothero** [twilio/twilio-csharp#221]
#164 and #127 both have been closed, but it appears the latest version of the library still is using RestSharp and does not have TPL (async/await) friendly methods.

Would the team be interested in a PR that has a separate extension methods class that wraps the RestSharp API calls with TPL friendly Async versions? Would there even be anything to gain by that? I'm not familiar with the internals of RestSharp.

The general approach for that is outlined here: http://stackoverflow.com/questions/11879967/best-way-to-convert-callback-based-async-method-to-awaitable-task

**Comment by carlosdp** [comment]
hey @dprothero, I'm actually working on our next-generation C# library and it will be a PCL that is TPL friendly. I think it's best to just leave this functionality for that next version. Thanks!

**Comment by dprothero** [comment]
Sounds good, thanks Carlos!
