### ISSUE TITLE
Wrong parameter name in SendMessage async method

### ISSUE THREAD

**Issue by dannsam** [twilio/twilio-csharp#229]
https://github.com/twilio/twilio-csharp/blob/master/src/Twilio.Api.Silverlight/Messages.Async.cs#L307
line:

```
if (applicationSid.HasValue()) request.AddParameter("ApplicationSid", statusCallback);

```

should be:

```
if (applicationSid.HasValue()) request.AddParameter("ApplicationSid", applicationSid);
```

Please have a look at the PR https://github.com/dannsam/twilio-csharp/pull/1

**Comment by jingming** [comment]
This has been addressed in the latest version of the library.
