### ISSUE TITLE
Error code missing when sending SMS to blacklisted numbers.

### ISSUE THREAD

**Issue by palmsey** [twilio/twilio-csharp#231]
`twilio.SendMessage` is returning an empty object (no error code, all strings empty, all dates equal `DateTime.MinValue`) when I attempt to send a message to a blacklisted number. I found out the number was blacklisted by sending a POST manually to `/Messages`, which provided this response:

```
<?xml version='1.0' encoding='UTF-8'?>
<TwilioResponse>
    <RestException>
        <Code>21610</Code>
        <Message>The message From/To pair violates a blacklist rule.</Message>
        <MoreInfo>https://www.twilio.com/docs/errors/21610</MoreInfo>
        <Status>400</Status>
    </RestException>
</TwilioResponse>
```

**Version:** 4.7.0
**API Subdomain (api/taskrouter/ip_messaging):** SMS

### Code Snippet
```c#
var twilioResponse = twilio.SendMessage(from, to, body, statusCallbackUrl);
```

### Exception / Log
No exception, unfortunately.

### Steps to Reproduce
1. Attempt to send an SMS message to a blacklisted number.

**Comment by devinrader** [comment]
This is expected.  The library handles protocol exceptions and then exposes those through the RestException property that should exist on your `twilioResponse` object.  In your code you can check that property and handle accordingly:

    var twilioResponse = twilio.SendMessage(from, to, body, statusCallbackUrl);
    if (twilioResponse.RestException != null) {
        //handle error returned from Twilio's API
    }

Hope that helps.

**Comment by palmsey** [comment]
Very helpful, thanks!
