### ISSUE TITLE
Calling The TwilioApi using the client's ListRecordings results in a stackoveflow

### ISSUE THREAD

**Issue by mattlacrosse** [twilio/twilio-csharp#233]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

**Version:**
**API Subdomain (api/taskrouter/ip_messaging):**

### Code Snippet
```c#
# paste code here
```
          var account = _client.GetAccount(AccountSid);
            var token = account.AuthToken;
            _subclient = new TwilioRestClient(AccountSid, token);

            try
            {
                var recordings = _subclient.ListRecordings();
                return Ok(recordings);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }

            return NotFound();

### Exception / Log
```
An unhandled exception of type 'System.StackOverflowException' occurred in Twilio.Api.dll
<place exception / log here>
```

### Steps to Reproduce
1. Using Visual Studio 2015 Create a new Web API project
2. Add the Twilio nuget packages
3. Try to call ListRecordings() as shown  above

### Feature Request
_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by mattlacrosse** [comment]
I added this method to my class as a work around

        private RecordingResult ListRecordings()
        {
            var request = new RestRequest();
            request.Resource = "Accounts/{AccountSid}/Recordings.json";

            return _subclient.Execute<RecordingResult>(request);
        }

**Comment by jingming** [comment]
@mattlacrosse thanks for pointing this out! pull request is here: https://github.com/twilio/twilio-csharp/pull/234.

We'll try to get this out ASAP.
