### ISSUE TITLE
Issue in version of Twilio.Pricing in NuGet repository

### ISSUE THREAD

**Issue by EliuX** [twilio/twilio-csharp#235]
Attempting to execute the code snippet [get-messaging-country.cs](https://github.com/TwilioDevEd/api-snippets/blob/master/pricing/get-messaging-country/get-messaging-country.cs) in Visual Studio (Community Edition). 

When installing `Twilio.Pricing` the following dependencies was solved for the framework `net452`:
- RestSharp, version 105.2.3
- Twilio, version 4.7.1
- Twilio.Lookups, version 1.1.0
- Twilio.Pricing, version 1.1.0

This code has 2 concrete problems:
1. The method `GetMessagingCountry` is not available for the instance of `PricingClient`.
2. The type `InboundSmsPrice` is not available.

![virtualbox_ie10 - win7_06_04_2016_10_30_04](https://cloud.githubusercontent.com/assets/6514740/14325082/e95da166-fc27-11e5-99bc-1947c731fe64.png)

Later on I checked if the method `GetMessagingCountry` actually exist in the current [codebase](https://github.com/twilio/twilio-csharp/blob/9b10460f62e7ab0ad18bfd67b7fd97f8f6d68a93/src/Twilio.Pricing/Messages.cs). Seems like the aforementioned method is available there.

What do you think about updating the package in NuGet to reflect the latest changes you made?

**Comment by jingming** [comment]
This has been addressed in the latest version of the library.
