### ISSUE TITLE
NumImages is Zero When Message Contains Images

### ISSUE THREAD

**Issue by RealDotNetDave** [twilio/twilio-csharp#236]
When an image is sent via a message, the NumImages property in the message object is always zero. The data is coming through in the http response, but not filled in the Twilio rest library for .NET.

Request:
GET https://api.twilio.com/2010-04-01/Accounts/ACe24fc8b882af5006ff8f29f71e9eaac4/Messages.json?To=%2B18583670921&DateSent=2016-04-07 HTTP/1.1
Authorization: Basic 
Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml
Accept-charset: utf-8
User-Agent: twilio-csharp/3.4.1.0 (.NET 4.0.30319.42000)
Host: api.twilio.com
Accept-Encoding: gzip, deflate

Response:
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since
Access-Control-Allow-Methods: GET, POST, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Apr 2016 17:42:28 GMT
Strict-Transport-Security: max-age=15768000
Twilio-Request-Duration: 0.059
Twilio-Request-Id: RQ98e266771b0641419b63c8de576d1dfd
X-Powered-By: AT-5000
X-Shenanigans: none
Content-Length: 1197
Connection: keep-alive

{"first_page_uri": "/2010-04-01/Accounts/ACe24fc8b882af5006ff8f29f71e9eaac4/Messages.json?To=%2B18583670921&DateSent=2016-04-07&PageSize=50&Page=0", "end": 0, "previous_page_uri": null, "messages": [{"sid": "MM86380fa13a7bd6d3404f3d82ea0f8038", "date_created": "Thu, 07 Apr 2016 17:32:24 +0000", "date_updated": "Thu, 07 Apr 2016 17:32:24 +0000", "date_sent": "Thu, 07 Apr 2016 17:32:24 +0000", "account_sid": "ACe24fc8b882af5006ff8f29f71e9eaac4", "to": "+18583670921", "from": "+18582298430", "messaging_service_sid": null, "body": "", "status": "received", "num_segments": "1", "num_media": "1", "direction": "inbound", "api_version": "2010-04-01", "price": "-0.01000", "price_unit": "USD", "error_code": null, "error_message": null, "uri": "/2010-04-01/Accounts/ACe24fc8b882af5006ff8f29f71e9eaac4/Messages/MM86380fa13a7bd6d3404f3d82ea0f8038.json", "subresource_uris": {"media": "/2010-04-01/Accounts/ACe24fc8b882af5006ff8f29f71e9eaac4/Messages/MM86380fa13a7bd6d3404f3d82ea0f8038/Media.json"}}], "uri": "/2010-04-01/Accounts/ACe24fc8b882af5006ff8f29f71e9eaac4/Messages.json?To=%2B18583670921&DateSent=2016-04-07&PageSize=50&Page=0", "page_size": 50, "start": 0, "next_page_uri": null, "page": 0}

**Comment by trupsis** [comment]
I hit this issue as well. I spent some time calling the API directly and noticed that if you delete media then num_media is not updated. The SDK still should be fixed to reflect the value returned from the API, but I guess it can't be relied upon even if it is.

**Comment by jingming** [comment]
The SDK has been updated to display the property. However, if you continue to see issues with the API results, please email any concerns to help@twilio.com
