### ISSUE TITLE
Error caught when published on the IIS 'Could not load file or assembly 'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies'

### ISSUE THREAD

**Issue by eriansuwandi** [twilio/twilio-csharp#247]
Hi,
I have issue only when the project published on the IIS. But there's no error when I try running on my local. Is there any that I've missed?

Error message: _Could not load file or assembly 'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified_

I use this SDK from nuget package:
-  **package id="RestSharp" version="105.2.2" targetFramework="net45"** 
-  **package id="Twilio" version="4.7.2" targetFramework="net45"** 

Thanks in advance

**Comment by hsrobflavorus** [comment]
You probably have an older version or something registered in your GAC or somewhere else. This might help:

`
<runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
            <dependentAssembly>
                <assemblyIdentity name="RestSharp" publicKeyToken="null" />
                <bindingRedirect oldVersion="100.0.0-200.0.0" newVersion="105.2.2" />
            </dependentAssembly>            
        </assemblyBinding>
    </runtime>
`

**Comment by lion444** [comment]
me too. i am about to give up on twilio..too much effort getting it to run.

**Comment by lion444** [comment]
I just uninstalled all twilio packages and ran 'Install-Package Twilio' and all is well. I guess it is because we installed twilio.mvc. dont need this.

**Comment by jingming** [comment]
Resolved.
