### ISSUE TITLE
Key Resource doesn't have a ListKeys method

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-csharp#249]
_Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!_

**Version:**
**API Subdomain (api):** Rest API
### Code Snippet

``` c#
using System;
using Twilio;
class Example
{
  static void Main(string[] args)
  {
    // Find your Account Sid and Auth Token at twilio.com/user/account
    string AccountSid = "SIDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    string AuthToken = "SIDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    var twilio = new TwilioRestClient(AccountSid, AuthToken);

    var keys = twilio.ListKeys();

    foreach (var key in keys.Keys)
    {
      Console.WriteLine(key.FriendlyName);
    }
  }
}
```
### Exception / Log

```
Type `Twilio.TwilioRestClient' does not contain a definition for `ListKeys' and no extension method `ListKeys' of type `Twilio.TwilioRestClient' could be found. Are you missing an assembly reference?
```
### Steps to Reproduce
1. Run the snippet above.
### Feature Request

The ListKeys() method should be defined here https://github.com/twilio/twilio-csharp/blob/master/src/Twilio.Api/Keys.cs

The code snippet is taken from the Twilio Rest API docs. Is there another way to list key resources?

**Comment by jingming** [comment]
This has been addressed with the latest release.
