### ISSUE TITLE
TaskRouterClient.ListEvents failing with resource not found.

### ISSUE THREAD

**Issue by mmcfadye** [twilio/twilio-csharp#250]
_Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!_

**Version:** 2.3.0
**API Subdomain (api/taskrouter/ip_messaging):**taskrouter events
### Code Snippet

``` c#
            var client = new TaskRouterClient(AccountSid, AuthToken);

            EventListRequest request = new EventListRequest();
            request.StartDate = startDate;
            request.EndDate = endDate;
            request.EventType = eventType;
            var eventResult = client.ListEvents(WorkspaceSid, request);
            if(eventResult.RestException == null)
            {
                return eventResult.Events;
            }
            else
            {
                throw new Exception(eventResult.RestException.Message);
            }
```
### Exception / Log

```
20404 rest exception on calling list events
```
### Steps to Reproduce
1. Any event calls fail with the 404 error
2. Looks like the resource address in Twilio.TaskRouter/Events.cs are using a different url format than other taskrouter api calls
3. I created a subclass of TaskRouterClient that is working:

``` c#
        public override EventResult ListEvents(string workspaceSid, EventListRequest options)
        {
            Require.Argument("WorkspaceSid", workspaceSid);


            var request = new RestRequest();
            request.Resource = "Workspaces/{WorkspaceSid}/Events";

            request.AddUrlSegment("WorkspaceSid", workspaceSid);


            AddEventListOptions(options, request);


            return Execute<EventResult>(request);
        }
```
### Feature Request

_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by jwitz10** [comment]
You are totally correct on this. I've added on a fix to https://github.com/twilio/twilio-csharp/pull/244 that includes this.

**Comment by jingming** [comment]
This should be addressed with the latest version of the library.
