### ISSUE TITLE
Twilio 4.7.2 dependency on RestSharp 105.2.3 error.

### ISSUE THREAD

**Issue by mitchvh** [twilio/twilio-csharp#257]
I have been trying to use Twilio in a Azure Function App to send an SMS on an Event Hub Message from Streaming Analytics. I almost gave up, since nothing seemed to fix the dependency error, no matter how I changed project.json. I tried, essentially the same code, in Visual Studio and noticed that the NuGet Twilio include automatically included RestSharp 105.2.2 - not the 105.2.3 that Twilio said it was wanting (seems like a NuGet package config error, to me) - error message:

_Exception while executing function: Functions.EHTriggerCS mscorlib: Exception has been thrown by the target of an invocation. Twilio.Api: Could not load file or assembly 'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified._

As a final act of desperation, I deleted the function and recreated it with the RestSharp 105.2.3 dependency ahead of the Twilio 4.7.2 dependency in the project.json and it worked. 

I just thought I would share incase others run into the same issue, I certainly wasted enough time on this today for several people.

**Comment by mitchvh** [comment]
Very strange behaviour - it will sometimes compile and work fine, while other times the function doesn't compile with the following error:

_Error CS0246: The type or namespace name 'TwilioRestClient' could not be found (are you missing a using directive or an assembly reference?)_

Not sure what the TwilioRestClient is - is this the replacement for RestSharp? If so, why does it sometime compile and work? Is TwilioRestClient available on NuGet, if so, which Twilio library do I include? Not sure if fixing the dependencies of 4.7.2 in Nuget will get rid of this error...

**Comment by mitchvh** [comment]
Oops, didn't mean to close this...

**Comment by mitchvh** [comment]
Very strange behaviour - it will sometimes compile and work fine, while other times the function doesn't compile with the following error:

Error CS0246: The type or namespace name 'TwilioRestClient' could not be found (are you missing a using directive or an assembly reference?)

Not sure what the TwilioRestClient is - is this the replacement for RestSharp? If so, why does it sometime compile and work? Is TwilioRestClient available on NuGet, if so, which Twilio library do I include? Not sure if fixing the dependencies of 4.7.2 in Nuget will get rid of this error...

**Comment by jingming** [comment]
This has been resolved with the latest release of the library.
