### ISSUE TITLE
Both dependencies (Microsoft.Net.Http & Microsoft.Bcl) do not support .NetCore...   

### ISSUE THREAD

**Issue by Kavik00** [twilio/twilio-csharp#259]
_Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!_

**Version:**
**API Subdomain (api/taskrouter/ip_messaging):**
### Code Snippet

``` c#
# paste code here
```
### Exception / Log

NU1002 The dependency Microsoft.Net.Http 2.2.29 does not support framework .NETStandard,Version=v1.6.

NU1002 The dependency Microsoft.Bcl 1.1.10 does not support framework .NETStandard,Version=v1.6.

<place exception / log here>

```

### Steps to Reproduce
1.Add Twilio 5.0.0-rc4 to .Net Core Project
2.
3.


### Feature Request
_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

```

**Comment by devinrader** [comment]
@Kavik00 can you provide some more detail on what you are seeing?  I' running VS2015 with the latest updates and am not able to reproduce your issue.

**Comment by Kavik00** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/9566155/16747210/507ef554-477b-11e6-8c63-5980377f1df4.jpg)

Simply start a .NET Core project and attempt to add the twilio 5.0.0-rc4 NuGet package

**Comment by devinrader** [comment]
OK, I was able to reproduce with a .NET Console app.   Seems to work different with a web app.

**Comment by jingming** [comment]
These two dependencies have been removed from the latest version of the library.
