### ISSUE TITLE
Non-autogenerated helper libraries not included in next-gen

### ISSUE THREAD

**Issue by dprothero** [twilio/twilio-csharp#261]
**Version:** 5.0.0-rc5

The following libraries are missing from the next-gen branch:

Twilio.Auth
Twilio.Client
Twilio.IpMessaging
Twilio.Lookups
Twilio.Monitor
Twilio.Mvc
Twilio.Pricing
Twilio.TaskRouter
Twilio.Trunking
Twilio.TwiML
Twilio.WebMatrix
Twilio.WinRT

It's possible not all are needed, but I know for certain Twilio.Auth, Twilio.Mvc, and Twilio.TwiML will be needed.

**Comment by jingming** [comment]
`Twilio.Auth`, `Twilio.Mvc`, `Twilio.TwiML` will be picked up when we merge this into master. The subdomain resources are included under `Twilio`.

**Comment by carlosdp** [comment]
Well Twilio.Auth and Twilio.TwiML will be merged in, but Twilio.Mvc will move to a new repository as it is a little to high-level for the API team to manage and will be spun out to different management.
