### ISSUE TITLE
TaskRouter Worker list APIs are missing

### ISSUE THREAD

**Issue by amattie** [twilio/twilio-csharp#266]
I see a way in the lib to get an individual TaskRouter worker, but not a way to list the workers (per https://www.twilio.com/docs/api/taskrouter/workers#action-list). I suspect it was an oversight. Can that be added?

**Comment by jwitz10** [comment]
Hmm, interesting. What version are you currently using?

**Comment by amattie** [comment]
Sorry, using 5.0.0-rc4. I'd expect to see a "WorkersResource.cs" in https://github.com/twilio/twilio-csharp/tree/next-gen/Twilio/Resources/Taskrouter/V1/Workspace if it were actually implemented.

**Comment by jwitz10** [comment]
In 5.0+, the list versions of these resources will live within each singular resource.

For example, within WorkerResource.cs (singular), you'll want to utilize the WorkerReader from the Read function:

https://github.com/twilio/twilio-csharp/blob/next-gen/Twilio/Resources/Taskrouter/V1/Workspace/WorkerResource.cs#L23

**Comment by amattie** [comment]
Sorry, you're right. I just wasn't used to the API and was guessing in lieu of docs for it. Thanks for taking the time to respond.
