### ISSUE TITLE
API feedback: Use DateTimeOffset or NodaTime.Instant instead of DateTime

### ISSUE THREAD

**Issue by amattie** [twilio/twilio-csharp#267]
**5.0.0-rc4**
**api/taskrouter/v1/workspace**

It'd be nice if DateTimeOffset were used everywhere instead of DateTime for the sake of clarity. Better yet, perhaps considering referencing NodaTime and using an Instant (which works out of the box with Newtonsoft.Json).

Additional reading / reference: http://blog.nodatime.org/2011/08/what-wrong-with-datetime-anyway.html

**Comment by jingming** [comment]
We chose to use the default `DateTime` since it adds less dependencies to the library.

**Comment by amattie** [comment]
`DateTimeOffset` would be a better choice if you don't want to add the extra dependency. The problem with `DateTime` is that it's not clear what the timezone is. I presume it's UTC, but the `Kind` property comes through as "Unknown" and so I'm left to basically just assume. Even if you really wanted to stick with `DateTime` for some reason, it'd be nice if you also set `Kind` to "UTC".
