### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by tig4647** [twilio/twilio-csharp#269]
Hopefully I am not missing something obvious, however I cannot see with the webhook how to handle picture messages. There is no indicator nor class in the SMSReceieve that has this. Any help is appreciated.

**Comment by mplacona** [comment]
Hey Jason, a "picture message" is just an SMS (or MMS to be more precise), therefore all you need to do is handle it the way you would handle a regular SMS message.

Have a look at the bottom of [this page](https://www.twilio.com/docs/quickstart/csharp/sms/sending-via-rest) and you will see an example of how to send an MMS message in .NET, and [this page](https://www.twilio.com/docs/api/rest/sending-messages) to see information about `MediaUrl `, which is where the image will come attached on the request.

Hope this helps.
