### ISSUE TITLE
RestException does not have a valid ISerializable constructor.

### ISSUE THREAD

**Issue by akhansari** [twilio/twilio-csharp#272]
**Version: 5.0.0-rc4**
**API: Twilio.Creators.Api.V2010.Account.Sms.SmsMessageCreator**
#### Exception

ISerializable type 'Twilio.Exceptions.RestException' does not have a valid constructor. To correctly implement ISerializable a constructor that takes SerializationInfo and StreamingContext parameters should be present. Path '', line 1, position 171.
#### Steps to Reproduce

Calling SmsMessageCreator.Execute fail if there is a Rest exception.

**Comment by justinkitagawa** [comment]
Thanks for filing this @akhansari.  We will take a look and this and get back to you.

**Comment by carlosdp** [comment]
@akhansari can you provide the relevant snippet of your code please?

**Comment by amattie** [comment]
I've seen this issue occur as well. I believe it was happening when my auth credentials were incorrect (or at least didn't have permissions to access the resource I was trying to access).

**Comment by akhansari** [comment]
@justinkitagawa I took the example which is at the end of this page :
https://www.twilio.com/docs/libraries/csharp

**Comment by carlosdp** [comment]
@akhansari is this a warning or an error?

The exceptions do not implement ISerializable because this is a PCL library and Serializable is not in the PCL set. I can't seem to replicate any exception that complains about it though using that snippet or any of our smoke test code?

**Comment by chrislarabell** [comment]
I am getting the same error.  Maybe because your base class inherits [`System.Exception`](http://referencesource.microsoft.com/#mscorlib/system/exception.cs,f092fb2b893a0162) and that does implement `ISerializable?`

**Comment by lakeba** [comment]
I have seen this issue occur as well using the RC8, any update?

**Comment by lakeba** [comment]
The Error is still there even the latest RC.

**Comment by dougblack** [comment]
@lakeba Have you tried this once more with the latest RC? I am having difficulty reproducing.

**Comment by jingming** [comment]
Closing due to lack of response. Feel free to open if issue is still happening.

**Comment by demoran23** [comment]
I am seeing this issue.  From my own log of the exception:

> ISerializable type 'Twilio.Exceptions.RestException' does not have a valid constructor. To correctly implement ISerializable a constructor that takes SerializationInfo and StreamingContext parameters should be present. Path '', line 1, position 159.

The timestamp for this is 2017-04-17T02:41:14.376Z on my own side.  There is no log entry on the Twilio side for this message (searched 10 min on either side).
