### ISSUE TITLE
Many (all?) updaters require all params to be set, or they throw an exception

### ISSUE THREAD

**Issue by amattie** [twilio/twilio-csharp#273]
**5.0.0-rc4:**
**/Updaters/Taskrouter/V1/Workspace/WorkerUpdater:**

```c#
var updater = new WorkerUpdater("123", "456");
updater.setActivitySid(offlineActivitySid);
updater.Execute(new TwilioRestClient("", ""));
```

This causes the Twilio service to error and an exception to be thrown. The reason is that the private `attributes` property is [null on class instantiation](https://github.com/twilio/twilio-csharp/blob/03a645802bfcd70fc957c66b38ce731d1d78030c/Twilio/Updaters/Taskrouter/V1/Workspace/WorkerUpdater.cs#L17), [`attributes` is thus `!= ""`] (https://github.com/twilio/twilio-csharp/blob/03a645802bfcd70fc957c66b38ce731d1d78030c/Twilio/Updaters/Taskrouter/V1/Workspace/WorkerUpdater.cs#L144), and Twilio doesn't like attributes being an empty param since it's not actual JSON.

The Twilio error message looks like this: `Attributes JSON [] not valid. Strict JSON format is required. Error was: [Unexpected token END OF FILE at position 0.] for worker ...`

The immediate workaround is to call `.setAttributes("")` on the updater so that the attributes aren't added to the request, although my realization here is that every `.set` method on every updater needs to be called with an empty string to prevent empty value updates. The fix is to check for `string.IsNullOrEmpty` rather than `""`, although that'd prevent any desired updates to null values / empty strings.

This feels like a rather large bug since it's spread across so many updaters and since misuse can accidentally wipe data within Twilio.

**Comment by ihumanable** [comment]
Thank you for your report, we will investigate and follow up shortly.

**Comment by ihumanable** [comment]
@amattie could you take a look at https://github.com/twilio/twilio-csharp/commit/9fa0b2706ea7ebbcc9870c32110a6724ef9534d4 I believe that fixes this issue, if you concur I will close.

**Comment by carlosdp** [comment]
I'm going to mark this as closed for now, feel free to comment again if it is not resolved @amattie

**Comment by amattie** [comment]
I left this commend on the changeset itself:

> This entire changeset puts the library in a much better place since it'll no longer accidentally overwrite data, but I still can't set values to empty. For example, if I had previously set fallbackAssignmentCallbackUrl using this SDK, I won't be able to unset it. It probably won't be noticed in most situations and for most uses (including us, for now), but as you get more and more users on this, it's bound to be noticed by someone.

>Again though, I think this changeset at least puts the SDK in a better place than it was.
