### ISSUE TITLE
Paging doesn't work in TaskRouter readers

### ISSUE THREAD

**Issue by amattie** [twilio/twilio-csharp#274]
**5.0.0-rc4:**
**API Subdomain (Readers/Taskrouter/V1):**

NextPage doesn't work in at least WorkerReader due to Domains.TASKROUTER not being included in the request [built in NextPage](https://github.com/twilio/twilio-csharp/blob/03a645802bfcd70fc957c66b38ce731d1d78030c/Twilio/Readers/Taskrouter/V1/Workspace/WorkerReader.cs#L161).

**Comment by justinkitagawa** [comment]
Thanks, @amattie.  We will take a look at this.

**Comment by carlosdp** [comment]
This was an error to do with query param handling in paging, fixed in 93d65b9

**Comment by amattie** [comment]
I don't think this fixes the issue. The TaskRouter domain needs to be specified in the place I referenced or else the api.twilio.com host will be hit instead of taskrouter.twilio.com
