### ISSUE TITLE
Paging broken due to ? in URL when it shouldn't be there

### ISSUE THREAD

**Issue by amattie** [twilio/twilio-csharp#275]
**5.0.0-rc4:**
(for TaskRouter, but appears to be a more generic issue)

In [Request.cs in ConstructURL](https://github.com/twilio/twilio-csharp/blob/03a645802bfcd70fc957c66b38ce731d1d78030c/Twilio/Http/Request.cs#L28), a `?` is unconditionally added to the end of the URL, even if there are no query params. This causes a problem with paging because the URIs returned from the Twilio API for paging already contain a `?` in them.

When the URL does have two `?`s in it, the Twilio API returns a message like this: `{"message": "Value 'WK079dfd4e20e1ab289d3c89e992129d61?' provided for AfterSid has an invalid format", "status": 400}`

**Comment by justinkitagawa** [comment]
@amattie thanks for the bug report.  We will look into this and keep you abreast of any fix.

**Comment by carlosdp** [comment]
Fixed in 93d65b9
