### ISSUE TITLE
Allow clientname without allowing incoming

### ISSUE THREAD

**Issue by waynebrantley** [twilio/twilio-csharp#278]
The only way to set the client name is to allow incoming calls.
I want the client name set so it shows in the logs and such, but do now want to allow incoming always.

Break this call up in this code.

https://github.com/twilio/twilio-csharp/blob/master/src/Twilio.Client.Capability/TwilioCapability.cs

I would submit a pull request, but there are 23 requests and none seem to be accepted??

**Comment by jingming** [comment]
Feel free to submit a PR against the latest version of the library.

**Comment by efossier** [comment]
@waynebrantley Just to clarify on the last point about submitting a pull request, we were doing a pretty bad job of triaging and reviewing pull requests prior to releasing the 5.x version of the library as we didnt have the bandwidth to add features to the 4.x library while also writing the 5.x one and so we were pretty unresponsive.

Now that 5.x is released we have cleaned up a lot of the out of date issues and prs and are now regularly checking on this repo for new issues and prs so your contributions will not be in vain!
