### ISSUE TITLE
support for framework .NETCoreApp,Version=v1.0.

### ISSUE THREAD

**Issue by himadrinath** [twilio/twilio-csharp#282]
When we can expect to see Twilio Client library for .NETCoreApp,Version=v1.0.

**Comment by waynebrantley** [comment]
Any update?

**Comment by ByronAP** [comment]
Knock knock anyone home... I think the demand for a core clr library is high enough to warrant priority.

**Comment by jayrulez** [comment]
Any word on this?

**Comment by adamreed90** [comment]
Update?

**Comment by Izzmo** [comment]
There is this PR: https://github.com/twilio/twilio-csharp/pull/301 .. probably just need to review and complete.

**Comment by jingming** [comment]
This is done!

**Comment by Izzmo** [comment]
Awesome work, thanks @jingming!

**Comment by himadrinath** [comment]
@jingming Twilio.TwiML support in .NETCoreApp
