### ISSUE TITLE
vNext of this api is creating portable class library - that is old way now!

### ISSUE THREAD

**Issue by waynebrantley** [twilio/twilio-csharp#287]
Vnext of this api is creating a pcl?
Should be creating a class library package and tie to .net standard.

http://damien.dennehy.me/blog/2016/01/15/class-library-packages-future-class-libraries/

Seems no feedback or any moderation of any issues on this repository.
This is 'open source' but it does not seem to be collaborative or anything.

@jingming Can you please advise?  You seem to be a commiting part of the team?

**Comment by dprothero** [comment]
@waynebrantley I can tell you this is definitely on the roadmap. It's uncertain whether it'll be part of the first GA release, however. I've [experimented with it](https://github.com/twilio/twilio-csharp/pull/301) and it does seem feasible, compiling great in Visual Studio 2015 U3. However, there are issues with the [Travis CI build](https://travis-ci.org/twilio/twilio-csharp/builds/184281700) as well as trying to [compile with the `dotnet` CLI](https://github.com/dotnet/cli/issues/5031).

**Comment by waynebrantley** [comment]
GREAT news @dprothero    
This is the first response of any issue posted by anyone that I have heard from twilio on this.  I hope this is a sign of things to come.   
Glad you guys are plugged into what is needed as I dont really want to fork and create my own.

**Comment by dprothero** [comment]
Reopening this issue until we complete this work.

**Comment by dprothero** [comment]
My experiment is complete (and successful):
https://github.com/twilio/twilio-csharp/pull/301

Will need to figure out where this fits in the dev team's schedule.

**Comment by waynebrantley** [comment]
I hope you know some special magic way to communicate with them!
Thanks for doing this!

**Comment by dprothero** [comment]
Yep, I work at Twilio, so they can't avoid me. 👍

**Comment by jingming** [comment]
This is fixed! 😄

**Comment by dprothero** [comment]
Version 5.0.0 of the library targets .NET Standard 1.4!
