### ISSUE TITLE
Error is not returned when sending message to blocked number

### ISSUE THREAD

**Issue by paritoshmmmec** [twilio/twilio-csharp#291]
Twilio does not return error if system send a message to blocked number. So if a number opt out from a communication , and if we trying to send a message, twilio blocks the message which is great , but does not return an error

**Twilio 4.7.2:**
**messaging**

### Steps to Reproduce
1. Send a message to number using SDK
2. Reply STOP 
3. Check the twilio logs , message cannot be sent as failed.
4. Check the status from the api. No errors included.

**Comment by jingming** [comment]
@paritoshmmmec please direct this question to help@twilio.com. They will happy to take care of you!
