### ISSUE TITLE
The "next-gen" version of the Twilio library not working in ASP.Net Web api

### ISSUE THREAD

**Issue by sunilkumarmandadi** [twilio/twilio-csharp#296]
**Version: 5.0**

### Code Snippet
using System;
using System.Threading.Tasks;
using Twilio;
using Twilio.Clients;
using Twilio.Creators.Api.V2010.Account;
using Twilio.Types;

namespace ConsoleApplication1
{
  class Program
  {
    static void Main(string[] args)
    {
      SendSms().Wait();
      Console.Write("Press any key to continue.");
      Console.ReadKey();
    }

    static async Task SendSms()
    {
      var accountSid = "AC74eb95e20c9debae358696905039c815"; // Your Account SID from twilio.com/console
      var authToken = "{{ auth_token }}";   // Your Auth Token from twilio.com/console

      TwilioClient.init(accountSid, authToken);
      var restClient = new TwilioRestClient(accountSid, authToken);

      var message = await
        new MessageCreator(
          accountSid,
          new PhoneNumber("+12345678901"),  // To number
          new PhoneNumber("+12345678901"),  // Twilio From number
          "Hello from C#"
        ).ExecuteAsync(restClient);

      Console.WriteLine(message.GetSid());
    }
  }
}
# paste code here
```

### Exception / Log
```
I have installed "Twilio -Pre" through Package Manager Console in Visual Studio. But i am not able to access Twilio.Creators.Api.V2010.Account namespace. So "MessageCreator" is giving the error.
```

### Steps to Reproduce
(I have taken all the code from https://www.twilio.com/docs/libraries/csharp )

1. Install "Twilio -Pre" through Package Manager Console in Visual Studio. 
2. Paste the above code. 
3. You will see the errors.

Please help me.

Thanks,
Sunil

**Comment by dprothero** [comment]
Thanks for the report. The latest version of the library has a new interface. The sample on the /docs website has been updated:
https://www.twilio.com/docs/libraries/csharp#installation-nextgen

Here's the code you need to run:

```c#
using System;
using System.Threading.Tasks;
using Twilio;
using Twilio.Rest.Api.V2010.Account;
using Twilio.Types;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            SendSms().Wait();
            Console.Write("Press any key to continue.");
            Console.ReadKey();
        }

        static async Task SendSms()
        {
            // Your Account SID from twilio.com/console
            var accountSid = "ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            // Your Auth Token from twilio.com/console
            var authToken = "auth_token";   

            TwilioClient.Init(accountSid, authToken);

            var message = await MessageResource.CreateAsync(
                to: new PhoneNumber("+12345678901"),
                from: new PhoneNumber("+12345678901"),
                body: "Hello from C#");

            Console.WriteLine(message.Sid);
        }
    }
}
```

**Comment by dprothero** [comment]
@sunilkumarmandadi please close this issue if this resolves the problem for you.

**Comment by rubit0** [comment]
Using above's code throws me a WebException with an "Bad Request" 400 Status Code. I am using a pretty bare bones Asp.Net Core 1.0 project on VS2015 with the latest Next-Gen Twilio release.
I have also checked the sid, token and phonenumber for mistakes.

`
    public class TwilioMessageSender : IMessageSender
    {
        private readonly string _accountSid;
        private readonly string _authToken;
        private readonly string _twilioSender;

        public TwilioMessageSender()
        {
            _accountSid = Startup.Configuration["Twillio:Sid"];
            _authToken = Startup.Configuration["Twillio:Token"];
            _twilioSender = Startup.Configuration["Twillio:Sender"];
        }

        public async Task SendMessageAsync(string number, string message)
        {
            TwilioClient.Init(_accountSid, _authToken);

            try
            {
                var messageTask = await MessageResource.CreateAsync(
                    to: new PhoneNumber(number),
                    from: new PhoneNumber(_twilioSender),
                    body: message);
            }
            catch (Exception ex)
            {
                throw;
            }
        }
    }
`

**Comment by dprothero** [comment]
@rubit0 The development team is going to be working on .Net Core support soon.

**Comment by rubit0** [comment]
@dprothero 
Great to know that, in the meanwhile I have rolled out my own manual requests to the REST service which is fine enough for me, since I just send SMS for authentication of new users.

**Comment by jingming** [comment]
The new library has been release with .Net Core support.
