### ISSUE TITLE
Twilio.Princing does not include Messages

### ISSUE THREAD

**Issue by acamino** [twilio/twilio-csharp#299]
**Version:**
Twilio Pricing v.1.1.0

Some clases like [Messages.cs](https://github.com/twilio/twilio-csharp/blob/7831a28014fe1d768c69295c7b8042ab48d7a0cb/src/Twilio.Pricing/Messages.cs) and [Messages.Async.cs](https://github.com/twilio/twilio-csharp/blob/7831a28014fe1d768c69295c7b8042ab48d7a0cb/src/Twilio.Pricing/Messages.Async.cs) are [not included for compilation](https://github.com/twilio/twilio-csharp/blob/ab0983ae00269746c5dbeb891955ae3edd83796d/src/Twilio.Pricing/Twilio.Pricing.csproj#L40-L56).

<img width="417" alt="twilio-pricing" src="https://cloud.githubusercontent.com/assets/957202/21105691/27e506ae-c059-11e6-8849-e73e4291c07c.png">

So that methods like `PricingClient#GetMessagingCountry` are not available.
I can submit a pull request with a patch for solving this issue - what do you think?

**Comment by acamino** [comment]
This issue seems to be partially described in #235.

**Comment by jingming** [comment]
This should be resolved in the latest release.
