### ISSUE TITLE
Need callback validation on various api methods.

### ISSUE THREAD

**Issue by niemyjski** [twilio/twilio-csharp#311]
I'm not a consumer if your api, but was diagnosing an issue with an user (via our exceptionless project).

You are calling the callback without checking to see if it's null all over your api (https://github.com/twilio/twilio-csharp/blob/ab0983ae00269746c5dbeb891955ae3edd83796d/src/Twilio.TaskRouter/Tasks.Async.cs#L154)

I'm logging this as it should be fixed :).

**Comment by jingming** [comment]
This is fixed in the latest release as it introduces a new paradigm.
