### ISSUE TITLE
Pricing API doesn't have support for Inbound / Outbound messages

### ISSUE THREAD

**Issue by armhil** [twilio/twilio-csharp#318]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

**Version:**
**API Subdomain (api/taskrouter/ip_messaging):**

### Code Snippet
```c#
# paste code here
```

### Exception / Log
```
<place exception / log here>
```

### Steps to Reproduce
1.
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by jingming** [comment]
This is added in the latest release of the library.
