### ISSUE TITLE
Twilio.TwiML support in .NETCoreApp

### ISSUE THREAD

**Issue by himadrinath** [twilio/twilio-csharp#329]
i can't find any TwiML support in asp.net core

**Comment by devinrader** [comment]
@himadrinath check out the `MessageResponse` and `VoiceResponse` classes under the `Twilio.Twiml` namespace.

**Comment by himadrinath** [comment]
@devinrader VoiceResponse object toString Converting Xml but How To Convert Dial Object Into Xml

**Comment by devinrader** [comment]
@himadrinath since Twiml requires that `<Response>` be the root tag there isn't a way to just serialize `<Dial>` to a string.  If you want to include `<Dial>` in your TwiML response you can do something like this:

    var response = new Twilio.TwiML.VoiceResponse();
    response.Dial("+15555555555");
    var result = response.ToString();

This will generate this TwiML:

    <?xml version="1.0" encoding="utf-8"?>
    <Response>
       <Dial>+15555555555</Dial>
    </Response>

Hope that helps

**Comment by himadrinath** [comment]
@devinrader I want this

```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial>
        <Number
         statusCallbackEvent="initiated ringing answered completed"
         statusCallback="https://myapp.com/calls/events"
         statusCallbackMethod="POST">
            +14158675309
        </Number>
    </Dial>
</Response>
```

**Comment by devinrader** [comment]
Here you go:

    var response = new Twilio.TwiML.VoiceResponse();
    response.Dial(
        new Dial().Number(
            phoneNumber: "+15555555555", 
            statusCallbackEvent: "initiated ringing answered completed",
            statusCallback: "https://example.com/status",
            statusCallbackMethod: "POST")
    );
    var result = response.ToString();

**Comment by jingming** [comment]
Answered. Thanks @devinrader!

**Comment by himadrinath** [comment]
thanks
