### ISSUE TITLE
The version on nuget file is 0.0.0.0

### ISSUE THREAD

**Issue by JBaltika** [twilio/twilio-csharp#347]
**Version:**
5.2.1

[assembly: AssemblyVersion("0.0.0.0")]

**Comment by dprothero** [comment]
Can you let us know where, specifically, you're seeing this?

**Comment by JBaltika** [comment]
Hi, 
i got nuget from nuget.org and 5.2.1 or later is still the same (Twilio.dll):

using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;

[assembly: AssemblyCopyright("Twilio")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyVersion("0.0.0.0")]

**Comment by JBaltika** [comment]
Hi guys, can you fix this as it really screws up our deployments which depends on library version.

Thanks

**Comment by efossier** [comment]
@JBaltika Hey, sorry this took so long to get to, I believe this PR will fix it: https://github.com/twilio/twilio-csharp/pull/351

**Comment by JBaltika** [comment]
I checked the files from nuget.org. The version is still 0.0.0.0. 

Also consider to add to AssemblyInfo.cs standard attributes as these attributes are used by many troubleshooting or security tide up tools for enterprise deployments for production environments with high security requirements. 

[assembly: Guid("")]
[assembly: AssemblyTitle("")]
[assembly: AssemblyDescription("")]

#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif

[assembly: AssemblyInformationalVersion("")]

**Comment by dprothero** [comment]
@JBaltika the PR hasn't been merged yet.

**Comment by Gfweis** [comment]
Just got version 5.4.0 from NuGet - File & Assembly versions are 0.0.0.0

**Comment by JBaltika** [comment]
Hi guys,
What is the status? We use Twilio in our commercial application and we need to deliver to customers a new version as part of sprint. Is it possible to merge and publish the nugets, please

**Comment by efossier** [comment]
@JBaltika Sorry for a delay, we'll get a release out today.

**Comment by efossier** [comment]
@JBaltika @Gfweis This should be fixed in the latest releases `5.4.1` and `5.4.2-alpha1`. Thank you for your patience.
