### ISSUE TITLE
Twilio OutBound Call Issue. As Per the new Sdk i.e version 5  with that not able to make calls with Twimlet echo  there is the sample, it works for conference call but it doesnt work for echo.

### ISSUE THREAD

**Issue by prabhurashmi** [twilio/twilio-csharp#349]
const string accountSid = "Ac7878787878787";
            const string authToken = "24332432424242424";

          

            TwilioClient.Init(accountSid, authToken);

       
            var to = new PhoneNumber("xxxxxxxxxx");
            var from = new PhoneNumber("+xxxxxxxxxx");
            var call = CallResource.Create(
              to,
              from,
              url: new Uri("http://twimlets.com/echo?Twiml=%3CResponse%3E%3CSay%3EHi+there.%3C%2FSay%3E%3C%2FResponse%3E"));

            var sid = call.Sid;

**Comment by efossier** [comment]
Can you elaborate on the problem you are seeing? 
Is an exception thrown? If so please provide the stacktrace. 

If there is no exception and the problem is that the call is not behaving as you expect then that would not be a C# helper library issue.

**Comment by prabhurashmi** [comment]
there is no exception.call is trigered by it says application error. same Url if i use as per the Twilio SDk 3 version it works fine.

**Comment by prabhurashmi** [comment]
I would really appreciate quick reply..

**Comment by dprothero** [comment]
@prabhurashmi since this isn't a helper library issue, you'll find you get quicker responses by opening a support ticket here: https://support.twilio.com/
