### ISSUE TITLE
 Twilio Voice Call Issue as per the New Dll Version 5.3.0

### ISSUE THREAD

**Issue by prabhurashmi** [twilio/twilio-csharp#350]
Below is the Code Snippet as per The Dll Version Twilio 5.3.0- From the below Piece of Code,Call gets triggered but the call says Application Error.

const string accountSid = "ACXXXXXXXXXXXXXXXXXXXX";
const string authToken = "74398742987492rsrewrwre";
TwilioClient.Init(accountSid, authToken);

var url1 = "http://twimlets.com/echo?Twiml=%3CResponse%3E%3CSay%3EHi+there.%3C%2FSay%3E%3C%2FResponse%3E";

            var to = new PhoneNumber("+919000000000");
            var from = new PhoneNumber("+919000000001");
            var call = CallResource.Create(to, from, url: new Uri(url1), method: "POST");
            

Below is the Code Snipper as per The Dll Version Twilio.Api 3.4- From the below Piece of Code,Call gets triggered and the voice Says what it is meant to say as per the url.

string AccountSid = "ACXXXXXXXXXXXXXXXXXXXX";
string AuthToken = "74398742987492rsrewrwre";
var twilio = new TwilioRestClient(AccountSid, AuthToken);

var options = new CallOptions();
options.To = "+919000000000";
options.From = "+919000000001";
options.Method = "GET";
options.Url = "http://twimlets.com/echo?Twiml=%3CResponse%3E%3CSay%3EHi+there.%3C%2FSay%3E%3C%2FResponse%3E";

  var call = twilio.InitiateOutboundCall(options);

Kindly let me know, how to make call in last version(The Dll Version Twilio 5.3.0).

**Comment by dprothero** [comment]
Here's the code you need:

https://www.twilio.com/docs/guides/how-to-make-outbound-phone-calls-in-csharp?code-sample=code-make-an-outbound-call&code-language=cs&code-sdk-version=5.x
