### ISSUE TITLE
Make TwiML classes consistent

### ISSUE THREAD

**Issue by waynebrantley** [twilio/twilio-csharp#355]
``VoiceResponse`` has the XML elements private and when you are done, you simply ``ToString()`` the object.
``Dial`` as well as many others expose the XML element publicly and do not provide a ``ToString()`` method.

They should all be the same - probably with the ``ToString()`` method

**Comment by waynebrantley** [comment]
I did not realize everything was used by VoiceResponse.
Consider making the XML element on the other classes as 'internal' so api users know not to use it.

**Comment by jhurdlow** [comment]
In the older version of the libraries, the XML element was not private. This allowed us to add XComments to it in our WebHooks, which made it easier to debug problems. I would prefer to either see the XML made public so we can continue to do this, or add a Comment(...) method to VoiceResponse so this ability is natively supported. I'm happy to submit a PR.

**Comment by waynebrantley** [comment]
@jhurdlow I have yet to see them reply or do anything that is asked.  However, when asked they said they will now accept pull requests (they were not before).   To maintain how their library works, rather than make that variable public, consider just adding a method that accepts comments and then adds to the private variable.

**Comment by efossier** [comment]
@waynebrantley @jhurdlow Hello! Sorry for not getting to this sooner, we've been swamped trying to maintain all 6 twilio helper libraries as well as well as make progress on the api work we need to do. We've been making a concerted effort in recent months to service the library issues better, that being said this issue and many others still haven't gotten the attention they deserve and we apologize for that. 

I've created a ticket to track this work on our end and we'll be addressing it as soon as we can. In the meantime we always welcome pull requests if you would like to make the changes yourself.

**Comment by jmctwilio** [comment]
The libraries will be automatically generating TwiML to prevent inaccuracies and inconsistencies between the verbs available at Twilio and those incorporated in the helper libraries.  Thank you for your feedback.
