### ISSUE TITLE
Conference - argument should be boolean

### ISSUE THREAD

**Issue by waynebrantley** [twilio/twilio-csharp#356]
TwiML

``Dial.Conference`` method takes a ``beep`` parameter.  This is true/false and should be a boolean.

**Comment by efossier** [comment]
@waynebrantley The Conference `beep` parameter accepts the following values: `true`, `false`, `onEnter`, `onExit`.

https://www.twilio.com/docs/api/twiml/conference

**Comment by waynebrantley** [comment]
@efossier 
Perhaps an enum would be in order then?

**Comment by efossier** [comment]
@waynebrantley Yeah I agree an enum would the the idea solution but seeing as the other enum-like parameters such as `trim` don't have enums we dont want to introduce an enum for this parameter only and we also dont have the bandwidth to do this for every parameter at the moment.

Most likely when we move to generating the twiml classes as well this will happen automatically as we have better definitions of what each parameter should take and can more strongly type them. I expect us to begin working on this in the near to medium future.
