### ISSUE TITLE
TwiML api not consistent with Rest api

### ISSUE THREAD

**Issue by waynebrantley** [twilio/twilio-csharp#358]
TwiML:
- when specifying statusCallback it is a string  (like on Dial)
- when specifying statusCallbackEvent it is a string (like on Dial)

Rest Resources:
- when specifying statusCallback it is a Uri  (like on CallResource.Create)
- when specifying statusCallbackEvent it is a list<string> (like on CallResource.Create)

The TwiML should probably mirror the Rest api where appropriate.

**Comment by efossier** [comment]
@waynebrantley Yep we definitely want to do that, this probably stems from the fact that the twiml is currently handwritten code. We are currently working on making that generated as well which should greatly help with consistency in the library.

**Comment by jmctwilio** [comment]
The libraries will be automatically generating TwiML to prevent inaccuracies and inconsistencies between the verbs available at Twilio and those incorporated in the helper libraries. Thank you for your feedback.
