### ISSUE TITLE
Twilio.Rest.Video.V1 is missing

### ISSUE THREAD

**Issue by Firex** [twilio/twilio-csharp#359]
**Version: 5.4.1**
**API Subdomain: Twilio.Rest.Video.V1**

We are working with Twilio Video and now wants to enable recording, in [documentation ](https://twilio.github.io/twilio-csharp/5.4.1/class_twilio_1_1_rest_1_1_video_1_1_v1_1_1_create_room_options.html) you have reference to a file src/Twilio/Rest/Video/V1/RoomOptions.cs, however it's missing from both - source code and release pack.

Are we doing something wrong or it's not released yet?

**Comment by efossier** [comment]
@Firex That is a beta product and therefore it is included in the `alpha` packages we release alongside our main packages. The alpha packages always have a patch version 1 higher than the corresponding mainline package version so in this case you would want to download `5.4.2-alpha1`
