### ISSUE TITLE
Sudden NullReferenceException in HandleErrorResponse when calling MessageResource.Create on production

### ISSUE THREAD

**Issue by adamtal3** [twilio/twilio-csharp#361]
**Version:** reproduced on 5.4.0 and 5.5.0

### Code Snippet
```c#
            try
            {
                var msg = MessageResource.Create(new PhoneNumber(phoneNumber),
                    from: new PhoneNumber(alphanumericId),
                    body: messageBody);
            }
            catch (Twilio.Exceptions.RestException ex)
            {
                    // This doesn't catch the error (it's not a RestException)
                    throw;
            }
```

### Exception / Log
```c#
System.NullReferenceException: Object reference not set to an instance of an object.
   at Twilio.Http.WebRequestClient.HandleErrorResponse(HttpWebResponse errorResponse)
   at Twilio.Http.WebRequestClient.MakeRequest(Request request)
   at Twilio.Clients.TwilioRestClient.Request(Request request)
   at Twilio.Rest.Api.V2010.Account.MessageResource.Create(CreateMessageOptions options, ITwilioRestClient client)
   at Twilio.Rest.Api.V2010.Account.MessageResource.Create(PhoneNumber to, String pathAccountSid, PhoneNumber from, String messagingServiceSid, String body, List`1 mediaUrl, Uri statusCallback, String applicationSid, Nullable`1 maxPrice, Nullable`1 provideFeedback, Nullable`1 validityPeriod, ITwilioRestClient client)	
```

### Steps to Reproduce
I could reproduce this error only on my production server.
Running on localhost worked as expected.
I get this error sending to a valid number that works at first but after about 5 messages it stops working (with exact same to/from/body values). Also, it fails immediately (not a timeout).
It keeps failing with this exception until I restart the application pool or the iis server.

What can cause this `NullReferenceException` inside [`HandleErrorResponse`](https://github.com/twilio/twilio-csharp/blob/f25643d51d54af25dd4a21f3ba98c2e56c391d46/src/Twilio/Http/WebRequestClient.cs#L47)?
I couldn't get any valuable information from this exception..

**Comment by adamtal3** [comment]
I've managed to find the problem using a custom build I made of this library. I've created a pull request fixing the exception handling so other users can see the problem right.

**Comment by efossier** [comment]
@adamtal3 What was the root cause of the error? Anything we need to fix in the library itself apart from exposing more information when an error occurs?

**Comment by adamtal3** [comment]
@efossier The error was caused by an unsupported TLS security protocol (It was sudden because I had a task running once an hour that accesses an https api and sets the `ServicePointManager.SecurityProtocol` to a different value before doing so - and it seems it didn't set it back to its original value).

Once I've used my custom build I saw the correct error.. the main problem is that the error was hidden and disguised by `NullReferenceError`.
When I had an idea it was using the wrong TLS protocol I just added: (and I made sure the other place in my code also sets back the `SecurityProtocol` value to its original state)

```
            var securityProtocol = ServicePointManager.SecurityProtocol;
            var expect100Continue = ServicePointManager.Expect100Continue;

            try
            {
                ServicePointManager.Expect100Continue = true;
                ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

                // ... MessageResource.Create ...
            }
            finally
            {
                ServicePointManager.Expect100Continue = expect100Continue;
                ServicePointManager.SecurityProtocol = securityProtocol;
            }
```
