### ISSUE TITLE
Dialing Conference not able to fetch the conference Sid after the Conference has started, only the callSid cab be fetched.

### ISSUE THREAD

**Issue by prabhurashmi** [twilio/twilio-csharp#369]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

**Version:**
**API Subdomain (api/taskrouter/ip_messaging):**

### Code Snippet
```c#
# paste code here
```

### Exception / Log
```
<place exception / log here>
```

### Steps to Reproduce
1.
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by ilanbiala** [comment]
@prabhurashmi please provide some code and the error you are facing.

**Comment by prabhurashmi** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Twilio.AspNet.Common;
using Twilio.AspNet.Mvc;
using TwilioMVC.Models;
using System.Data;
using Twilio.Rest.Api.V2010.Account;
using Twilio;
using Twilio.TwiML;
using System.Net.Http;
using CLB;
using TwilioCallConference;


namespace TwilioMVC.Controllers
{
    public class TwilController : TwilioController
    {

        [HttpPost]
        public TwiMLResult Index(VoiceRequest request)
        {
            var response = new Twilio.TwiML.VoiceResponse();
            try
            {
                var gather = new Twilio.TwiML.Gather(numDigits: 4, action: $"{Request.Url.Scheme}://{Request.Url.Authority}{Url.Content("~")}/Twil/gather", method: "POST").Say("Please enter your Incident ID, to place in conference.");
                         response.Gather(gather);
            }
            catch (Exception ex)
            {
                LogFile objlogfile = new LogFile();
                objlogfile.LoggingMsg(ex.ToString());
            }
            return TwiML(response);
    }
       
        [HttpPost]
        public TwiMLResult Gather(VoiceRequest request)
        {
            var response = new Twilio.TwiML.VoiceResponse();
            LogFile log = new LogFile();
            try
            {
                
                response.Say("your are inside response");
                 if (!string.IsNullOrEmpty(request.Digits))
                {

                    string strTicked_ID = string.Empty;
                           
                    var dial = new Twilio.TwiML.Dial();
             
                    dial.Conference(request.Digits, statusCallback: $"{Request.Url.Scheme}://{Request.Url.Authority}{Url.Content("~")}/Twil/ConferenceDtls" , statusCallbackMethod: "POST",statusCallbackEvent: "join");
                    response.Dial(dial);
                }
            }
            catch (Exception ex)
            {             
            }
           
            return TwiML(response);

        }

        [HttpPost]
        public TwiMLResult ConferenceDtls(VoiceRequest request)
        {
         
            var response = new Twilio.TwiML.VoiceResponse();
        
            try
            {
                LogFile objlogfile = new LogFile();
              
                const string accountSid = "zzzzzzzzzzzzzzzzzzzzzz";
                const string authToken = "zzzzzzzzzzzzzzzzzzzz";

          
                TwilioClient.Init(accountSid, authToken);
              
                var conferences1 = ConferenceResource.Read(status: ConferenceResource.StatusEnum.Init);

           
                foreach (var conference in conferences1)
                {
                    objlogfile.LoggingMsg(conference.Sid.ToString());
                     objlogfile.LoggingMsg(conference.Status.ToString());
                    
                }
              
            }catch(Exception ex)
            {
                
            }
            return TwiML(response);

        }
    }

}

**Comment by prabhurashmi** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Twilio.AspNet.Common;
using Twilio.AspNet.Mvc;
using TwilioMVC.Models;
using System.Data;
using Twilio.Rest.Api.V2010.Account;
using Twilio;
using Twilio.TwiML;
using System.Net.Http;
using CLB;
using TwilioCallConference;


namespace TwilioMVC.Controllers
{
    public class TwilController : TwilioController
    {

        [HttpPost]
        public TwiMLResult Index(VoiceRequest request)
        {
            var response = new Twilio.TwiML.VoiceResponse();
            try
            {
                var gather = new Twilio.TwiML.Gather(numDigits: 4, action: $"{Request.Url.Scheme}://{Request.Url.Authority}{Url.Content("~")}/Twil/gather", method: "POST").Say("Please enter your Incident ID, to place in conference.");
                         response.Gather(gather);
            }
            catch (Exception ex)
            {
                LogFile objlogfile = new LogFile();
                objlogfile.LoggingMsg(ex.ToString());
            }
            return TwiML(response);
    }
       
        [HttpPost]
        public TwiMLResult Gather(VoiceRequest request)
        {
            var response = new Twilio.TwiML.VoiceResponse();
            LogFile log = new LogFile();
            try
            {
                
                response.Say("your are inside response");
                 if (!string.IsNullOrEmpty(request.Digits))
                {

                    string strTicked_ID = string.Empty;
                           
                    var dial = new Twilio.TwiML.Dial();
             
                    dial.Conference(request.Digits, statusCallback: $"{Request.Url.Scheme}://{Request.Url.Authority}{Url.Content("~")}/Twil/ConferenceDtls" , statusCallbackMethod: "POST",statusCallbackEvent: "join");
                    response.Dial(dial);
                }
            }
            catch (Exception ex)
            {             
            }
           
            return TwiML(response);

        }

        [HttpPost]
        public TwiMLResult ConferenceDtls(VoiceRequest request)
        {
         //Firstly here not able to fetch the conferencesid - 
		   var id=request.CallSid;
            var sid=request.DialCallSid;
			
            var response = new Twilio.TwiML.VoiceResponse();
        
            try
            {
                LogFile objlogfile = new LogFile();
              
			// Now trying to fetch conferene sid using rest api but there also error is coming below is the error generated
                const string accountSid = "zzzzzzzzzzzzzzzzzzzzzz";
                const string authToken = "zzzzzzzzzzzzzzzzzzzz";

          
                TwilioClient.Init(accountSid, authToken);
              
                var conferences1 = ConferenceResource.Read(status: ConferenceResource.StatusEnum.Init);

           
                foreach (var conference in conferences1)
                {
                    objlogfile.LoggingMsg(conference.Sid.ToString());
                     objlogfile.LoggingMsg(conference.Status.ToString());
                    
                }
              
            }catch(Exception ex)
            {
                
            }
            return TwiML(response);

        }
    }

}


Error: System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 52.7.124.13:443
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Twilio.Http.SystemNetHttpClient.<MakeRequestAysnc>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Twilio.Http.SystemNetHttpClient.MakeRequest(Request request)
   at Twilio.Clients.TwilioRestClient.Request(Request request)
   at Twilio.Rest.Api.V2010.Account.ConferenceResource.Read(ReadConferenceOptions options, ITwilioRestClient client)
   at TwilioCallConference.TwilioCalingConference.CallConference() in C:\Users\inrprabhu20\Documents\Visual Studio 2015\Projects\TwilioMVC\TwilioCallConference\TwilioCalingConference.cs:line 29
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 52.7.124.13:443
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Twilio.Http.SystemNetHttpClient.<MakeRequestAysnc>d__4.MoveNext()<---

**Comment by efossier** [comment]
@prabhurashmi This looks more like an issue connecting to Twilio in general from the error message: `System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 52.7.124.13:443`. 

Is this still going on? Are you able to make any other api calls? Are you able to `curl https://api.twilio.com`?
