### ISSUE TITLE
Gather constructor doesn't support set speechTimeOut as "auto"

### ISSUE THREAD

**Issue by jorge-henao** [twilio/twilio-csharp#391]
Acording to [the docs](https://www.twilio.com/docs/api/twiml/gather), the Gather verb supports to setting "auto" value for speechTimeOut attribute. However The Gather constructor expects and int type so is not possible to specify "auto" string value.

**Version: Twilio 5.6.4**

### Code Snippet
          var gather = new Gather(input: "speech", action: GetActionUrl(), speechTimeout: "auto" /*Not supported*/, language: Constants.Language, method: "POST", bargeIn: true);

# 
```

**Comment by jmctwilio** [comment]
The libraries will be automatically generating TwiML to prevent inaccuracies and inconsistencies between the verbs available at Twilio and those incorporated in the helper libraries. Thank you for your feedback.
