### ISSUE TITLE
Number() method does not handle a relative URL for the status callback URL

### ISSUE THREAD

**Issue by RNCRyan** [twilio/twilio-csharp#395]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:** 5.7.0

### Code Snippet
```csharp
	private const string OC_DIAL_STATUS_URL_RELATIVE = "/Call/OCDialStatus";
	private const string OC_DIAL_STATUS_URL_ABSOLUTE = "https://sample.com/Call/OCDialStatus";

	var dial = new Dial(null, 20, null, VOICEMAIL_URL, null, request.To, "record-from-answer", "trim-silence", STATUS_URL);
	dial.Number(forwardedPhoneNumber.TwilioFormattedPhoneNumber, null, OC_DIAL_URL, null, "initiated answered completed", OC_DIAL_STATUS_URL_RELATIVE); // this fails with Error 21609 Invalid StatusCallback URL
	dial.Number(forwardedPhoneNumber.TwilioFormattedPhoneNumber, null, OC_DIAL_URL, null, "initiated answered completed", OC_DIAL_STATUS_URL_ABSOLUTE); // this works

	response.Dial(dial);
```

### Exception/Log
```
(In the Twilio debugger console)
Error - 21609

Invalid StatusCallback URL

Possible Solutions

Make sure you submit a fully qualified URL including:
protocol (http:// or https://)
hostname
file path
properly url-encoded query parameters
Twilio must be able to reach this URL over the public Internet.
```

### Steps to Reproduce
1. Create a Dial.Number method call with a relative URL

### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by efossier** [comment]
@RNCRyan Thanks for writing in, this sounds like a feature request for all TwiML rather than the TwiML helpers in this library. I encourage you to reach out to help@twilio.com if you would like us to support this feature and they can do a better job of getting this in front of the relevant team(s). 

Closing this as this is not an issue with the C# library and would be implemented within Twilio.
