### ISSUE TITLE
NuGet package does not install in Visual Studio 2017

### ISSUE THREAD

**Issue by grahambunce** [twilio/twilio-csharp#401]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:**
5.9.0

### Exception/Log

Error		Failed to add reference. The package 'Twilio' tried to add a framework reference to 'System.Net.Http' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

### Steps to Reproduce
1. Create .NET 4.6.1 Console app (e.g. web job)
2. Install package

**Comment by grahambunce** [comment]
To fix I had to manually add the nuget package System.Net.Http

**Comment by mikeycdavis** [comment]
I followed the steps to reproduce and was successfully able to add the package to a new .NET 4.6.1 Console app with no errors.
