### ISSUE TITLE
CallResource.Create does not support from Client Type

### ISSUE THREAD

**Issue by zxed** [twilio/twilio-csharp#402]
Documentation states that **to** _AND_ **from** can be client's https://www.twilio.com/docs/api/voice/making-calls#required-parameters

The following should work - but does not for C# - Works fine for Py.....

### Code Snippet
```csharp
var to = new Client("Bob");
var from = new Client("Tom");
var call = CallResource.Create(to,
                               from,
                               url: new Uri("http://demo.twilio.com/docs/voice.xml"));

```

Specifically - note that I have from as a client - not a phone number.

**Comment by zxed** [comment]
specifically, seems like the issue is here: https://github.com/twilio/twilio-csharp/blob/master/src/Twilio/Rest/Api/V2010/Account/CallResource.cs#L139 ?

```
public static CallResource Create(IEndpoint to, 
                                          Types.PhoneNumber from, 
```

**Comment by alexcchan** [comment]
As a workaround, you can use

```
var to = new PhoneNumber("client:Bob");
var from = new PhoneNumber("client:Tom");
```

but I concur, `Client` should be supported.

**Comment by pwoosam** [comment]
Has there been any word on this? I am also trying to make a call to a client using `CallResource.Create()`, but nothing seems to be working.

This should work, but does not
```C#
var clientTo = new Client(userId);
var numberFrom = new PhoneNumber(request.FromNumber);

CallResource.Create(clientTo, numberFrom);
```
This results in: `The phone number you are attempting to call, <userid>, is not valid`


This does not work for me either
```C#
var numberTo = new PhoneNumber($"client:{userId}");
var numberFrom = new PhoneNumber(request.FromNumber);

CallResource.Create(numberTo, numberFrom);
```
This results in: `Called is not valid client:<userid>`

**Comment by pwoosam** [comment]
Update:
The `new PhoneNumber("client:<userid>")` workaround works.

The reason I was getting `Called is not valid client:<userid>` is because there were dashes in our userids. 

Although clients can have names with dashes, the REST API's `To` and `From` parameters do not accept dashes and will result in a 400 error.

Not accepting dashes in the `To` parameter of the REST API is inconsistent with the TwiML <Dial> verb which can accept client names with dashes.

**Comment by childish-sambino** [comment]
👀
