### ISSUE TITLE
Unable to use relative or same URL for Voice Redirect

### ISSUE THREAD

**Issue by ShelbyZ** [twilio/twilio-csharp#403]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

The code in TwiML/Voice/Redirect.cs is auto-generated, but makes calls to the AbsoluteUri property in GetElementBody() override.  The [documentation](https://www.twilio.com/docs/api/twiml/redirect) indicating relative URIs are allowed.

**Version:**
5.9.0

### Code Snippet
```csharp
// test 1
var response = new VoiceResponse();
response.Say("Hello World");
response.Redirect(null, Twilio.Http.HttpMethod.Get);

// test 2
var response = new VoiceResponse();
response.Say("Hello World");
response.Redirect(new Uri("../primary", UriKind.Relative), Twilio.Http.HttpMethod.Get);
```

### Exception/Log
// test 1
Adds increasing amounts of query params - [stackoverflow](https://stackoverflow.com/questions/47543724/twilio-voice-redirect-to-same-url)

```
// test 2
Invalid URI: The format of the URI could not be determined.
```

### Steps to Reproduce
Execute the above tests and notice that the results are either work with odd side effects or do not work at all.

**Comment by philnash** [comment]
Twilio developer evangelist here.

Thanks for reporting this! You should now find that `AbsoluteUri` is no longer used and you can use a relative URL since version 5.9.5. A serializer has now been implemented for URLs in PR #409.
