### ISSUE TITLE
Allow support for Newtonsoft 10+

### ISSUE THREAD

**Issue by dougleu** [twilio/twilio-csharp#405]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

After upgrading to the latest version (5.9.1), this error keeps popping out. 

I have cleaned my solution, checked my app.configs, verified that the latest binaries are in the correct location, etc.

### Code Snippet
            TwilioClient.Init(_sid, _token);
            try
            {
                var _to = new PhoneNumber(pHistory.twilio_country_code + _phone);
                var _from = new PhoneNumber(pLogin.assigned_sms_number);

                        message = MessageResource.Create(
                            to: _to,
                            from: _from,
                            body: pBody);
# paste code here
```

### Exception/Log
```
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Twilio.Clients.TwilioRestClient.ProcessResponse(Response response)
   at Twilio.Rest.Api.V2010.Account.MessageResource.Create(CreateMessageOptions options, ITwilioRestClient client)
   at Twilio.Rest.Api.V2010.Account.MessageResource.Create(PhoneNumber to, String pathAccountSid, PhoneNumber from, String messagingServiceSid, String body, List`1 mediaUrl, Uri statusCallback, String applicationSid, Nullable`1 maxPrice, Nullable`1 provideFeedback, Nullable`1 validityPeriod, String maxRate, Nullable`1 forceDelivery, String providerSid, ContentRetentionEnum contentRetention, AddressRetentionEnum addressRetention, Nullable`1 smartEncoded, ITwilioRestClient client)
   at WPR.wprAGENT.Mailer.ProcessSms(Login pLogin, History pHistory, String pBody)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

```

### Steps to Reproduce
1.
2.
3.


### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by zkost** [comment]
Twilio specifically references newtonsoft.json 9.0.0.0. you have to downgrade to newtonsoft to 9.0.0.0. During my testing I could not get twilio 5.9.2 to work newtonsoft.json 10.x.

**Comment by dougleu** [comment]
Make sure you have these 2 items in your app.config.

  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>

**Comment by dougleu** [comment]
I would be happy to take a loik at it with you if you wanted. Lmk.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by dougleu** [comment]
So you are good.to go?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dprothero** [comment]
Does someone have a .csproj they could share with us that reproduces the issue?
