### ISSUE TITLE
InputEnum.DtmfSpeech does not work, wrong string constant

### ISSUE THREAD

**Issue by HGSandhagen** [twilio/twilio-csharp#413]
TwiML Gather does not work for input= speech **and** dtmf when using InputEnum.DtmlSpeech to define it, because InputEnum uses the wrong string 'dtmf_speech'.

**Version:**

### Code Snippet
```csharp
// does not work
var gather = new Gather(input: Gather.InputEnum.DtmfSpeech, timeout: 3, numDigits: 1);

// works        
var gather = new Gather(input: "speech dtmf", timeout: 3, numDigits: 1);
```

### Exception/Log
On the web page a warning is shown for the request:

Msg=input must be'DTMF', 'Speech', or 'DTMF Speech' &input=dtmf_speech&ErrorCode=13326&LogLevel=WARN

The generated TmiML is 
```
<Gather input="dtmf_speech" timeout="3" numDigits="1" >
```

**Comment by richardkeller411** [comment]
For anyone looking you can pass both in a list to the Method
 var _inputenum = new List<InputEnum >{ "speech","dtmf"};
voiceResponse.Append( new Gather(_inputenum, x,x,x,x ) ;

**Comment by thinkingserious** [comment]
Thanks for helping out @richardkeller411!

Hi @HGSandhagen, @brunoalbano,

I'm closing this issue per the solution proposed by @richardkeller411. If you still need help, please feel free to re-open. Thanks!

With best regards,

Elmer
