### ISSUE TITLE
Twillo sample does not work for create Async

### ISSUE THREAD

**Issue by weedkiller** [twilio/twilio-csharp#417]
```
    public async Task<MessageResource> SendMessage(string from, string to, string body, List<Uri> mediaUrl, Client client)
        {
            var toPhoneNumber = new PhoneNumber(to);
            return await MessageResource.CreateAsync(
                toPhoneNumber,
                from: new PhoneNumber(from),
                body: body,
                //mediaUrl: mediaUrl,
                client: client);
        }
```
The [sample from twillo](https://www.twilio.com/docs/sms/tutorials/server-notifications-csharp-mvc) above does not work.

![image](https://user-images.githubusercontent.com/21086190/38108151-f35889a6-3361-11e8-8c2c-2cedf7f0ecc0.png)

**Comment by dubstylee** [comment]
@weedkiller Which version of the API are you using? Make sure to use `Twilio.Rest.Api.V2010.Account` to use the `mediaUrl` parameter.

**Comment by weedkiller** [comment]
@dubstylee I was using latest.

I tried latest download from here, and also saw a nuget. Does not build in VS 2017 targeting 4.71 or 4.72 which ships with Win 10 ENT install since 2018 jan.

**Comment by thinkingserious** [comment]
Thanks for helping out @dubstylee!

@weedkiller,

Please let me know if you are still having issues and we will re-open.

**Comment by weedkiller** [comment]
hello both the sample, does not work in 4.8 with progress task, or IProgress report or simply compile because its the old task interface. I posted the picture with the link, but its not resolved yet

**Comment by childish-sambino** [comment]
What namespace are you using? There are several `MessageResource` classes defined in the lib under different namespaces. The one you want (that contains the `mediaUrl` param is under the `Twilio.Rest.Api.V2010.Account` namespace: https://github.com/twilio/twilio-csharp/blob/master/src/Twilio/Rest/Api/V2010/Account/MessageResource.cs#L204

See the `using` statements in the example you linked in the description.
