### ISSUE TITLE
Misused HttpClient?

### ISSUE THREAD

**Issue by nforysinski** [twilio/twilio-csharp#420]
It appears that TwilioRestClient spinup always generates a new HttpClient under the covers. This is a misuse of the HttpClient which suggests as a best practice using (and reusing) one singular HttpClient as outlined here: https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client#create-and-initialize-httpclient

In situations where the client is being used for multiple different subaccounts, simply doing a single `TwilioClient.Init` at app warmup isn't an option. I am a bit worried there is over-creation of HttpClients going on and if there should be further discussion on HttpClient reuse within the TwilioRestClient.

Am I missing something here or does this seem like a real problem? 

**Version: 5.10.0**

**Comment by dprothero** [comment]
@nforysinski Thanks for raising this point. Yes, the guidance is correct that you want to reuse an `HttpClient` object, for sure. Most people don't need multiple `TwilioRestClient`s, so they can just use `TwilioClient.Init` and we will keep track of it for them.

If you need to create multiple `TwilioRestClient` objects, then we recommend you pass in your own `HttpClient` into the constructor so it will reuse it.

This article doesn't directly address your question, but it does illustrate how to pass your own `HttpClient` when creating your own `TwilioRestClient` objects:
https://www.twilio.com/docs/libraries/csharp/custom-http-clients-dot-net-framework

Let me know if you have any other questions.
