### ISSUE TITLE
How does Twilio Init work?

### ISSUE THREAD

**Issue by adamreed90** [twilio/twilio-csharp#432]
Sorry for going out of format, but I was hoping for a quick answer to a silly question.

I scanned over the code for a bit and I can't seem to understand how functions like AccountResource.Read() are able to know what TwilioClient to use, how is this achieved? 

We are building an application using multiple credentials and want to ensure we do not cross-contaminate requests.

**Comment by imthepitts** [comment]
Hi @adamreed90, 

Sorry for the confusion. 

The `Init()` method sets the credentials as static properties: https://github.com/twilio/twilio-csharp/blob/master/src/Twilio/Twilio.cs#L11-L13 

If you are using multiple credentials, instantiate `TwilioRestClient` directly for each request to ensure thread safety. 

Example: https://gist.github.com/dprothero/165f0544d752ade2c29841d7882efa8e#file-program-cs-L17
