### ISSUE TITLE
Could not load file or assembly 'System.Net.Http'

### ISSUE THREAD

**Issue by zkost** [twilio/twilio-csharp#436]
I've been using Twilio for many years. Awesome product and service! When it works, it works reliably, when it breaks it breaks reliably. I'm not sure if this is a Twilio issue or a Twilio symptom considering the many, many .net changes going on. 

**Version:**
vs2017 15.7.5
.Net 4.7.2 (version 4.7.03056)
Twilio 5.14.1.0 

### Code Snippet
```csharp
      string _fromNumber = "+1....";
      string _accountSid = "....";
      string _authToken = "....";

      // Find your Account Sid and Auth Token at twilio.com/console
      TwilioClient.Init(_accountSid, _authToken);

      CreateMessageOptions sms = new CreateMessageOptions(new Twilio.Types.PhoneNumber("+1...."))
      {
        From = new Twilio.Types.PhoneNumber(_fromNumber),

        // only send the first 160 characters of a message.
        Body = "Test"
      };
	  // this next line of code is where the exception is thrown
      MessageResource.Create(sms);
```

### Exception/Log
```
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.dll
Additional information: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

### Steps to Reproduce
1. Blank new project. Set to 4.7.2, install Twilio 5.14.1.0 and download dependencies from nuget
2. Run the above code and you get the exception. I confirm that System.net.http verson 

My app.config 
```
<runtime>
   ....
         <dependentAssembly>
            <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0" />
         </dependentAssembly>
```
		 
Considerations:
1. First guess is that there is a reference issue in Twilio.dll 5.14.1.0 when running 4.7.2
2. Twilio 5.14.1.0 is not compatible with Net 4.7.2
3. The exception is a red herring for some other exception not bubbling up.
4. This very well be within my code, but I can't make it any more vanilla. 

Is anyone else experiencing this or similiar issue? For me downgrading is not an option. Any insight is greatly appreciated.

**Comment by dsghi** [comment]
Where did the `System.Net.Http` binding redirect come from in your `app.config`? The redirect is not part of a 4.7 console app or blank web application template nor is it added by the Twilio package. I would suggest taking that out and trying without it... 

Here's what I have with a blank console app and the Twilio package:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IdentityModel.Tokens.Jwt" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.4.0" newVersion="5.2.4.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Tokens" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.4.0" newVersion="5.2.4.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by zkost** [comment]
Derek, 

I was asking the wrong question. I was chasing why "System.Net.Http" cannot be found rather then why is it there in the first place. That was my issue. I removed the reference from my app.config and all is working. 

Now the question is how did 'System.Net.Http' it get into my app.config? I must have unknowingly added it or it was done as part of a nuget update. I'm betting and hoping it was me; in either case it's not an issue for Twilio. 

Issue Closed. 

Thanks for the nudge in the right direction.
-Ben
