### ISSUE TITLE
testing the method TestTlsProtocol in .net 4.5.* doesn't throw an exception

### ISSUE THREAD

**Issue by guya1976** [twilio/twilio-csharp#438]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:**
5.14.1
### Code Snippet
```csharp
# paste code here
```
public class Client
    {
        public Client(string username, string password)
        {
            TwilioClient.Init(username, password);
        }

        public void SendSms(string number, string from, string message)
        {
            try
            {
                var msg = MessageResource.Create(
                    to: new PhoneNumber(number),
                    from: new PhoneNumber(from),
                    body: message);

                if (!msg.ErrorCode.HasValue)
                {
                    Logger.Log("TwilioClient", $"sms message to {msg.To} - {msg.Status} on {msg.DateCreated}", new { msg.Sid, msg.Body });
                }
                else
                {
                    throw new Exception($"message {msg.Sid} failed - {msg.ErrorMessage} ({msg.ErrorCode.Value})");
                }
            }
            catch (Exception ex)
            {
                Logger.LogError("TwilioClient", $"failed sending sms to {number} - {ex.Message}", exception: ex);
            }
        }

        public void TestTlsProtocol()
        {
            TwilioClient.ValidateSslCertificate();
        }
    }

[TestFixture]
    public class Tests
    {
        public string _twilioUser;
        public string _twilioSmsNumber;
        public string _twilioPassword;
        public Integration.Twilio.Client _client;

        [OneTimeSetUp]
        public void Setup()
        {
            _twilioUser = GetConfiguration("Integration.Twilio.User");
            _twilioSmsNumber = GetConfiguration("Integration.Twilio.SmsNumber");
            _twilioPassword = GetConfiguration("Integration.Twilio.Password");
            _client = new Integration.Twilio.Client(_twilioUser, _twilioPassword);
        }

        [Test]
        public void TestSmsTlsSupport()
        {
            Console.WriteLine(System.Net.ServicePointManager.SecurityProtocol);
            Assert.That(() => _client.TestTlsProtocol(), Throws.TypeOf<Exception>());
        }

        private string GetConfiguration(string key)
        {
            if (!String.IsNullOrWhiteSpace(TestContext.Parameters[key]))
            {
                return TestContext.Parameters[key].ToString();
            }
            else
            {
                throw new Exception($"{key} param is missing");
            }
        }
    }

### Exception/Log
```
<place exception/log here>
```

### Steps to Reproduce
1. run the test in a .net 4.5.* framework which only support Ssl3 | Tls expecting to get an exception, non is thrown
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by imthepitts** [comment]
Hi @guya1976,

If you're trying to test a TLSv1.2 connection failure, your test is not passing because the REST API validation endpoint on port 8443 is still configured to allow TLS versions 1.0 and 1.1. You can test for 1.2 failures after August 15 when we enable the new security settings.

Additional details:
https://support.twilio.com/hc/en-us/articles/360003316334-Twilio-root-certificate-change-and-deprecation-of-TLS-v1-0-v1-1

Please contact our Support Team if you have additional questions:
https://www.twilio.com/help/contact 

Zack
