### ISSUE TITLE
Twilio Security Changes Support

### ISSUE THREAD

**Issue by leticiatech** [twilio/twilio-csharp#439]
Hi!
Besides using the code to test the validation of certificate with testing port 8443.
Is there any guarantee from your part, that ensures this package will work correctly after the Twilio security changes are launched the 15th of August? Is this being handled and supported properly?

**Comment by imthepitts** [comment]
Hi @leticiatech,

Thanks for checking with us. Our engineering team has verified the helper library works correctly with the upcoming changes. The scope of the August 15 change is just updating the root certificate from thawte to DigiCert. So as long as you have a standard bundle of CA certs installed in your local trust store (which you probably do), you're all set.

Please contact our support team if you have further questions or run into any issues testing port 8443.
https://www.twilio.com/help/contact 

Zack
