### ISSUE TITLE
RequestValidator.IsValidRequest takes port into account but URL used for X-Twilio-Signature does not

### ISSUE THREAD

**Issue by MikeJansen** [twilio/twilio-csharp#44]
I am working with my development server right now which is on a non-standard port.  The default implementation of RequestValidator.IsValidRequest() does not work because it is using the full URL including the port, but it appears the Twilio's server-side computation of X-Twilio-Signature does not.

I think the best thing would be to fix the server-side, but another option is to change RequestValidator.IsValidRequest.

This is my work-around (which also verifies that server-side does not take into account the port, because it works with this):

```
        private string GetUrlWithoutPort()
        {
            Uri uri = System.Web.HttpContext.Current.Request.Url;
            string urlWithoutPort = string.Format("{0}://{1}{2}", uri.Scheme, uri.Host, uri.PathAndQuery);
            return urlWithoutPort;
        }

        private bool IsValidRequest()
        {
            return new RequestValidator().IsValidRequest(System.Web.HttpContext.Current, TwilioAuthToken, GetUrlWithoutPort());
        }
```

**Comment by MikeJansen** [comment]
Looks like this may have been fixed on the server side to include the port.  Can anyone confirm this?

**Comment by MikeJansen** [comment]
The only reason I know is that my hack stopped working :)  Adding the port back in (actually, just not passing the url parameter) made it work again.

**Comment by MikeJansen** [comment]
On the server-side, it appears that maybe some calls include the port and some don't.

My new hack accounts for both:

```
        protected bool IsValidRequest()
        {
            System.Web.HttpContext context = System.Web.HttpContext.Current;
            RequestValidator validator = new RequestValidator();

            // If either URL with port or without port succeeds, then it's valid
            // See https://github.com/twilio/twilio-csharp/issues/44
            return
                validator.IsValidRequest(context, AuthToken) ||
                validator.IsValidRequest(context, AuthToken,
                    context.Request.Url.GetUrlWithoutPort());
        }
```

**Comment by MikeJansen** [comment]
OK, I need to find where to submit this for the twilio server team but here's what I have:

Message status and Call status callbacks include the Port (if present) in the signature calculation.  Call handlers (the Url parameter) that return the TwiML do NOT include the Port in the signature calculation.  These are the only callbacks I have tested and verified.  So it seems the signature calculation is inconsistent across callbacks.

**Comment by MikeJansen** [comment]
I submitted a Twilio support ticket for this since the core issue is server-side.

**Comment by MikeJansen** [comment]
The ticket number is 810391

**Comment by MikeJansen** [comment]
I have forked the repo and am currently working on a fix.  Support confirmed this issue and pointed me to https://www.twilio.com/docs/api/security#notes:

> For voice calls over HTTP, Twilio will drop the username and password (if any) from the URL before computing the signature. For voice calls over HTTPS, Twilio will drop the username, password and port (if any) before computing the signature. This behavior will continue to be supported in the 2008-08-01 and 2010-04-01 versions of the API to ensure compatibility with existing code. We understand this behavior is inconsistent, and apologize for the inconvenience.

**Comment by MikeJansen** [comment]
I got the basic coding done for the change.  It's in the above commit.  I haven't tested it yet, but wanted to make it available in case others wanted to review it.

Support informed me this library is being sunsetted and will be replaced with a next generation library.  I'm including the commit for informational purposes.

**Comment by jingming** [comment]
@MikeJansen We updated the request validator in the latest version of the library. Please give that a try and let us know if you continue to see issues.
