### ISSUE TITLE
Twilio voice call back and messaging not working in production environment

### ISSUE THREAD

**Issue by abhadeshpande** [twilio/twilio-csharp#452]
Twilio voice call back and messaging not working only in production environment. It works in all other development, testing and stage environments. 
For troubleshooting, difference in firewall settings have been considered. But they are the same.
When trying to create a voice call back from TWILIO, the call is initiated but is not completed. YOu can see the call initiation in IIS logs. It's not logged in the TWILIO number logs when tracked from TWILIO number account. Same is the case for TWILIO messaging.

I am getting 500: Internal error.

*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:**

### Code Snippet
```csharp
# paste code here
```

### Exception/Log
```
<place exception/log here>
```

### Steps to Reproduce
1.
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by imthepitts** [comment]
Hi @abhadeshpande,

Sorry you're having trouble. Since this is affecting your production environment, please file an urgent ticket to our support team to investigate.

https://www.twilio.com/help/contact 

All the Best,
Zack

**Comment by abhadeshpande** [comment]
We have raised a ticket with Twilio. But we are yet to find a solution. Actually I was about to edit ticket with more details.

**Comment by abhadeshpande** [comment]
Can I reopen this ticket with details - 
It gives Connection error to Call.json.
You can reach api.twilio.com from the server.

**Comment by imthepitts** [comment]
@abhadeshpande please continue working with the Support team. GitHub issues are for bugs in the helper library, not for troubleshooting production issues specific to your server/network environment.

I recommend reviewing this article for common issues and troubleshooting tips:

https://support.twilio.com/hc/en-us/articles/360007130274-Requirements-for-Connecting-to-the-Twilio-REST-API-and-Troubleshooting-Common-Issues  

All the Best,
Zack
