### ISSUE TITLE
Increase duration time of the voice call

### ISSUE THREAD

**Issue by ashishsharma30** [twilio/twilio-csharp#457]
Hello Guys (@imthepitts , @kwhinnery , @philnash , @minddog , @ajtack , @andrewryno )

I've got an issue or question when I launch a call than during call its auto disconnected after 5min.
I used timelimit keyword in my code but still its disconnect after 5min.
Here my code:

===============================================================

`<?xml version="1.0" encoding="UTF-8" ?>
<Response>
    <Say voice="alice" language="en" >Please wait while we connect you to the customer.</Say>
    <Dial callerId="+121381036***" timeout="15" timeLimit="1740">
        <Client statusCallback="*********"  statusCallbackMethod="POST" statusCallbackEvent="initiated ringing answered completed">
            customer_87316
        </Client>
    </Dial>
    <Redirect>*************</Redirect>
</Response>
`

===============================================================

I want to maximum call duration 30min, can you please suggest me or help me what I do ???

**Comment by imthepitts** [comment]
Hi @ashishsharma30,

Sorry you're having trouble. A 5-minute disconnect sounds like the timer built into our platform that automatically ends calls when no audio packets are received from one of the participants. Please submit a ticket to our Support team with an example Call SID so they can investigate further.

https://www.twilio.com/help/contact

All the Best,

Zack
