### ISSUE TITLE
How to retrieve active phone numbers from my Account using twilio-csharp API

### ISSUE THREAD

**Issue by deepumi** [twilio/twilio-csharp#458]
Hi Team,

I am trying to use Twilio-Csharp library to pull my active numbers from my Twilio account. I already have multiple numbers listed on my account. 

How do I get my active numbers via API?

May I know what APIs I should try.

```csharp

TwilioClient.Init(accountSid, authToken);

var account = AccountResource.Fetch(pathSid: accountSid);
```

I see all information when I execute the above line of code, 
Also, I tried account.SubresourceUris to make manual REST calls, I see all info except my active numbers.

Do you have any specific endpoint or API which returns the active phone numbers?

Appreciate your support.

Thank you
Deepu

**Comment by mplacona** [comment]
Hey @deepumi, the resource you want to use for this is the `IncomingPhoneNumberResource` as you can read about in [this link](https://www.twilio.com/docs/phone-numbers/api/incoming-phone-numbers?code-sample=code-list-all-incomingphonenumber-of-your-account&code-language=C%23&code-sdk-version=5.x).

Here are some changes to your code to get you going in the right direction.

```
TwilioClient.Init(accountSid, authToken);

var incomingPhoneNumbers = IncomingPhoneNumberResource.Read();

foreach(var record in incomingPhoneNumbers)
{
    Console.WriteLine(record.PhoneNumber);
}
```

Hope this helps you out!

**Comment by dsghi** [comment]
There is an example of listing all phone numbers in the API documentation: https://www.twilio.com/docs/phone-numbers/api/incoming-phone-numbers?code-sample=code-get-an-incomingphonenumber&code-language=C%23&code-sdk-version=5.x#linkcode
________________________________

Derek Gabriel | Cofounder & CEO
Ignite Solutions Group | 91-110 Hanua Street, Suite 204, Kapolei, HI 96707
808.450.2693 x101808.492.9947https://derekgabriel.me
 Simplify your IT.
​Lower your costs.
​Stay in control.
  Schedule a free Office 365
​consultation to get started.​
Click to Schedule

**Comment by deepumi** [comment]
Thank you everyone for quick response to my thread!

When I try the above code using Customer SID (via connect app), It does not return any phone number.

Does the above APIs can use for getting customer phone number as well?

https://www.twilio.com/docs/iam/connect/quickstart/csharp

![image](https://user-images.githubusercontent.com/554039/49666949-83ff1100-fa27-11e8-8d58-bca704df7244.png)

**Comment by mplacona** [comment]
Are the numbers you're trying to list for sure under that account SID? Can you see them if you login in?

**Comment by deepumi** [comment]
This one I am talking about our customer's account. The SID I passed as Customer SID which they have authorized via our connect App in Twilio.

Yes, If I login using our customer credentials I can see they have purchased a new phone number.

**Comment by deepumi** [comment]
@mplacona  - Should I open a new issue for getting customer active phone number?

**Comment by imthepitts** [comment]
Hi @deepumi, 

For questions about how to use the helper library or Twilio's APIs in general, your best option is to contact our Developer Support team at https://www.twilio.com/help/contact.

All the Best,
Zack

**Comment by deepumi** [comment]
Thanks @imthepitts.

Submitted ticket.

**Comment by deepumi** [comment]
@imthepitts, @mplacona

It's been almost 5 days I am working with support team @ twilio And I have not got any solution yet. 
I have shared all the information about my account and sub account.

Twilio ticket # - 1613141

Appreciate if you could shed some light on this issue.

Thank you
Deepu
