### ISSUE TITLE
Naming is inconsistent

### ISSUE THREAD

**Issue by kevinburke** [twilio/twilio-csharp#46]
Some of the naming in the library is inconsistent. For example: 

* the ListResource() method usually gives the name of the resource, so Calls -> ListCalls etc. However with Accounts, the resource translates to ListSubAccounts. 
* most of the ResourceOptions() classes map directly to the class name, but the Options class for IncomingPhoneNumbers is called PhoneNumberOptions, not IncomingPhoneNumberOptions.
* the Participants resource is referred to as ListConferenceParticipants, and MuteConferenceParticipant etc but the actual resource name is Participant, and the object that comes back is a Participant list, not a ConferenceParticipant list. Either it should be a ConferenceParticipant object or QueueMembers should be just Members, but it shouldn't be either way.
* The List etc methods for SMS Messages refer to ListSmsMessages, SendSmsMessage etc but the actual class name is SMSMessage.

Recommended changes:

* Rename ListSubAccounts to ListAccounts, or provide an extra method mapping to this behind the scenes.
* Add an IncomingPhoneNumberOptions class with the same arguments
* Change ListConferenceParticipants etc to be just Participants instead of ConferenceParticipants.
* Be consistent with naming SmsMessages or SMSMessages.

**Comment by carlosdp** [comment]
This is in progress, going to close this ticket to try and clean up the issue log.
