### ISSUE TITLE
105.2.3.0 Restsharp error

### ISSUE THREAD

**Issue by alicankablan** [twilio/twilio-csharp#460]
'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null' 

   location: Twilio.TwilioClient..ctor(String accountSid, String authToken, String accountResourceSid, String apiVersion, String baseUrl)
   location: Twilio.TwilioRestClient..ctor(String accountSid, String authToken, String accountResourceSid) C:\projects\twilio-csharp\src\Twilio.Api\Core.cs içinde: satır 182
   location: Twilio.TwilioRestClient..ctor(String accountSid, String authToken) C:\projects\twilio-csharp\src\Twilio.Api\Core.cs içinde: satır 152
   location: Sport.DataAccess.IdentitySmsService.SmsService.SendAsync(IdentityMessage message) C:\Users\Mustafa\source\repos\SportDunyasi\Sport.DataAccess\IdentitySmsService\SmsService.cs

FusionLog

=== Pre-bind status information ===
GNLK: DisplayName = RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
Call-out integrated code: Twilio.Api, Version=3.4.1.0, Culture=neutral,

**Comment by jnyrup** [comment]
Do you have a newer RestSharp 106.0.0 or newer installed?
From 106.0.0 RestSharp is stongly named.

I "solved" the problem by upgrading Twilio to v5 which does not depend on RestSharp.

**Comment by jdaigle7** [comment]
We updated to twilio 5.33.0 and even though the nuget Manager doesnt show RestSharp as a dependency, it still appears to hit the error in the code when trying to use the Twilio RestAPI. 

Is the newest version of Twilio REST API helper library supposed to be still referencing the RestSharp DLL?

**Comment by jnyrup** [comment]
@jdaigle7 Can you share a stack trace that shows your problem or even better a small project that reproduces it?
I can't find *any* references to RestSharp i twilio 5.33.
