### ISSUE TITLE
Support TLS1.2 gracefully

### ISSUE THREAD

**Issue by adam-therapynotes** [twilio/twilio-csharp#461]
**Version:** 5.9.4 (in production, but verified this exists in the current version)

### Steps to Reproduce
1. Make any request to the Twilio API
2. TLS1.1 is used

### Feature Request

We'd like to request builds targeting .NET 4.7.1 or later, in order that we meet the Twilio requirement to update to TLS1.2 without unnecessary workarounds or consequences.

Twilio will require all API connections use TLS1.2 by June 2019.  However, this library uses TLS1.1 to make API requests.  This is due to the library being built against .NET 4.5.1, which uses TLS1.1 by default. There are a number of workarounds that we can do without changes to this library, but they don't work for various reasons (based on official MS docs at https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls ):

- We could set `ServicePointManager.SecurityProtocol = Tls12`.  This works, but it affects the entire application, instead of this library.  This breaks any other API calls to other vendors if those API do not support TLS1.2, and prevents all API calls from individually floating up to TLS1.3 as it becomes available from each vendor.  It also creates a future maintenance task to remove this code.  Using `ServicePointManager.SecurityProtocol = SystemDefault` causes .NET 4.5.1 to use TLS1.1 instead of TLS1.2, so we have to force exactly TLS1.2 across our entire stack if we make this change.
- We could set the `SchUseStrongCrypto` and `SystemDefaultTlsVersions` registry keys per the linked article.  This works perfectly, except that it isn't compatible with our Azure Web App hosting - it is only possible when you control the whole underlying machine.  Additionally, our ops team considers this kind of registry manipulation to be unnecessarily risky for side effects and strongly prefers we don't require things like this when possible.
- Or, if this library provides a .NET 4.7.1 (or later) build, TLS1.2 will automatically be used because .NET 4.7.1 makes TLS1.2 (or TLS1.3 when available on both ends) the default.

If this library can offer a .NET 4.7.1 build prior to June, we could avoid risky changes or possibly having to fork this library.  Additionally, customers who aren't paying attention to the Twilio change to TLS1.2 - but who regularly update from NuGet or elsewhere - would automatically change to TLS1.2 because of this. 
 This would avoid a possible outage for these customers, and a loss of business or support cost to Twilio that would result.

**Comment by dprothero** [comment]
Thanks for the suggestion, @adam-therapynotes. My testing shows that this shouldn't be necessary. If you use the Twilio .NET helper library as-is in a .NET 4.7.1 project, the TLS 1.2 connection succeeds without any special code or registry settings. To confirm this, I put together this test repository:

https://github.com/TwilioDevEd/dotnet-tls-tests

Let me know what you think.

**Comment by adam-therapynotes** [comment]
OK, I can see a difference.  When we added from NuGet, it created this packages.config entry:

`<package id="Twilio" version="5.9.4" targetFramework="net462" />`

When you did it, this entry was created:

`<package id="Twilio" version="5.24.1" targetFramework="net471" />`

At this time I'm not completely sure why that happened, but I'll bet that change in targeting causes the different behavior.  We should be able to use that to fix on our end.  I'll update if I can find any reason why that might be happening, but I think it at least points the way to a solution.

**Comment by carentsen** [comment]
To avoid forcing TLS 1.2 on the entire application, maybe just allowing the security protocol to use 1.2 could be enough? 
Something like `ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;`?
