### ISSUE TITLE
MessagingResponse object no longer working with latest c# helper library

### ISSUE THREAD

**Issue by mnoreen** [twilio/twilio-csharp#465]
I have a webhook set up to call a custom URL on our website.  I know the webhook is working "as intended" as I can log the Request coming in (message SID and body and all that good stuff). At the end, we have code to instantiate a MessagingResponse object to send back a confirmation text that the message was received. 

After upgrading the latest c# helper library (5.25.1 and all its dependencies...), this is no longer working.  It's pretty simple A/B test.  Before the upgrade it worked, after the upgrade of DLLs it no longer worked.

I don't get a SMS message on my phone nor do I see an Outgoing API record on the SMS logs page when I'm logged into my project on Twilio.com (whereas I do see the test message I've sent to our number as an Incoming message).

There is no error or exception either.

### Code Snippet
 
// custom logging method here:  "About to send MessagingResponse"
 string responseTxt = "TESTING:  Got it.  Thanks.";
 var smsResponse = new MessagingResponse();
 var smsMsg = smsResponse.Message(responseTxt);
 response.Write(smsMsg);
// custom logging method here:  "after MessagingResponse:  " + smsMsg

### Steps to Reproduce
1.  Send SMS text message to one of our registered numbers
2.  Registered Number is set up with a webhook to post to a custom URL on our website
3.  Run test before upgrade, a return text message is received
4.  Run test after upgrade, no return text message is received

**Comment by mnoreen** [comment]
First, I am upgrade from 5.6.

Second, there's nothing to debug really.  There's just no result, no action, no exception, no error, no anything as a result of instantiating the MessagingResponse object and doing a response.write with it.  It worked under 5.6, doesn't work under 5.25.1.  I think the code snippet is pretty simple.

I'm open to refactoring, but its hard to find out where that's documented.  I have seen documentation that uses the MessagingResponse object just as I have.

**Comment by thinkingserious** [comment]
Hello @mnoreen,

Are you still experiencing this issue in the latest version of this helper library?

With best regards,

Elmer

**Comment by mnoreen** [comment]
@thinkingserious honestly, that was so many months ago... we came up with a workaround, essentially creating a brand new MessageResource and sending it to the "from" number we parsed off the incoming message... and haven't gone back to try it over.  

Unfortunately, in the past, every time we pull down the latest Twilio DLL, we have found it's a day or two project to get things figured out (is there a breaking change, like this one, deal with the Newtonsoft dependency issue, etc.).  So once we get back to a "stable" situation, we're inclined to leave it alone.

**Comment by childish-sambino** [comment]
Pretty sure this is a result of the changes made to `ToString` in that `MessagingResponse` used to override the default implementation and the base class `TwiMl` no longer does (it takes an optional argument). Think this can be resolved by explicitly calling `ToString()` (e.g., `response.Write(smsMsg.ToString());`

Closing since it's no longer an issue for the OP.
