### ISSUE TITLE
SMS c# Authentication Error - No credentials provided

### ISSUE THREAD

**Issue by ashishampl** [twilio/twilio-csharp#467]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:** 5.0.0

### Code Snippet
```csharp
const string accountSid = "ACxxx";
            const string authToken = "xxxx";
            TwilioClient.Init(accountSid, authToken);


            var messageOptions = new CreateMessageOptions(
            new PhoneNumber("+1905xxxxxxx"));
            messageOptions.From = new PhoneNumber("+1647xxxxxxx");
            messageOptions.Body = "Hi from App";
            var message = MessageResource.Create(messageOptions); 
```

### Exception/Log
[ApiException: Authentication Error - No credentials provided]
   Twilio.Clients.TwilioRestClient.ProcessResponse(Response response) +237
   Twilio.Clients.TwilioRestClient.Request(Request request) +51
   Twilio.Rest.Api.V2010.Account.MessageResource.Create(CreateMessageOptions options, ITwilioRestClient client) +40

**Comment by soso-maitha** [comment]
maybe you are using a web proxy in your company. I tried the following code in Web.config and it resolved the issue for me.
```
  <system.net>
    <defaultProxy useDefaultCredentials="true" >
    </defaultProxy>
  </system.net>
```

regards,

**Comment by thinkingserious** [comment]
Hello @ashishampl,

Thanks for taking the time to report this issue! Have you tried @soso-maitha's proposed solution?

@soso-maitha,

Thanks for helping out!

With best regards,

Elmer

**Comment by amd989** [comment]
I'm seeing the same problem with the Fax operation.

While running the example code:

```     const string accountSid = "ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        const string authToken = "your_auth_token";

        TwilioClient.Init(accountSid, authToken);

        var fax = FaxResource.Create(
            from: "+15017122661",
            to: "+15558675310",
            mediaUrl: new Uri("https://www.twilio.com/docs/documents/25/justthefaxmaam.pdf")
        );

        Console.WriteLine(fax.Sid);
```
The first calls fails, with
`{"code": 20003, "detail": "Your AccountSid or AuthToken was incorrect.", "message": "Authentication Error - No credentials provided", "more_info": "https://www.twilio.com/docs/errors/20003", "status": 401}`

However if you retry that call again (through retry pattern, queue retry, etc) the call succeeds...

While comparing both request made to Twilio, (the one that failed and the one that succeeded) you can tell, the first request is setting a cookie that the next request uses to authenticate.

Response of failed request:
```
HTTP/1.1 401 UNAUTHORIZED
[...]
WWW-Authenticate: Basic realm="flask-restful"
Set-Cookie: BCSI-CS-257c498afXXXXXXX=1; Path=/
```

Retry Request:
```
POST https://fax.twilio.com/v1/Faxes HTTP/1.1
[...]
Cookie: BCSI-CS-257c498afXXXXXXX=1
```
This is extremely sneaky as its not detailed anywhere. Am I missing some piece of information here?

**Comment by childish-sambino** [comment]
@amd989 Have you tried the answer above? https://github.com/twilio/twilio-csharp/issues/467#issuecomment-486073936

Guessing there's a proxy that's adding the cookie as there's nothing in this client library that would do this.
