### ISSUE TITLE
Twilio.Exceptions.ApiException: Upgrade Required following the Release of 5.28.0

### ISSUE THREAD

**Issue by trmatt** [twilio/twilio-csharp#472]
**EDIT: The persistent upgrade exception appears to have been related to a cached DLL. Things are back to normal. The outstanding question is how can users of the library receive advanced notification of breaking changes?** 

**Version: 5.28.0 (previously 5.9.0)**

We use the CSharp Twilio library for Programmable Faxing, and this morning, we started seeing "Upgrade Required" exceptions (presumably due to the breaking changes in the API portion of the library).

To resolve the changes, we pulled the latest library, and rebuilt the affected projects. We deployed the fresh binaries, and are still receiving the "Upgrade Required" exception (after restarting the associate Application Pools).

What else can we try to resolve this issue?

(Furthermore, short of watching the GitHub repo for releases, and finding out after the fact (via Exceptions), how can we avoid surprises in future releases?)

### Exception/Log
```
Twilio.Exceptions.ApiException: Upgrade Required
   at Twilio.Clients.TwilioRestClient.ProcessResponse(Response response)
   at Twilio.Clients.TwilioRestClient.<RequestAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Twilio.Rest.Fax.V1.FaxResource.<CreateAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Twilio.Rest.Fax.V1.FaxResource.<CreateAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TruckRight.Tools.Faxing.ConcreteFaxProviders.TwilioFaxProvider.<Send>d__6.MoveNext()
```

**Comment by trmatt** [comment]
Posting an update based on feedback received from Twilio Support.

The issue may have been related to upcoming security updates (TLS and ciphers) slated for June 2019.

**Notice: Twilio REST API’s TLS and Cipher Suite Security Changes for June 2019**

https://support.twilio.com/hc/en-us/articles/360007724794-Notice-Twilio-REST-API-s-TLS-and-Cipher-Suite-Security-Changes-for-June-2019

There is a REST status test endpoint to monitor for upcoming changes too...

**Monitoring Updates to Twilio REST API Security Settings**

https://support.twilio.com/hc/en-us/articles/226478767-Monitoring-Updates-to-Twilio-REST-API-Security-Settings

Additionally, I became aware of the "Subscribe to Updates" button on the Twilio Status page (https://status.twilio.com/).

**Comment by adamreed90** [comment]
This has broken my application as well, latest NuGet package: 

Twilio.Exceptions.ApiException: 'Upgrade Required'

**Comment by adamreed90** [comment]
I was able to resolve this by setting : 

ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072; //TLS 1.2

in the start of my application.

**Comment by palashmon** [comment]
As per their [**docs**](https://support.twilio.com/hc/en-us/articles/360007724794-Notice-Twilio-REST-API-s-TLS-and-Cipher-Suite-Security-Changes-for-June-2019), Twilio APIs now requires TLS v1.2 and strong cipher suites.

To resolve this issue, before calling `MessageResource.Create()` we can add:

```csharp
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls 
	| SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12 | SecurityProtocolType.Ssl3;
```

**Comment by Matthiasclee** [comment]
When I put ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072; //TLS 1.2
in the start of my c# app, it does this:


Error	CS0103	The name 'ServicePointManager' does not exist in the current context	SMS	C:\Users\Administrator\source\repos\SMS\SMS\Program.cs	13	Active

**Comment by LuvForAirplanes** [comment]
> I was able to resolve this by setting :
> 
> ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072; //TLS 1.2
> 
> in the start of my application.

@adamreed90 Could you please define "start of my application" ??

**Comment by JTMcCarthy** [comment]
@Matthiasclee you need to include either a Using System.Net or format the line of code this way:             System.Net.ServicePointManager.SecurityProtocol = (System.Net.SecurityProtocolType)3072; //TLS 1.2
