### ISSUE TITLE
Add "speechModel" and "actionOnEmptyResult" attributes for the Gather verb

### ISSUE THREAD

**Issue by RNCRyan** [twilio/twilio-csharp#477]
### Feature Request
Hey, the "speechModel" and "actionOnEmptyResult" attributes (https://www.twilio.com/docs/voice/twiml/gather) are missing from the Gather verb in this repo.  Could support for those be added?  Thank you!

Ryan

**Comment by childish-sambino** [comment]
These attributes are missing in the upstream API definition that we build off of. They should be added in the next release which is scheduled for next week.

**Comment by childish-sambino** [comment]
Wasn't able to make it into the latest release. Will keep you updated here.

**Comment by thinkingserious** [comment]
Hello @RNCRyan,

It looks like the `actionOnEmptyResult` has been added, but not the `speechModel` just yet.

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by childish-sambino** [comment]
Added as part of the [5.37.2](https://github.com/twilio/twilio-csharp/releases/tag/5.37.2) release.
