### ISSUE TITLE
Csharp library appears to generate invalid xml for say-as

### ISSUE THREAD

**Issue by ksmith173** [twilio/twilio-csharp#479]
**Version: 5.28.4**

Csharp library appears to generate invalid xml for say-as.

### Code Snippet
```csharp
var response = new VoiceResponse();
 var say = new Say("This is a test of AWS Polly. ", voice: "Polly.Joanna");
say.SsmlSayAs("5/17/2019", SsmlSayAs.InterpretAsEnum.Date, SsmlSayAs.RoleEnum.Mdy);
response.Append(say);
var temp = response.ToString();
```

### Exception/Log
```
Warning - 13520
Say: Invalid text
The text of the Say verb was empty or un-parsable. See the Say Verb API Reference for more information.
```

### Steps to Reproduce
1. Create twiml via code snippet. 
2. Initiate call with twiml output.
3. Receive the above error in Twilio logs
4. Revise twiml snippet to use attribute "format" instead of "role" on the say-as element.
5. Initiate call.
6. Call works.

**Comment by eshanholtz** [comment]
This is not a change that can be made in the library. An internal ticket has been filed against the relevant product team.
