### ISSUE TITLE
No way to add existing SSML strings to SAY.

### ISSUE THREAD

**Issue by chriswelles** [twilio/twilio-csharp#483]
Version: 5.29.1

### Code Snippet
```csharp
(new Say("<speak>hello</speak>")).ToString()

"<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Say>&lt;speak&gt;hello&lt;/speak&gt;</Say>"

```
### Feature Request
Add a method to enable embedding arbitrary XML inside an Element.  AddText() has the same problem the above does.  I can't find anyway to embed custom XML via the TwiML helper libraries.

**Comment by dsghi** [comment]
You don't need to use SSML inside of Say to use Polly normally, you can just use the standard Say - Either set your default settings to use a Polly Voice from your Dashboard, or define it in code:

```c#
response.Say("Chapeau!", voice: "Polly.Celine", language: "fr-FR");
```

```xml
<Response>
   <Say voice="Polly.Celine" language="fr-FR">
      Chapeau!
   </Say>
</Response>
```
If you want to use SSML to add pronunciation values, etc. there is reference using the helper library here: https://www.twilio.com/docs/voice/twiml/say/text-speech#generating-ssml-via-helper-libraries

**Comment by chriswelles** [comment]
That's insufficient.  It implies custom Twilio Helper code for every phrase variation.  We have a whole series of collection of phrases that are already stored in SSML form.  We just can't use it reasonably because the helper libraries assume you don't have SSML to begin with.

Currently, it seems the only option is coding the full XML and skipping the helper libraries entirely.  Not the end of the world, but certainly not desirable.

**Comment by dsghi** [comment]
I'd argue that it's completely desirable. If you already have XML, you don't need the helper library, which main function is to generate the TwiML. XML manipulation it in your base framework will be far more efficient...

Also, I haven't seen an example of using SSML with TwiML that includes the `Speak` portion, only the pronunciation related items, so you may have trouble with just dumping SSML inside of TwiML - may want to test that first (if you haven't already).

You could look at `append()` for creating child elements and `addtext()`, they may allow you to accomplish what you want.

**Comment by chriswelles** [comment]
The only XML we already have is the SSML, so going the XML route will mean generating all the TwiML explicitly.  Any other developer that touches it won't be able to rely on the intellisense / guidance provided by the helper libraries.  The helper libraries should allow you to extend things rather than taking an all or none approach.

Regarding "<Speak>", you're correct about that being a concern.  We'd need to review everything and make sure it's all supported or adapt things so that they are supported.  We can do that.

**Comment by chriswelles** [comment]
FYI - the <speak> and various other SSML options work perfectly when embedded in the XML.  I had to convert the whole voiceResponse payload into an XDocument, navigate in and modify the Speak property, and then rework everything to pass the XML around rather than the TwiML object.  It's shouldn't be necessary to go through all that.

**Comment by thinkingserious** [comment]
Hello @chriswelles,

Thanks for taking the time to report this issue!

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by childish-sambino** [comment]
@chriswelles Would this suffice? (I'm not proposing a change to this library):

```
public class CustomXML : TwiML
{
    public string Body { get; set; }

    public CustomXML(string body) : base("")
    {
        this.Body = body;
    }
    override protected XNode ToXml()
    {
        return XElement.Parse(this.Body);
    }
}
```
Usage:
```
var say = new Say();
say.Append(new CustomXML("<speak>hello</speak>"));
```
