### ISSUE TITLE
MessageResource.Price has become a string in 5.30.0

### ISSUE THREAD

**Issue by chriswindram** [twilio/twilio-csharp#484]
In MessageResource, the Price property seems to have changed from Decimal? to String in 5.30.0.

I cannot find anything about this in the change notes. Before I look to change code, can I check that this is deliberate and a change that will remain?

**Comment by childish-sambino** [comment]
👀

**Comment by childish-sambino** [comment]
Yes, this was a deliberate change but not included in the release notes. I've updated the release notes.
