### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0

### ISSUE THREAD

**Issue by mnoreen** [twilio/twilio-csharp#486]
I'd like to start a fresh thread here as I believe this is still an "issue" for the Twilio c# library, and I continue to spend a lot of time trying to deal with it...  

I have a pretty simple .NET set up.  A web forms based website and a class library that the website references.  In the class library, among other common code, we have added Twilio and of course all its dependencies (using nuget).  Allowing nuget to pull down the "Highest" version (under Dependency Options), we now have NewtonSoft.Json v12.x (in this case 12.0.2).

Class lib compiles fine.  Web site "builds" fine, and by doing so, it adds the Twilio lib and all the dependencies into the website's Bin directory, as expected.

However, an exception is thrown when I actually run my code to send a text message (webpage.aspx => calls in to CommonClassLib method => calls Twilio's MessageResource.Create method).

`Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

Interestingly enough... the text message is actually sent ( I do get my test text on my phone!).  But the exception is thrown, so of course it "appears" there's an error...

The stack trace actually helps with that as the exception seems to come from a "ProcessResponse" method in the Twilio lib:

`at Twilio.Clients.TwilioRestClient.ProcessResponse(Response response) at Twilio.Clients.TwilioRestClient.Request(Request request) at Twilio.Rest.Api.V2010.Account.MessageResource.Create(CreateMessageOptions options, ITwilioRestClient client) at Twilio.Rest.Api.V2010.Account.MessageResource.Create(PhoneNumber to, String pathAccountSid, PhoneNumber from, String messagingServiceSid, String body, List`1 mediaUrl, Uri statusCallback, String applicationSid, Nullable`1 maxPrice, Nullable`1 provideFeedback, Nullable`1 validityPeriod, Nullable`1 forceDelivery, Nullable`1 smartEncoded, String interactiveData, Nullable`1 forceOptIn, ITwilioRestClient client) at `

The only solution I have found is downgrading the Newtonsoft.Json library to exactly v10.0.  I think this is a problem, as we would like to be using a later version.

Note, I have carefully rerun all my tests by uninstalling Twilio and its dependencies and removing ANY reference to any of these dlls (from the class lib and the website Bin directory).  Then nuget'd the latest Twilio (v 5.31.2) and its dependencies.

**Comment by thinkingserious** [comment]
Hello @mnoreen,

I believe should be able to redirect the assembly version for Newtonsoft [like so](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions).

Please try it out and let us know how it goes. Thanks!

With best regards,

Elmer

**Comment by mjanulaitis** [comment]
I am experiencing the same issue.  I have modified my app.config file to include the following section however in release mode the SMS text goes out then while handling the results I get the above error message.  In debug mode I do not receive the error.

  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="12.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>

**Comment by mjanulaitis** [comment]
I am receiving the same error but only in release mode.  I have updated all of my app.config files to include the following section to no avail:

`  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>`

**Comment by mnoreen** [comment]
@thinkingserious Thank you Elmer, as it so happens I know that you can do that, I've just struggled w/ the root cause of that, for a couple of reasons.

First, we use other library's that happened to depend on Newtonsoft as well, but none them end of up requiring the binding redirect.  They all seem to use whatever Newtsonsoft is already available in the project.

Second, and probably more "annoying", is that we have wrapped up our core SMS functionality in a helper class library that is, in turn, used by many dozens of console apps.  Suddenly every single one of those is littered with app.configs that didn't have them before, or if they did, now have these binding redirects added.  The litter and overall maintenance of that is not something we like to have to deal with

**Comment by mnoreen** [comment]
@thinkingserious As mentioned by a couple of people now... Those who have taken the time to clone the whole twilio repo and add it as project to their solution and manually compile it, etc, etc.... then it's NOT a problem.  So it seems to me to beg the question of why that works and now Twilio's provided library doesn't.

**Comment by mjanulaitis** [comment]
I like the old days where we versioned DLLs with numbers in the name so it was impossible to load the wrong version of a library.  I feel loading libraries then checking version numbers was an design and implementation mistake. If a library is not backwards compatible, then the file name should be changed.  Pretty simple stuff but that's not we have these days.

**Comment by MayaEverLogic** [comment]
We just encountered the same problem as mnoreen. Is this planning on being fixed? Downgrading to 10 is not an option as another 3rd party tool requires 12 in our software.

**Comment by dsghi** [comment]
This is something you can fix on your own, just look at your binding redirects...

**Comment by MayaEverLogic** [comment]
Is this the permanent fix going forward? We shouldn't have to distribute a config file to every one of our user's workstations.

**Comment by garrett4** [comment]
My fix for this was to create a new csproj file and import all the Twilio source. I was then able to choose whatever version of Newtonsoft we needed.

Also my visual studio didn't like the AssemblyInfomation class in the AssemblyInfo.cs file. It was causing the nuget package manager to hang sometimes. Removing it fixed nuget.

**Comment by thinkingserious** [comment]
Duplicates https://github.com/twilio/twilio-csharp/issues/422

**Comment by TurgutAcar** [comment]
gggg
