### ISSUE TITLE
Missing coach attribute on Conference object

### ISSUE THREAD

**Issue by Uriil** [twilio/twilio-csharp#487]
**Version**:  5.31.2

### Code Snippet
```csharp
var dial = new Dial();
dial.Conference("Snowy Owl 3",
                startConferenceOnEnter: true, 
                statusCallback: new Uri("https://hhhh.com/twilio/status/conference")
);
```

### Feature Request
Based on article [Agent Conference is now Generally Available](https://www.twilio.com/blog/2017/12/agent-conference-generally-available.html) _Dial_->_Conference_ TwiML should contain property _coach_, however I can find this property only on _Participant_ resource. Am I right that this part is missing? Or I misunderstand the API ?

**Comment by eshanholtz** [comment]
This is not a change that can be made in the library. An internal ticket has been filed against the relevant product team.

**Comment by childish-sambino** [comment]
The upstream TwiML definitions have been updated and this library will be updated in the next release to contain the `coach` attribute.
