### ISSUE TITLE
Question "InvalidSandboxRequest" whatsapp- message sending

### ISSUE THREAD

**Issue by SurielRuano** [twilio/twilio-csharp#488]
**Version: 5.31.2**

### Code Snippet
```csharp
  static void Main(string[] args)
        {

            // Find your Account Sid and Token at twilio.com/console
            // DANGER! This is insecure. See http://twil.io/secure
            const string accountSid = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
            const string authToken = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

            TwilioClient.Init(accountSid, authToken);

            var message = MessageResource.Create(
                body: "This is the ship that made the Kessel Run in fourteen parsecs?",
                from: new Twilio.Types.PhoneNumber("whatsapp:+1XXXXXXXXXX"),
             

                to: new Twilio.Types.PhoneNumber("whatsapp:+52XXXXXXXXXX")
            );

            Console.WriteLine(message.Sid);
            Console.ReadLine();
        }
```
My settings:
**accountSid:** I set my  twilio accountSid
**authToken:** I set my twilio authToken
**From:**  I set my twilio  sandbox number

**To:** I set my personal number

### Exception/Log
```
When I Run my project
The message status is "Queued"
And nothing happend :(

to track my message i set a callbackRequest on my project, I used an  Object SmsStatusCallbackRequest in my callback method request

And this is the response:

ChannelPrefix: "whatsapp"
ErrorCode: "InvalidSandboxRequest"
MesaggeStatus: "Failed"
```

### Steps to Reproduce
1. Install Twilio Package
2. Add settings
3. Add STATUS CALLBACK URL  in twilio Console
4. Run project

##
I don´t know whats happend

**I want send a proactive message to my personal number**

**Comment by dsghi** [comment]
Is the recipient number joined to the sandbox? There's a list of various things in the [Whatsapp FAQ ](https://www.twilio.com/docs/sms/whatsapp/best-practices-and-faqs) under "My outbound message from the Sandbox was not delivered. Why?"

**Comment by SurielRuano** [comment]
"My outbound message from the Sandbox was not delivered. Why"


Hello dsghi, thank you for answering, consult the FAQ you mention, according to the article there are 2 cases in which a whatsapp message is not sent:
- The first is that the recipient number is not registered in sandbox (in my case my phone number is already registered).
- The second is that the session of free whatsapp messages lasts only 24 hours after the last message (in my case the session is valid).

**Comment by dsghi** [comment]
In this case I would suggest contacting [Twilio support](https://support.twilio.com/hc/en-us) directly, it seems your issue lies on the sandbox side of the fence. It doesn't look like there's anything wrong with your code if the message is being successfully queued.

**Comment by SurielRuano** [comment]
> In this case I would suggest contacting [Twilio support](https://support.twilio.com/hc/en-us) directly, it seems your issue lies on the sandbox side of the fence. It doesn't look like there's anything wrong with your code if the message is being successfully queued.


I already sent a request for support to Twilio, if they help me I will feed back, thanks

**Comment by SurielRuano** [comment]
it was my mistake, my sandox session had already expired and in that case only approved template messages are sent
