### ISSUE TITLE
Infinite Paging of empty pages

### ISSUE THREAD

**Issue by systemundertestcode** [twilio/twilio-csharp#489]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:**
5.31.0

### Code Snippet
```csharp
 public static Page<T> FromJson(string recordKey, string json)
        {
            var root = JObject.Parse(json);
            var records = root[recordKey];
            var parsedRecords = records.Children().Select(
                record => JsonConvert.DeserializeObject<T>(record.ToString())
            ).ToList();

            var uriNode = root["uri"];
            if (uriNode != null)
            {
                JToken pageSize;
                JToken firstPageUri;
                JToken nextPageUri;
                JToken previousPageUri;

                // v2010 API
                var intPageSize = (root.TryGetValue("page_size", out pageSize) ? root["page_size"].Value<int>() : parsedRecords.Count);
                var pageNextPageUri = root.TryGetValue("next_page_uri", out nextPageUri) ? root["next_page_uri"].Value<string>() : null;
                // v2010 API

                //HACK: Hack for the page nexturi, should be null when there are no more pages of records
                if ((parsedRecords.Count < intPageSize || parsedRecords.Count == 0) && pageNextPageUri != null)
                {                    
                    throw new Exception($"Pager has less records than the pagesize, but the api has indicated there are more pages!!!" +
                                        $"parsedRecords.Count: {parsedRecords.Count}. pageSize: {pageSize}. " +
                                        $"pageNextPageUri: {pageNextPageUri}."  +
                                        $"recordKey: {recordKey}. " +
                                        $"json: {json}.");
                }

                return new Page<T>(
                    parsedRecords,
                    intPageSize,
                    uri: uriNode.Value<string>(),
                    firstPageUri: root.TryGetValue("first_page_uri", out firstPageUri) ? root["first_page_uri"].Value<string>() : null,
                    nextPageUri: pageNextPageUri,
                    previousPageUri: root.TryGetValue("previous_page_uri", out previousPageUri) ? root["previous_page_uri"].Value<string>() : null
                );
            }

            // next-gen API
            var meta = root["meta"];
            return new Page<T>(
                parsedRecords,
                meta["page_size"].Value<int>(),
                url: meta["url"].Value<string>(),
                firstPageUrl: meta["first_page_url"].Value<string>(),
                nextPageUrl: meta["next_page_url"].Value<string>(),
                previousPageUrl: meta["previous_page_url"].Value<string>()
            );
        }
```

### Exception/Log
```
<place exception/log here>
```

### Steps to Reproduce
1. Use ConferenceResource.ReadAsync to get a range of conferences. Set the pageSize of ReadAsync to a low number (like 1 / 2) (in fact any other even number will do, but setting it low will make the issue appear faster)

2. Enumerate the result of ConferenceResource.ReadAsync. This will cause the ResourceSet<T> to page in the conferences. If there are an even number of conferences, the iterator will continue paging forever.
(if you log your requests to the api you will see 
It does this because the API returns a page with 0 records, but with a populated NextPageUri
3. If you want: replace Twilio.Rest.Page.cs   static FromJson method with the code above. I've added an if statement to detect the issue and throw an exception:
```
 throw new Exception($"Pager has less records than the pagesize, but the api has indicated there are more pages!!!"
```

**Comment by thinkingserious** [comment]
Hello @systemundertestcode,

Thanks for taking the time to report this!

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by childish-sambino** [comment]
@systemundertestcode Is there a particular number of conferences this fails for, or does it just always fail with low/even page sizes? I'm not able to recreate this using any page size.

**Comment by systemundertestcode** [comment]
Hey,

This should fail for any number of conferences 
(just I found that the issue occurs faster if setting the page size low)

Now, this was happening in 5.31.0
ultimately I think the server was returning a page with zero records, but with  'next_page_uri' populated.    (which might have been fixed / changed over on twilios side?)

Im still using 5.31.0 here,  Ill see if I can recreate it today

**Comment by systemundertestcode** [comment]
I'm not able to reproduce it either.
it looks like next_page_uri is now coming back as null on the conference resource pager 
looks to me like its resolved.
(if there is anyway you can check the backend service that provides the conference page resources ... maybe there was some update there around the 6th of November)

Anyway, I guess you can close this issue....
(I can always re-open if we detect it again)

**Comment by childish-sambino** [comment]
Works for me.

Though I do recommend [filing a support ticket](https://twilio.com/help/contact) instead next time if you see this same issue. It's not something that should be solved in this library as it's a backend issue. Support will better be able to debug the issue then.
