### ISSUE TITLE
Linux with .net core 3.0 + OpenSSL 1.1.1 doesn't work

### ISSUE THREAD

**Issue by zalza13** [twilio/twilio-csharp#507]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:5.35.1**

### Code Snippet
```csharp
public SystemNetHttpClient(System.Net.Http.HttpClient httpClient = null)
        {
            _httpClient = httpClient ?? new System.Net.Http.HttpClient();
        }
```

### Exception/Log
```
Message: The SSL connection could not be established, see inner exception.",
"ExStackTrace":"   at Twilio.Clients.TwilioRestClient.Request(Request request)   
                   at Twilio.Rest.Api.V2010.Account.MessageResource.Create(CreateMessageOptions options, ITwilioRestClient client)
                   at Twilio.Rest.Api."
```

### Steps to Reproduce
1. Using the twilio client with .net core 3.0 on Linux with openssl 1.1.1
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

My solution for now was:

```
       public SystemNetHttpClient(System.Net.Http.HttpClient httpClient = null)
        {
            var handler = new HttpClientHandler
            {
                ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>
                {
                    if (errors == SslPolicyErrors.None)
                        return true;
                    else
                    {
                        Console.WriteLine("Twilio sslPolicyErrors {0}", errors);
                    }

                    return true;
                }
            };

            Console.WriteLine("SystemNetHttpClient::Creando el objeto _httpClient");

            //_httpClient = httpClient ?? new System.Net.Http.HttpClient();
            _httpClient = new System.Net.Http.HttpClient(handler);
        }
```

Thansk!

**Comment by programando-ideas** [comment]
Hi twilio team. Please check [this](https://github.com/dotnet/runtime/issues/662)

Thanks!!

**Comment by thinkingserious** [comment]
Hello @zalza13,

Could you please verify the specific version of OpenSSL you have installed with `openssl version`? Per @programando-ideas' link, it appears that there may an issue with version 1.1.1d vs. 1.1.1.

With best regards,

Elmer

**Comment by programando-ideas** [comment]
Hi @thinkingserious! The problem was with OpenSsl 1.1.1d. I did a downgrade to 1.1.1 and the problem was fixed.

In the future this version will be a problem.

Sorry about my English 🤓.
