### ISSUE TITLE
Twilio not working with System.IdentityModel.Tokens.Jwt 5.5.0

### ISSUE THREAD

**Issue by constantintaivan** [twilio/twilio-csharp#513]
### Issue Summary
Hello,

I've found that Twilio package 5.27.0 for net462 (even last one 5.38.0) it's not working with 
Microsoft.IdentityModel.Tokens, v5.5.0
System.IdentityModel.Tokens.Jwt, v5.5.0
The following exception is thrown:

### Exception/Log

{
  "ClassName": "System.IO.FileLoadException",
  "Message": "Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=5.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
  "Data": null,
  "InnerException": {
    "ClassName": "System.IO.FileLoadException",
    "Message": "Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=5.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": null,
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2146234304,
    "Source": null,
    "WatsonBuckets": null,
    "FileLoad_FileName": "System.IdentityModel.Tokens.Jwt, Version=5.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
    "FileLoad_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n"
  },

### Code
Above exception is thrown here: 
new Twilio.Jwt.AccessToken.Token(...).ToJwt();

If using 5.1.4 version for Microsoft.IdentityModel.Tokens and System.IdentityModel.Tokens.Jwt, no exception is thrown.

### Technical details:
* twilio-csharp version: 5.27.0/5.38.0
* csharp version: 7.1

Thank you
Regards

**Comment by thinkingserious** [comment]
Hello @constantintaivan,

I am currently working on a [similar issue](https://github.com/twilio/twilio-csharp/issues/422) for which a solution may also apply here. Note that on that thread there are several workarounds posted that may be worthwhile trying before #422 comes to a resolution.

With best regards,

Elmer

**Comment by childish-sambino** [comment]
I'll defer to the comment here for why this is happening: https://github.com/twilio/twilio-csharp/issues/431#issuecomment-421478157

High-level, binding redirects are required to avoid this issue and VS is able to help out. I don't see anything we can/should do in this repo to alleviate the issue as it's core to .NET
