### ISSUE TITLE
Mocking the API?

### ISSUE THREAD

**Issue by rschiefer** [twilio/twilio-csharp#518]
Do you have any good examples of how to mock the API usage?

The static nature of the examples don't naturally lend to easy testing/mocking.

**Comment by JosephIaquinto** [comment]
I would try implementing a mock of ITwilioRestClient. See #268 for further discussion.

**Comment by thinkingserious** [comment]
Thanks for helping out @JosephIaquinto!

@rschiefer,

Please re-open if you require further assistance, thanks for reaching out!

You may also want to investigate utilizing the [prism mock server](https://stoplight.io/open-source/prism/) utilizing our developing OpenAPI spec - [see the .json files here](https://github.com/twilio/twilio-cli-core/tree/master/src/services/twilio-api). We don't have a working example just yet, however.

With best regards,

Elmer
