### ISSUE TITLE
RequestValidator

### ISSUE THREAD

**Issue by chriswelles** [twilio/twilio-csharp#522]
### Issue Summary
requestValidator.Validate doesn't work when the hostname in the URL has any uppercase letters.  The change introduced with https://github.com/twilio/twilio-csharp/pull/492 breaks things.

The change introduces the use of URIBuilder to add and remove the port from the URL.  Unfortunately, that technique also lowercases the hostname.  The actual signature in the payload is against the hostname in the originally specified case, so signature validation fails if the hostname has any uppercase letters.

### Steps to Reproduce
Validate a request using a callback URL with any uppercase letters in the hostname.

### Code Snippet
```csharp
	var uri = new UriBuilder("http://MixedCaseUrl/");
	uri.Port = -1;
	string result = uri.ToString();
	// result is "http://mixedcaseurl".
	// It's been lowercased.
```

### Technical details:
* twilio-csharp version: 5.38.0
* csharp version: .NET Core 3.1

**Comment by eshanholtz** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.
