### ISSUE TITLE
Cannot filter calls by more than one date

### ISSUE THREAD

**Issue by kevinburke** [twilio/twilio-csharp#53]
It's impossible to retrieve calls that started before a certain date and after another, for example:

```
GET /2010-04-01/Accounts/AC123/Calls?StartTime>=2012-04-01&StartTime<=2012-04-30
```

The CallListRequest only allows you to input one StartTime or EndTime with one comparison.

**Comment by jingming** [comment]
This functionality is supported in `5.0.0` here: https://github.com/twilio/twilio-csharp/blob/master/src/Twilio/Rest/Api/V2010/Account/CallOptions.cs
