### ISSUE TITLE
Method not found: 'System.String[] System.String.Split(Char, System.StringSplitOptions)'

### ISSUE THREAD

**Issue by glittle** [twilio/twilio-csharp#536]
### Issue Summary
This .NETFramework nuget package was updated today and now breaks.

The stack trace is:
```
at Twilio.Http.Request.buildUri()
at Twilio.Http.Request.ConstructUrl()
at Twilio.Clients.TwilioRestClient.Request(Request request)
at Twilio.Rest.Api.V2010.Account.MessageResource.Create(CreateMessageOptions options, ITwilioRestClient client)
at Twilio.Rest.Api.V2010.Account.MessageResource.Create(PhoneNumber to, String pathAccountSid, PhoneNumber from, String messagingServiceSid, String body, List1 mediaUrl, Uri statusCallback, String applicationSid, Nullable1 maxPrice, Nullable1 provideFeedback, Nullable1 attempt, Nullable1 validityPeriod, Nullable1 forceDelivery, ContentRetentionEnum contentRetention, AddressRetentionEnum addressRetention, Nullable1 smartEncoded, List1 persistentAction, ITwilioRestClient client)
```

The old line had:
`string[] strArray = uriBuilder.Host.Split('.');`

The new line has:
`string[] strArray = uriBuilder.Host.Split('.', StringSplitOptions.None);`

### Technical details:
* twilio-csharp version: 5.46.1
* csharp version: .NET Framework 4.8  (same error on 4.6.1)

**Comment by thinkingserious** [comment]
Hello @glittle,

Thanks for taking the time to report this to us!

Could you please provide example code that is triggering this break so that we may try and reproduce? 

Looking at the [source](https://github.com/twilio/twilio-csharp/blob/main/src/Twilio/Http/Request.cs#L118), I don't see the change you have mentioned. 

With best regards,

Elmer

**Comment by joshsacks** [comment]
I'm having this issue too and seeing the change in the decompiled code. This is probably due to your build server having a greater version of .NET than the ostensible target (4.5.1) so the wrong overload is being called.

This is what it is now (5.46.1):
![image](https://user-images.githubusercontent.com/11070846/92086655-7a3f4480-ed98-11ea-92a8-df2b8b1f6bdb.png)

This is what is was in 5.46.0:
![image](https://user-images.githubusercontent.com/11070846/92086821-b5417800-ed98-11ea-864e-d50838fc2990.png)

**Comment by childish-sambino** [comment]
@asheroto Can you not use version 5.46.0 in the mean time?

**Comment by glittle** [comment]
@childish-sambino Yes, that's the only option for now. I've downgraded to 5.46.0 and it is working fine.

**Comment by glittle** [comment]
> Could you please provide example code that is triggering this break so that we may try and reproduce?

I don't think it is helpful, but here's the line in my code that is breaking:
```
        var messageResource = MessageResource.Create(
          body: message,
          from: new PhoneNumber(fromNumber),
          to: new PhoneNumber(number),
          provideFeedback: true
          );

```
For context:
```
using Twilio;
using Twilio.Rest.Api.V2010.Account;
using Twilio.Rest.Api.V2010.Account.Message;
using Twilio.Types;

```

**Comment by joshsacks** [comment]
It's easiest to test with TwilioClient.ValidateSslCertificate(). I'm having the issue on .NET Framework 4.7.2....please test with that as your startup project framework.

**Comment by gtwilliams03** [comment]
Same issue with 5.46.1.  Rolling back to 5.46.0 is fine. Happens with a simple call to MessageResource.Create.

**Comment by ssa3512** [comment]
We are using a similar set of code for SMS that is also failing with 5.46.1:

```cs
using Twilio;
using Twilio.Rest.Api.V2010.Account;
using Twilio.Types;
```

```cs
TwilioClient.Init(accountSid, authToken);

var fromPhoneNumber = new PhoneNumber(fromMobileNumber);
var toPhoneNumber = new PhoneNumber($"+1{toMobileNumber.StripNonNumeric()}");

var message = MessageResource.Create(body: messageBody, from: fromPhoneNumber, to: toPhoneNumber);
```

**Comment by asheroto** [comment]
> @asheroto Can you not use version 5.46.0 in the mean time?

Indeed, thanks for that.  Working with 5.46.0

**Comment by jusantana** [comment]
I'm having the same issue with SessionResource.CreateAsync

**Comment by childish-sambino** [comment]
Sounds similar to this issue but there's been no response: https://stackoverflow.com/questions/56799673/is-the-string-split-method-broken-in-mono-5-20-1-on-windows-os

Attempting to remove mono from the build pipeline and release a new version.

**Comment by childish-sambino** [comment]
Looks to be resolved now. I'm no longer able to recreate the issue using .NET Framework.

**Comment by vpshonyak** [comment]
The same error in version 5.54.0. Needed to downgrade to 5.53.1

Error: "Method not found: 'System.String[] System.String.Split(Char, System.StringSplitOptions)'"
When calling: MessageResource.Create( ...

**Comment by SandeepReddyPinniti** [comment]
Hi,

I'm encountering the same issue after upgrading Twilio to 5.54.0. Below is the code where I'm encountering this error.

 var query = QueryResource.Create(
                        language: "en-US",
                        query: request.QuestionText,
                        pathAssistantSid: request.AntonAssistantSid
                    );
                    
Please review this.

**Comment by hussain-github** [comment]
I am getting the same error. I installed the latest version (stable as noted) version (5.54.0). When I downgrade, I get error: Upgrade Required!

Are you willing to solve this issue anytime soon?

**Comment by JenniferMah** [comment]
We are currently working on a fix. In the mean time please roll back to version 5.53.1. Progress on this issue will be tracked in #556.

**Comment by sveinung61** [comment]
Hi, I'm new to Twilio - just started yesterday with installing the 5.54.0. I get this "Methode not found: ..." error. I have tried to uninstall the 5,54.0 version and install the 5.53.1 version. I'm now getting the error "Upgrade Required". What should I do? Wait for the fix?

**Comment by edika99** [comment]
Same problem here sending sms with very simple code

                var sms = MessageResource.Create(
                            body: message,
                            from: new Twilio.Types.PhoneNumber("+xxxxxxxxxxxxx"),
                            to: new Twilio.Types.PhoneNumber(number)
                        );


Downgrading to 5.53.1 it works again

**Comment by iosdevmw** [comment]
FYI, ran into the same issue trying to figure out Twilio SMS.  Thanks to edika99, had to downgrade to Twilio v5.53.1 and Twilio.AspNet.Mvc v5.37.2 to get past this issue.

**Comment by Paulwills** [comment]
Same issue Installing Twilio 5.55.0.

**Comment by joshsacks** [comment]
@Paulwills No, they fixed it in 5.55.0. Update your packages with reinstall, clean solution, then build.

**Comment by thinkingserious** [comment]
Thanks for helping out @joshsacks!

**Comment by jjrosado** [comment]
Same Twilio issue with .Net application. 
Twilio.6.3.0 - Framework 4.8 or grater
Twilio.6.2.5 - Framework 4.7.2
