### ISSUE TITLE
Classes should use strings, not Uri type

### ISSUE THREAD

**Issue by DanielStout5** [twilio/twilio-csharp#537]
There are a number of issues with how this library uses the `Uri` type in its objects, including:

1. Cannot represent empty string URIs: A valid value for Conference waitUrl (https://www.twilio.com/docs/voice/twiml/conference#attributes-waitUrl) and possibly other values within the Twilio API is an empty string, which you can't represent via the URI type, so far as I am aware. new Uri("") will throw `UriFormatException: Invalid URI: The URI is empty.`
2. Much harder to represent relative URIs: `new Uri("/test")` will throw `UriFormatException: Invalid URI: The format of the URI could not be determined.` on .Net Core 2.1, even though relative paths are what your documentation recommends

These URIs should all just be strings - you are blocking access to parts of your own API by changing them to Uri!

**Comment by dsghi** [comment]
Take a look at [Uri.MakeRelativeUri(Uri) Method](https://docs.microsoft.com/en-us/dotnet/api/system.uri.makerelativeuri)

**Comment by DanielStout5** [comment]
My point #2 isn't about whether it's possible, it's about whether it's convenient - and MakeRelativeUri is certainly not convenient!

It makes no sense to have converted this API wrapper from using Strings to the URI type, when your API accepts things that C# does not agree are valid URIs.

**Comment by DanielStout5** [comment]
For the benefit of future people: The library includes a type, `Twilio.Types.EmptyUri` which is a subclass of Uri that is hardcoded to represent "https://this.is.empty.url", which the serializer checks for and if found uses an empty string instead.

Which is an absurd workaround for the mistake of using `Uri` instead of `string`, if you ask me!

**Comment by dsghi** [comment]
I did not write any of this SDK, but my assumption is they made the decision to use URI over strings so there's less opportunity for errors. There's not much distance between easier and lazy when it comes to programming.

**Comment by childish-sambino** [comment]
Mostly makes sense to me. Do you have an example doc link that recommends using relative paths? Just trying to understand the use case where a relative path is needed.

**Comment by DanielStout5** [comment]
Every reference to a URL in the Twilio API documentation seems to say it can be relative or absolute:

https://www.twilio.com/docs/voice/twiml/dial
> action | Relative or absolute URL

https://www.twilio.com/docs/voice/twiml/redirect
> An absolute or relative URL for a different TwiML document.

https://www.twilio.com/docs/voice/twiml/gather
> action | URL (relative or absolute) | current document URL

**Comment by childish-sambino** [comment]
I see the examples there make use of `UriKind.Relative`: https://www.twilio.com/docs/voice/twiml/dial?code-sample=code-set-dual-channel-recording-on-dial-5&code-language=C%23&code-sdk-version=5.x

Does using this value suffice for your use case?

**Comment by gagandeepp** [comment]
Is it still open,I am willing to contribute on this?

**Comment by childish-sambino** [comment]
@gagandeepp I'm not convinced yet any change is required given my previous comment.

**Comment by DanielStout5** [comment]
Hm.. UriKind.Relative does partially fix it.

I would still say that just using a string is simpler and there is no benefit from having to wrap it in a Uri object like
```
new Dial(record: Dial.RecordEnum.RecordFromRingingDual, recordingStatusCallback: new Uri("www.myexample.com", UriKind .Relative))
```
instead of just
```
new Dial(record: Dial.RecordEnum.RecordFromRingingDual, recordingStatusCallback: "www.myexample.com")
```

It's not like an enum where using a string would let you make spelling mistakes and changing it to an enum provides actual compile-time validation. In fact if you use `UriKind.Relative` it doesn't seem to validate the format of the Uri at all: new Uri("fdgdfdf", UriKind.Relative) doesn't throw an exception

**Comment by childish-sambino** [comment]
The advantage here being that a relative URI like `new Uri("fdgdfdf", UriKind.Relative)` is perfectly _valid_ (though it may not point to anything that actually exists) and shouldn't throw an exception, and using absolute paths (w/o the relative param) will be checked and potentially throw. This sort of checking is part of why some prefer strongly-typed languages and I'm inclined to not make the change given there is a way to accomplish what's intended.

@coreylweathers @devinrader Thoughts?

_Note the we use `URI`s for both TwiML generation types as well as Twilio API request/response types._
