### ISSUE TITLE
Is System.IdentityModel.Tokens.Jwt version 5.1.2 necessary?

### ISSUE THREAD

**Issue by srajkovic** [twilio/twilio-csharp#543]
### Issue Summary
Do this dependency need to have this version or higher for .NET Framework?
```
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.1.2" />
```

We need to stick with version `4.0.40306.1554` of `System.IdentityModel.Tokens.Jwt` for compatibility with other libraries. Would it be possible to use this library with that version of `System.IdentityModel.Tokens.Jwt` as well, or does it require 5.1.2 for something?

**Comment by childish-sambino** [comment]
I don't see us downgrading this dependency to an even older MV given that 6.X has now been released. You may be able to use a binding redirect to resolve this, but it could depend on if the interfaces changed between the version your using and 5.1.2

**Comment by srajkovic** [comment]
Thanks! That's pretty much what I expected. We'll find a way to work around it, either via binding-redirect or otherwise.
