### ISSUE TITLE
What happened to Resources under Twilio.Rest.Notify.V1.Service?

### ISSUE THREAD

**Issue by drewid** [twilio/twilio-csharp#551]
It has been a few years since I have done C# work for Twilio but am confused by changes to the library that I cannot seem to track down with the repository or Google.  I have a fully working version before for managing users/segments/bindings/notifications

### Issue Summary
I have installed the current 5.52.1 version of Twilio and the following items are not functioning as expected.

### Steps to Reproduce
Created functions such as GetUsers, Get UserBindings, GetUserSegments, CreateUser, DeleteUser, GetSegments  to handle the calls for the various items below related to users and segments - but the following resources no longer seem to exist.

Where have they gone and what is the proper way to interact with users?

### Code Snippet
```
Twilio.Rest.Notify.V1.Service.UserResource.Fetch
Twilio.Rest.Notify.V1.Service.UserResource.Read
Twilio.Rest.Notify.V1.Service.User.UserBindingResource
Twilio.Rest.Notify.V1.Service.SegmentResource.Read
Twilio.Rest.Notify.V1.Service.User.SegmentMembershipResource.Create
Twilio.Rest.Notify.V1.Service.User.SegmentMembershipResource.Delete
etc.
```

**The following are example errors and the nuget package is definitely there and referenced in the file and acknowledged elsewhere in the code successfully.**

### Exception/Log
```
Error	CS0234	The type or namespace name 'UserResource' does not exist in the namespace 'Twilio.Rest.Notify.V1.Service' (are you missing an assembly reference?)

Error	CS0234	The type or namespace name 'SegmentResource' does not exist in the namespace 'Twilio.Rest.Notify.V1.Service' (are you missing an assembly reference?)
```

### Technical details:
* twilio-csharp version: 5.52.1
* csharp version: 8.0/9.0.  Having issues with both a .Net Core 3.1 and 5.0 project
* Visual Studio 2019

**Comment by thinkingserious** [comment]
Hello @drewid,

I see that those resources were removed in 2018. I'm currently investigating why and will report back here. Thank you!

With best regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @drewid,

Those features were deprecated just before GA and we currently have no plans to re-enable. You may use user tags and identities instead. 

With best regards,

Elmer
