### ISSUE TITLE
Using the library in multi-tenancy application 

### ISSUE THREAD

**Issue by babakdevoteam** [twilio/twilio-csharp#555]
### Issue Summary
We have a multi-tenant application and for each request we might use different auth-key and account id for twilio. But As it seems, the client for twilio created as a static class and we can not initiate it for different requests in our .net core api application. 

### Code Snippet
```csharp
https://www.twilio.com/docs/sms/quickstart/csharp-dotnet-core

        TwilioClient.Init(accountSid, authToken);

        var message = MessageResource.Create(
            body: "Join Earth's mightiest heroes. Like Kevin Bacon.",
            from: new Twilio.Types.PhoneNumber("+15017122661"),
            to: new Twilio.Types.PhoneNumber("+15558675310")
        );

```

### Technical details:
* twilio-csharp version: latest
* csharp version: .net core 3.1

**Comment by JenniferMah** [comment]
Hi @babakdevoteam
I'm a bit unclear about what the ask is here. Do you need to use different twilio accountSids and authTokens when initializing the client? Can you potentially use [subaccounts](https://www.twilio.com/docs/iam/api/subaccounts) instead of a new twilio account for each customer?

**Comment by joelweiss** [comment]
@babakdevoteam [this comment](https://github.com/twilio/twilio-csharp/issues/432#issuecomment-403305848) might be what you want.

HTH

**Comment by JenniferMah** [comment]
Thanks @joelweiss for the recommendation! @babakdevoteam please let us know if this doesn't cover your use case.

**Comment by babakdevoteam** [comment]
It works thanks
