### ISSUE TITLE
5.54.0: Method not found: 'System.String[] System.String.Split(Char, System.StringSplitOptions)' (AGAIN)

### ISSUE THREAD

**Issue by joshsacks** [twilio/twilio-csharp#556]
### Issue Summary
Exact same problem as #536 last year. The package must be built with the correct reference assemblies. See #538 for resolution.

### Technical details:
* twilio-csharp version: 5.54.0
* csharp version:

**Comment by mrtristan** [comment]
repro'd

**Comment by kyle30312** [comment]
I encountered the same problem. My app targets .NET Framework 4.8.
Reverting from 5.54.0 to 5.53.1 works for me as a stopgap measure.

```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.String[] System.String.Split(Char, System.StringSplitOptions)'.
  Source=Twilio
  StackTrace:
   at Twilio.Http.Request.buildUri()
   at Twilio.Http.Request.ConstructUrl()
   at Twilio.Clients.TwilioRestClient.Request(Request request)
   at Twilio.Rest.Api.V2010.Account.ConferenceResource.Read(ReadConferenceOptions options, ITwilioRestClient client)
...
```

**Comment by JenniferMah** [comment]
Thanks for bringing this to our attention. We are currently working on a fix. In the mean time please roll back to version 5.53.1

**Comment by sanjay11edt** [comment]
@JenniferMah on downgrading to version 5.53.1 or earlier then its gives "Upgrade required" message.

**Comment by Airhawk** [comment]
> @JenniferMah on downgrading to version 5.53.1 or earlier it gives "Upgrade required" message.
> 
> > Thanks for bringing this to our attention. We are currently working on a fix. In the mean time please roll back to version 5.53.1

Had the same issue, its not really a descriptive error. Its actually referring to TLS settings. Try:
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11;`

**Comment by edika99** [comment]
Same problem here sending sms with very simple code

            var sms = MessageResource.Create(
                        body: message,
                        from: new Twilio.Types.PhoneNumber("+xxxxxxxxxxxxx"),
                        to: new Twilio.Types.PhoneNumber(number)
                    );

Downgrading to 5.53.1 is the solution for me

**Comment by joshsacks** [comment]
@JenniferMah Any update? A new package was uploaded within a few hours last time this happened.

This issue, along with the still-unresolved #549, makes us question Twilio's devops practices of late. For all Jeff Lawson talks about Twilio being a "developer-centric" company, this is very troubling.

**Comment by eshanholtz** [comment]
The new version of twilio-csharp with the fix for this issue will be released tomorrow 2021-02-24.
