### ISSUE TITLE
Method not found: 'System.String[] System.String.Split(Char, System.StringSplitOptions)'

### ISSUE THREAD

**Issue by vpshonyak** [twilio/twilio-csharp#557]
Issue Summary
This .NETFramework nuget package was updated to version 5.54.0 and now breaks when calling MessageResource.Create( ...
Error: "Method not found: 'System.String[] System.String.Split(Char, System.StringSplitOptions)'".

Previous version 5.53.1 works fine.

**Comment by JenniferMah** [comment]
Hi @vpshonyak thanks for brining this to our attention. We are currently working on a fix. In the mean time please roll back to version 5.53.1. Progress on this issue will be tracked in #556.
