### ISSUE TITLE
Incorrect timezone when sending SMS messages.

### ISSUE THREAD

**Issue by DaveBagler** [twilio/twilio-csharp#558]
### Issue Summary
When I send an SMS message from my application the Created timestamp is in my local timezone (**EST**) however the documentation says it should be **UTC**. When I receive an SMS message through the webhook the Created timestamp is correctly in **UTC**. This creates a sorting issue in my database log of SMS messages.

### Steps to Reproduce
1. Send an SMS message using the API (Snippet below: `SendMessage`.)
2. Log the message to the database.
3. Check the Created timestamp in the database. 
4. Set up a webhook for receiving SMS messages for the number used to send the SMS message.
5. Reply to the SMS message sent in step one.
6. The reply will hit the webhook URL set up in step 4.
7. When the webhook is hit use the information to fetch the SMS message (Snippet below: `RetrieveMessageDetails`.)
8. Check the Created timestamp in the database for the reply. The Created timestamp for the message sent in step 1 is not UTC, the timestamp for the message sent in step 2.

<img width="685" alt="Screen Shot 2021-02-15 at 9 01 27 PM" src="https://user-images.githubusercontent.com/3266985/108010161-381a6000-6fd2-11eb-8aef-8fd2ee47cd32.png">

### Code Snippet
```csharp
        public async Task<SmsMessage> SendMessage(string from, string to, string body, string vendorId, string vendorToken)
        {
            CreateClient(vendorId, vendorToken);
            PhoneNumber toNumber = new PhoneNumber(to);
            PhoneNumber fromNumber = new PhoneNumber(from);

            CreateMessageOptions messageOptions = new CreateMessageOptions(toNumber) {
                From = fromNumber,
                Body = body,
            };

            MessageResource message = await MessageResource.CreateAsync(messageOptions, _client);

            return MapMessage(message);
        }

        private async Task<SmsMessage> RetrieveMessageDetails(string messageId, string vendorId, string vendorToken)
        {
            CreateClient(vendorId, vendorToken);

            FetchMessageOptions messageOptions = new FetchMessageOptions(messageId);
            MessageResource message = await MessageResource.FetchAsync(messageOptions, _client);

            return MapMessage(message);
        }
```

### Exception/Log
N/A

### Technical details:
* twilio-csharp version:  5.53.1
* Twilio.AspNet.Cire version: 5.37.2
* csharp version: C# 9 (.NET 5)
* I checked my web server and it is using UTC.
* I checked my database and it is using UTC.

**Comment by DaveBagler** [comment]
The issue is just on the initial send. I added a status callback webhook. If the status is sent, failed, delivered or undelivered, I've added a fetch, and I update the message in the database. The fetch provides the timestamps in the correct timezone.

**Comment by shwetha-manvinkurke** [comment]
Hi @DaveBagler the timestamps on the messages are set at the API layer in UTC when you make a call and this is not a helper library issue. That said, have you set a timezone in your Twilio project? I would also recommend reaching out to support if you need more help.

**Comment by DaveBagler** [comment]
Thanks, I'll reach out to Twilio for support. It does seem like it's not setting UTC on the initial call but then updating it to UTC on fetch.
