### ISSUE TITLE
Check if the authentication keys are valid

### ISSUE THREAD

**Issue by babakdevoteam** [twilio/twilio-csharp#560]
### Issue Summary
Is there a way to check if the authentication values, including the phone number, is  correct, before sending the SMS ? 

### Technical details:
* twilio-csharp version: 5.54.0
* csharp version: 8

**Comment by eshanholtz** [comment]
@babakdevoteam Hi, can you be a little more specific? Or do you have a code sample of what you want to accomplish?

**Comment by babakdevoteam** [comment]
The values we pass for sending the message are SID, AuthKey and FromNumber, before calling sms endpoint, is there any endpoint that we call to be sure that those values for credential are valid. Like TwiliSDK.IsCredentialValid(AuthKey, SID< FromNumber, );

**Comment by JenniferMah** [comment]
Hi @babakdevoteam,
We don't specifically have a `IsCredentialValid` function. The simplest way to verify your AuthKey, SID, and FromNumber would be to call the list command to see all the phone numbers associated with the account. You can follow the [example here](https://www.twilio.com/docs/phone-numbers/api/incomingphonenumber-resource?code-sample=code-list-all-incomingphonenumber-resources-for-your-account&code-language=C%23&code-sdk-version=5.x#linkcode) but replace `incomingPhoneNumber.Sid` with `incomingPhoneNumber.friendlyName` to verify which phone numbers are associated with that set of credentials. Does this cover your use case?
