### ISSUE TITLE
StatusCallbackEvent missing from CallResource.Update and UpdateCallOptions 

### ISSUE THREAD

**Issue by MarkRogersEx** [twilio/twilio-csharp#564]
### Issue Summary
When updating a call using `CallResource.Update`, there is no `StatusCallbackEvent` option, even though there is a `StatusCallback` and `StatusCallbackMethod`.  Which means while you can update the other parts of the status callback, you can't update the list of events for which the status callback is called.

### Steps to Reproduce
1. Get a call sid from an creating a call, or receiving one
2. Try to update the `StatusCallbackEvent`
3. Get compiler error

### Code Snippet

          `CallResource.Update(sid, statusCallback: completeUrl, statusCallbackMethod: HttpMethod.Post, statusCallBackEvent: "completed");`

### Exception/Log

> The best overload for 'Update' does not have a parameter named 'statusCallBackEvent'

### Technical details:
* twilio-csharp version: any
* csharp version: any

**Comment by eshanholtz** [comment]
Hi @MarkRogersEx 

Please reference the [Update a Call Resource documentation](https://www.twilio.com/docs/voice/api/call-resource#update-a-call-resource) for valid Call Update parameters. StatusCallbackEvent is not a supported update parameter. For further questions about this issue or a feature request for this underlying API functionality, please [reach out to support](https://twilio.com/help/contact)

**Comment by MarkRogersEx** [comment]
@eshanholtz - I have read the documentation.  But the issue is that I can set this parameter using the api but I can't using the C# library.  I have to conclude it was an oversight and an error on the part of the implementors unless there is some explanation for why this parameter was not included.  Does that make sense?

**Comment by eshanholtz** [comment]
@MarkRogersEx As far as I can tell by looking at the underlying API design, StatusCallbackEvent should not be a valid Update parameter option, by direct API call or via any helper library. This parameter should only be able to be set during Call Resource creation, so the behavior you're seeing with the CSharp helper library is expected. I'm confused by how you're able to set this parameter via direct update API call, so I still recommend [reaching out to support](https://twilio.com/help/contact) for further help and clarification.

**Comment by MarkRogersEx** [comment]
Fair enough but there's no explanation for why the parameter is missing in the docs.

**Comment by eshanholtz** [comment]
Why would the parameter be present in the docs if it's not a valid parameter for the API call you're trying to make?

**Comment by MarkRogersEx** [comment]
Because its used in creation.  in other cases the StatusCallbackEvent is used to determine when to make a status callback, but in this case I guess its always complete.  That seems like something that has to be inferred, when it might be easier to just state upfront, there's 'no StatusCallbackEvent parameter because its only triggered on completion (or whatever the case is)"

**Comment by eshanholtz** [comment]
There is [StatusCallbackEvent documentation in the official Twilio documentation](https://www.twilio.com/docs/voice/api/call-resource#statuscallbackevent).

**Comment by MarkRogersEx** [comment]
Yes, I've read that, I'm just saying why not mention that you can't use the StatusCallbackEvent after creation, in the update docs.  Then we wouldn't be having this conversation, so there's obviously a hole there.

**Comment by eshanholtz** [comment]
I discussed this a bit with our docs team and we generally want to include documentation for parameters that are supported, and avoid calling out parameters that cannot be used. If you still feel like this is an issue please reach out to support as I suggested in earlier comments to have your request reviewed by the docs team.

**Comment by MarkRogersEx** [comment]
ok, thanks, while I disagree with their conclusion, its nice that you looked into it.
