### ISSUE TITLE
Build Errors Blazor Server Component

### ISSUE THREAD

**Issue by MSIH** [twilio/twilio-csharp#568]
### Issue Summary
Adding Twilio directives to aps.net core 5.0 blazor component page gives the following errors:

- Error	CS0138	A 'using namespace' directive can only be applied to namespaces; 'Twilio' is a type not a namespace. 
- Error	CS0146	Circular base type dependency involving 'Twilio' and 'Twilio'

### Steps to Reproduce
1. Create blazor server project with .net 5.0
2. Add twilio package: Install-Package Twilio
3. Create Razor componet
4. Add directives to top of file

### Code Snippet
```csharp
@using Twilio;
@using Twilio.Rest.Api.V2010.Account;
@using Twilio.Types;
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-csharp version: 5.61.1
* csharp version: 5.0

**Comment by shwetha-manvinkurke** [comment]
@MSIH Do you have a custom type called `Twilio` defined in your project?

**Comment by MSIH** [comment]
i am not able to reproduce. I am going to close.
