### ISSUE TITLE
Twilio.Rest.Video.V1.Room.RoomRecordingResource : why does it not expose timestamps for start/end ?

### ISSUE THREAD

**Issue by cristihrs** [twilio/twilio-csharp#571]
### Issue Summary
Twilio.Rest.Video.V1.Room.RoomRecordingResource does not expose any property indicating the exact time the recording started/ended.
Especially since the new RecordingRules API has been published, recording in a video group room can be started/stopped for each participant any time.
In our implementation this may lead to the situation that after a video room has taken place and its video composed , the actual composed video hides some "gaps" when no recording was active and we would like to be able to know where these gaps occurred (so we can synchronize other data we track in association with the video room ).
At this moment, using the Recordings API doesn't seem to help.

As a side question , could we rely on "date_created" for recording resources (i.e. assume each recording has been created when it actually started ) ?

### Technical details:
* twilio-csharp version: 5.61.1.0
* csharp version:netcoreapp2.2

**Comment by thinkingserious** [comment]
Hello @cristihrs,

Thank you for taking the time to report this feedback and your use case.

In order to properly assist with this issue, since it is not related to this helper library, please [file a support ticket](https://twilio.com/help/contact).

Thank you!

With best regards,

Elmer
