### ISSUE TITLE
Ability to change AccountSid after custom client creation to allow reuse for multiple subaccounts

### ISSUE THREAD

**Issue by mikequ-taggysoft** [twilio/twilio-csharp#575]
### Issue Summary

I want to use the SDK via DI and inject my own `HttpClient` via .NET's `IHttpClientFactory`. I looked at the doc here:
[https://www.twilio.com/blog/dependency-injection-twilio-sms-asp-net-core-2-1](https://www.twilio.com/blog/dependency-injection-twilio-sms-asp-net-core-2-1)

However, it seems the `AccountSid` property was made read-only for `TwilioRestClient` that can be only populated at construction time. 

Since our app is an ISV use case that will perform transactions on multiple subaccounts, I believe we'll need to initiate requests later with different subaccount sids. This means the pattern in the doc above won't work, and instead we'll probably have to inject the `HttpClient` into our service layer class and use it to construct a new `TwilioRestClient` each time we need to make a call against a sub account.

Is there a reason why this property has to be read-only?

**Comment by shwetha-manvinkurke** [comment]
The helper lets you initialize the client with a `username-password` (or `accountsid-authtoken`) or `username-password-accountSid` combo. In the case with `username-password-accountSid`, the username and password will be the auth for the account (parent) and the `accountSid` is for the subaccount. The second accountSid is mainly used for the [v2010 apis](https://github.com/twilio/twilio-csharp/tree/main/src/Twilio/Rest/Api/V2010). In addition to these, the v2010 apis also take in an `AccountSid` as a path parameter that would take precedence over the subaccount and the parent account sids.

**Comment by mikequ-taggysoft** [comment]
@shwetha-manvinkurke So I want to use the API keys instead of the main account tokens. I assume `username` is `keySid` in this case, and `password` is `keySecret`. Then do I still need to pass in the main `accountSid` during client initialization? 

Once the client is initiated this way, it can be used to perform master account level operations. But say I want to order a new phone number for a _subaccount_, then in that particular call I just pass in the subaccount's `accountSid` at the method level, which will override the `accountSid` set at the client level during client initialization, right?
