### ISSUE TITLE
How to get the message details with MessageID

### ISSUE THREAD

**Issue by shaangidwani** [twilio/twilio-csharp#578]
After sending any message no REST API methods for fetching details of that particular message using ID. There should be API in which user can fetch the details anytime without using WEBHOOK.

RestAPI is design for get and send the information anytime so it should be API for fetching the message information including tracking using individual API not with WEBHOOK because WEBHOOK is not fit for all organization.

**Comment by shwetha-manvinkurke** [comment]
There is an API to fetch a message by the SID. Please go over [this](https://www.twilio.com/docs/sms/api/message-resource?code-sample=code-fetch-message&code-language=C%23&code-sdk-version=5.x) documentation and reach out to support if further help is needed
