### ISSUE TITLE
I need Twilio.Api version 3.4.1 but the Nuget package for this version actually contains version 3.3.6

### ISSUE THREAD

**Issue by edgariscoding** [twilio/twilio-csharp#586]
I need to install a specific version of Twilio.Api but when I install version 3.4.1 from the Nuget Package Manager in Visual Studio I end up with version 3.3.6, which breaks our build. 

CSPROJ ref 
```
    <Reference Include="Twilio.Api, Version=3.3.6.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Twilio.3.4.1\lib\3.5\Twilio.Api.dll</HintPath>
    </Reference>
```

Am I doing something wrong?

**Comment by edgariscoding** [comment]
Looks like I had to install Twilio.Api package version 4.7.2 to get Twilio.Api version 3.4.1 along with the exact dependencies I needed. This seems like a bug no? Shouldn't the package version reflect the actual version contained within?

**Comment by shwetha-manvinkurke** [comment]
Hi @edgariscoding the latest version of the package `Twilio` is 5.68.0 and we do not own the `Twilio.Api` if [this](https://www.nuget.org/packages/Twilio.Api/) is what you are referring to

**Comment by eshanholtz** [comment]
Closing due to lack of customer response.
