### ISSUE TITLE
Problem in accessing Capability API

### ISSUE THREAD

**Issue by mkmurali** [twilio/twilio-csharp#6]
"Could not load file or assembly 'Newtonsoft.Json.Net35, Version=4.0.2.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json.Net35, Version=4.0.2.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified."

Rest of the API is working fine.

**Comment by henrihietala** [comment]
I'm still having this exact same issue. Versions in use: 
.NET 4.5.2
Twilio 4.1.0
Twilio.Client 3.4.4

I'm trying to follow this tutorial: https://www.twilio.com/docs/quickstart/csharp/client/hello-monkey

I get the following error on line 9: string token = capability.GenerateToken();

Could not load file or assembly 'Newtonsoft.Json.Net35, Version=4.0.2.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json.Net35, Version=4.0.2.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

Source Error: 


Line 14:     capability.AllowClientOutgoing(appSid);
Line 15:     capability.AllowClientIncoming("Innofactor");
Line 16:     string token = capability.GenerateToken();
Line 17: }
Line 18:

**Comment by bslatner** [comment]
I'm also having this issue. .NET 4.5, Twilio 4.2.1, Twilio.Client 3.4.4. 

I get the message about not being able to load Newtonsoft.Json.Net35.

I require a newer version of Newtonsoft.Json. Binding redirects don't work.

**Comment by carlosdp** [comment]
There's an active issue on this at #190
