### ISSUE TITLE
MessagingResponse's statusCallback not working

### ISSUE THREAD

**Issue by angelaki** [twilio/twilio-csharp#613]
Right now your MessagingResponse class just answeres with a message (like it was a new, sent one). When setting a `statusCallback` the result could e.g. look like this:

```
<?xml version="1.0" encoding="utf-8"?>
<Response>
	<Message statusCallback="https://my.callback.service/Twilio/Sms/Status">Hey there ! How 'bout those Seahawks?</Message>
</Response>
```

**But** according to the documentation, the attribute must be named **action** instead (https://www.twilio.com/docs/sms/tutorials/confirm-delivery-csharp-aspnet-mvc):

```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Message action="http://postb.in/b/1234abcd">This message will be tracked!</Message>
</Response>
```

It took me a while to find this ;). I already tried to just change it and make a PR but you're using the `Message-Class` where actually `statusCallback` is the right name for the property. For not deploying a breaking change I'd recommend your API to accept both `statusCallback` and `action`? Right now your lib https://github.com/twilio-labs/twilio-aspnet utilizing the `[TwiMLResult](https://github.com/twilio-labs/twilio-aspnet/blob/main/src/Twilio.AspNet.Core/TwiMLResult.cs)` isn't working because of this.

**Comment by angelaki** [comment]
In cooperation with one of your customer supporters I've just realized that the `MessagingResponse` already has an `action` proprety. But why is there also a (useless) `statusCallback`? Is it deprecated?

**Comment by rakatyal** [comment]
Hi @angelaki, statusCallback is indeed [deprecated](https://github.com/twilio/twilio-csharp/blob/main/src/Twilio/TwiML/MessagingResponse.cs#L36) in favor of action. Is there anything else we can help you with?

**Comment by angelaki** [comment]
No, that's it.
