### ISSUE TITLE
Filter in HSM templates listing are not applied

### ISSUE THREAD

**Issue by weltonbatist** [twilio/twilio-csharp#626]
### Issue Summary
Hello everyone, everything good?
I'm using the following method to list HSM/WhatsApp templates TemplateResource.ReadAsync() however, when I try to assemble a filter, passing exactly the name of the template in the friendlyName property, nothing is returned. The Template exists in the account and has already been approved, but only pre-approved templates are returned. Any idea what it could be? I looked in the documentation, but didn't find any help.

### Code Snippet
```csharp
var templates = await TemplateResource.ReadAsync(options, _client);
```

### Technical details:
* twilio-csharp version: 5.75.3
* csharp version: 10

**Comment by claudiachua** [comment]
Hi @weltonbatist, In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).
