### ISSUE TITLE
Update System.IdentityModel.Tokens.Jwt to fix Apple authentication

### ISSUE THREAD

**Issue by Swimburger** [twilio/twilio-csharp#629]
The update to `System.IdentityModel.Tokens.Jwt` 6.19.0 broke something in the Apple authentication, as discussed [here](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1861).
This was reported over at the [Twilio helper library for ASP.NET](https://github.com/twilio-labs/twilio-aspnet/issues/82).

For anyone else running into this issue, I suggest you explicitly add at least version 6.20.0 of the `System.IdentityModel.Tokens.Jwt` package and `Microsoft.IdentityModel.Tokens` package.

Could you update the Twilio helper library to update the dependency of `System.IdentityModel.Tokens.Jwt` and `Microsoft.IdentityModel.Tokens` to 6.20.0 or higher?

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the **issue summary** will help it move up the backlog (ref DI-2326).

**Comment by tiwarishubham635** [comment]
Closing it as it will be addressed by #739
