### ISSUE TITLE
Cannot add multiple media objects to a Conversation message?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [twilio/twilio-csharp#647]
Can somone please advise as to how I can get multiple media objects added to a new or existing Conversation message using the Helper Libraries...

On the POST to create a new message the media value is a simple string, and there is no media entry available at all on the update POST.

The client side API (browser/websocket) supports something like this:

```
await testConversation.prepareMessage()
    .setBody('Hello!')
    .setAttributes({foo: 'bar'})
    .addMedia(media1)
    .addMedia(media2)
    .build()
    .send();
```

How can I accomplish this via REST/Helper API?

**Comment by AsabuHere** [comment]
Currently, Media Content Service (MCS) provides the underlying Media REST endpoint used to create (upload) the media (files). It is a separate endpoint and not supported in the Twilio Helper Libraries or the Twilio CLI.

Sending a Media Message via the REST API is a two-step process:

1. First, upload the media file to Twilio's Media Content Service (MCS) via the REST API
2. Send a media message to the Conversation by attaching the media instance that you created in Step 1 to a new Conversation Message
Please refer to this documentation for more information regarding this : https://www.twilio.com/docs/conversations/media-support-conversations#retrieving-media-message-content

**Comment by mfreeman-xtivia** [comment]
I think you missed the point of my issue.

The question was whether it was possible, using the C# helper library, to add *MULTIPLE* media IDs to a single message object, given that those items had been previously uploaded to MCS. Outside of this GitHub issue Twilio support has confirmed that it is not possible using C#, since the generated API only accepts a single MExxx identifier.

**Comment by AsabuHere** [comment]
yes, this is not supported using C# helper library, only one identifier will be accepted as of now
