### ISSUE TITLE
Broken `CreateParticipantOptions` parameters in v6

### ISSUE THREAD

**Issue by Swimburger** [twilio/twilio-csharp#656]
In previous versions of the C# library the `MessagingBindingAddress` and `MessagingBindingProxyAddress` properties for the `CreateParticipantOptions` class would translated into `MessagingBinding.Address` and `MessagingBinding.ProxyAddress` parameters before submitting to the REST API.
However, in v6 it is now `MessagingBindingAddress` and `MessagingBindingProxyAddress` which are ignore by the REST API.

[Code v5](https://github.com/twilio/twilio-csharp/blob/5.81.2/src/Twilio/Rest/Conversations/V1/Conversation/ParticipantOptions.cs#L80-L88) vs [Code v6](https://github.com/twilio/twilio-csharp/blob/main/src/Twilio/Rest/Conversations/V1/Conversation/ParticipantOptions.cs#L79-L86).

It should be `MessagingBinding.Address` and `MessagingBinding.ProxyAddress` or it won't work. I'm not sure if there are other APIs that have similar dot-notations that are affected in v6.

**Comment by AsabuHere** [comment]
Hey @Swimburger, thanks for submitting this issue. It's been added to our internal backlog to be prioritised, +1s and pull requests on the issue summary will move it further up the backlog.

**Comment by wluke** [comment]
This is also effecting us - it makes the Conversations API useless as it's not possible to add an SMS participant!

**Comment by AsabuHere** [comment]
This issue is fixed in the latest version (6.2.0)

**Comment by Swimburger** [comment]
Just tested creating a conversation and adding a participant using phone numbers, worked as expected.
Thank you~
