### ISSUE TITLE
Start a new verification for a phone number with an expired state

### ISSUE THREAD

**Issue by Spaeda** [twilio/twilio-csharp#664]
### Issue Summary
When a verify request has been sent for a phone number, a code is generated and send to it. 
If user doesn't confirm it before expiration, it's impossible to start a new validation. Verification is set to expired and all new start will return a `too many requests` exception.
I try to fetch it but I have another exception `The requested resource /Services/VAxxx/Verifications/VExx was not found"}` but this service is listed in console but on expired state.

How can I start a new verification for a phone number with another in expired state?

### Steps to Reproduce
1. Start a verification with a phone number
2. Wait expiration
3. Try to start a verification for same phone number

### Code Snippet
```csharp
using Twilio;
using Twilio.Rest.Verify.V2.Service;

TwilioClient.Init("AccountSid", "AuthToken");
var serviceResourceSid = "VAxx";
var serviceSid = "VExx"; // id previously created by a verification request
var phone = "";

try
{
    var verifResx = VerificationResource.Create(new CreateVerificationOptions(serviceResourceSid, phone, "sms"));
}
catch (Exception e)
{
    Console.WriteLine(e.Message);
}

// Code used to fetch a verification service
try
{
    var verifResx = VerificationResource.Fetch(serviceResourceSid, serviceSid);
}
catch (Exception e)
{
    Console.WriteLine(e.Message);
}
```

### Exception/Log
```
Exception return by create method:
Twilio.Exceptions.ApiException: Too many requests\r\n   at Twilio.Clients.TwilioRestClient.ProcessResponse(Response response)\r\n   at Twilio.Clients.TwilioRestClient.Request(Request request)\r\n   at Twilio.Rest.Verify.V2.Service.VerificationResource.Create(CreateVerificationOptions options, ITwilioRestClient client)\r\n   at Program.<Main>$(String[] args)

Exception return by fetch method:
Twilio.Exceptions.ApiException: The requested resource /Services/VAxx/Verifications/VExx was not found\r\n   at Twilio.Clients.TwilioRestClient.ProcessResponse(Response response)\r\n   at Twilio.Clients.TwilioRestClient.Request(Request request)\r\n   at Twilio.Rest.Verify.V2.Service.VerificationResource.Fetch(FetchVerificationOptions options, ITwilioRestClient client)\r\n   at Program.<Main>$(String[] args)
```

### Technical details:
* twilio-csharp version: 6.2.1
* csharp version: 6.0

**Comment by isha689** [comment]
Hi @Spaeda, thanks for reaching out.

I have tried the same thing and I am able to start a new verification for the same phone number after the previous verification expired. Can you please help us with the complete logs/debug information ?

**Comment by Spaeda** [comment]
Hi,
Thanks for your reply, we finally found origin of our issue. It was just the pricing plan, we update it from Trial and all work fine.
