### ISSUE TITLE
Drop target frameworks that Microsoft doesn't support

### ISSUE THREAD

**Issue by Swimburger** [twilio/twilio-csharp#667]
Microsoft supports the following target frameworks at this time:
- .NET Framework 4.6.2 and up
- .NET 6 and up
I suggest removing target frameworks netstandard1.4 and net451.
These would be the TFM's targeted: netstandard2.0;net35.

This would continue to support all the versions that Microsoft supports.

See [.NET support](https://dotnet.microsoft.com/en-us/platform/support/policy) and [.NET Framework support](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework).

**Comment by kridai** [comment]
Thanks for the PR! We've added the review to our backlog to be prioritised. +1s on the issue summary will help it move up the backlog.

**Comment by sbansla** [comment]
We have dropped the support of older versions.
Please refer latest twilio-csharp version 7.0.1 in nuget.
