### ISSUE TITLE
Toll Free AvailablePhoneNumbers resource supports filtering by AreaCode but the library does not support this

### ISSUE THREAD

**Issue by kevinburke** [twilio/twilio-csharp#67]
Per the documentation, you can filter by AreaCode in addition to contains:

http://www.twilio.com/docs/api/rest/available-phone-numbers#toll-free-get-filters

It would be nice if we could do

```
public AvailablePhoneNumberResult ListAvailableLocalPhoneNumbers(string isoCountryCode, AvailablePhoneNumberListRequest options)
```

for TollFree numbers but this function for toll-free already has a 2-argument method overload, I am not sure if you can overload with a different type.

**Comment by jingming** [comment]
This has been added in `5.0.0`
