### ISSUE TITLE
MissingMethodException on 6.3.0

### ISSUE THREAD

**Issue by joshsacks** [twilio/twilio-csharp#676]
### Issue Summary
Same issue as #536 and #556. Please once again see #538 for how to setup the NuGet package.

### Technical details:
* twilio-csharp version: 6.3.0

**Comment by sbansla** [comment]
Hi @joshsacks I will be checking this issue.
Can you please let us know which api or share on which code you are getting this error.

**Comment by joshsacks** [comment]
Let me clarify the issue. The .NET 4.5.1. DLL is being built to call a String.Split() overload that doesn't exist in mscorlib.

This is your line of code:
<img width="794" alt="image" src="https://user-images.githubusercontent.com/11070846/228011081-a6e92355-8bd3-49d5-b14b-79530a72bf08.png">

Which on **6.30.0** gets translated to:

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/11070846/228013666-0f7bff93-c261-4769-860e-f952491d8ca0.png">

Now compare that to **6.25.0**:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/11070846/228013524-23d39d87-4cfc-415c-85f6-9288cd26a215.png">

The way to resolve this is to either fix the reference assemblies in your builder as was done to resolve #536 and #556, or call the correct overload directly by explicitly making Request.cs:32 var pieces = uriBuilder.Host.Split(new char[] { '.' });

**Comment by mnoreen** [comment]
I am also running into this bug.  I created a new standalone console app (C#, .NET Framework 4.8).  I used nuget pkg manager to add twilio and dependecies, updated all the dependencies to latest versions (a very long dependency chain now... !).   Then I added a simple bit of code:

`
TwilioClient.Init(SMS.AccountSID, SMS.AccountToken);

MessageResource message = MessageResource.Fetch(messageSID);
`

And the .Fetch call results in an exception:

Method not found: 'System.String[] System.String.Split(Char, System.StringSplitOptions)'.

**Comment by joshsacks** [comment]
@shrutiburman Is there any progress on this?

**Comment by shrutiburman** [comment]
We've identified the issue that has caused this. The environment used to build this nuget package was 6.3.0 which unfortunately is not backwards compatible. 
We'll be resolving this in our scheduled upcoming release (next Wednesday), till then it's advised to downgrade to [6.2.5](https://github.com/twilio/twilio-csharp/releases/tag/6.2.5).

**Comment by sbansla** [comment]
twilio-csharp is used to be build using dotnet-version: '3.1.x' ([link](https://github.com/twilio/twilio-csharp/blob/main/.github/workflows/test-and-deploy.yml#L27))
This time it was build using .net 6 because of which certain dependencies are not installed.
This will be fixed in upcoming release.

**Comment by sbansla** [comment]
Hi @joshsacks,
We have releases 6.4.0 version, Can you please test with this version.

**Comment by joshsacks** [comment]
It works.
