### ISSUE TITLE
Twilio depends on NUnit

### ISSUE THREAD

**Issue by reduckted** [twilio/twilio-csharp#734]
### Issue Summary
Twilio 7.0.0 now has dependencies on `NUnit` and `NUnit3TestAdapter`.

![image](https://github.com/twilio/twilio-csharp/assets/10321525/4cf0849a-ea9e-4859-8934-c9ea2dc74126)

https://github.com/twilio/twilio-csharp/blob/c33b9f0e3b27b8cc22902d1dfa7b573ce7ac6c06/src/Twilio/Twilio.csproj#L28-L34

### Steps to Reproduce
N/A

### Technical details:
* twilio-csharp version: 7.0.0
* csharp version: N/A

**Comment by joshsacks** [comment]
Yes, this reference is unnecessary. It's only used in the Twilio.Test project, not anywhere in the main library code.

**Comment by sbansla** [comment]
This will be taken care in next release.

**Comment by sbansla** [comment]
7.0.1 is released by removing NUnit dependencies.

**Comment by reduckted** [comment]
> @sbansla 7.0.1 is released by removing NUnit dependencies.

7.0.1 is marked as deprecated. https://www.nuget.org/packages/Twilio/7.0.1
