### ISSUE TITLE
SMS body length still limited to 160 characters; should be 1600

### ISSUE THREAD

**Issue by darrylwhitmore** [twilio/twilio-csharp#90]
After upgrading to the latest twilio-csharp (3.6.1) via NuGet I am still getting error 21605 "Maximum body length is 160 characters" when trying to send an sms over 160 characters. 

Per the recent announcement (https://www.twilio.com/blog/2013/09/twiliocon-2013-announcing-picture-messaging-price-drop-business-critical-apps-and-more.html), the limit should be 1600.

**Comment by rmamedov27** [comment]
So, is there a way to use twilio-csharp library to send a message body longer than 160 characters? Which class/method should we use?

**Comment by devinrader** [comment]
@rmamedov27 as mentioned above, the SendMessage method will let you send a message up to 1600 bytes.
